### ISSUE TITLE
path match explanation 

### ISSUE THREAD

**Issue by git001** [haproxytech/kubernetes-ingress#1]
in the kubernetes slack channel are some questions about how a `path` in a ingress controller is matching.  
As far as I have seen in the code the match is with `path_beg` https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.6-path , it this right?  
Please can you clarify this fact in the docs https://www.haproxy.com/documentation/hapee/1-9r1/traffic-management/kubernetes-ingress-controller/  
How about to add a `regex` flag which then use `path_reg` instead of `path_beg`?

**Comment by oktalz** [comment]
Hi,
yes, the match is done with `path_beg`, this will be added to docs.
Also adding regex (`path_reg`) as an option shouldn't be a problem.

**Comment by git001** [comment]
Any update on this issue about `regex ` match?

**Comment by git001** [comment]
as I mentioned in #131 

How about to use the new [Path Types](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) from the fresh updated [Ingress]( https://kubernetes.io/docs/concepts/services-networking/ingress/) doc.  
It's related to [Graduate Ingress to V1](https://github.com/kubernetes/enhancements/issues/1453)

**Comment by Mo3m3n** [comment]
> How about to use the new Path Types from the fresh updated Ingress doc.

That's the case now 
Thanks for reporting this.
