### ISSUE TITLE
Support for "pathless" ingress rules

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#10]
Hi,

Kubernetes allows writing such type of rule:
```spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: http
```
Based on the rule above, the current Ingress Controller (1.0.1) generates the following configuration:
```use_backend service1 if { req.hdr(host) -i foo.bar.com } { path_beg  }```

Unfortunately, the acl { path_beg } will never match and this backend will never receive any traffic.

Basically, if no **path** is provided, we should not set any **path_beg** acls.

**Comment by oktalz** [comment]
Hi, 
this is now available.
But keep in mind that either host or path (or both) must be present
