### ISSUE TITLE
Cluster Role is required

### ISSUE THREAD

**Issue by joshgibs** [haproxytech/kubernetes-ingress#105]
https://github.com/haproxytech/kubernetes-ingress/blob/30e43d5af02a32a0b7169a07d28fc433ac61a7d3/kubernetes-api.go#L259

Will there be an update that allows the ingress controller to run in a single namespace without requiring access to all namespaces?  I cannot use this controller until then.

**Comment by oktalz** [comment]
Hi @joshgibs 

RBAC is fully suported, 
also you can limit ingress to specified namespaces (multiple or one) on start 
if you use `--namespace-whitelist`

Please see the [doc](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md) how to use it
