### ISSUE TITLE
How to route to internal service loadbalanced by haproxy ingress 

### ISSUE THREAD

**Issue by cjroebuck** [haproxytech/kubernetes-ingress#108]
I have two 'layers' of services in my app, the first one is a thin 'api' layer which is exposed via the ingress. It makes a call to a second service, let's call this the 'engine' service. This engine service is designed to be called privately via the api service:
```
+------> LB +---> INGRESS +---> API SVC +---> ENGINE SVC
```
The engine service is quite a heavy process and is backed by many pods, so efficient loadbalancing is really important to distribute the load evenly. If I send requests to the default kubernetes provided service e.g. 'http://engine.namespace.svc', it ends up not distributing the requests efficiently to the backend pods - one pod ends up taking the majority of the requests and the rest of the pods are sat empty. (For me this seems to defeat the point of the default k8s service and hpa but that is a separate point...!).

If I expose the engine service via ingress and route requests back out to the publicly addressable ingress e.g. engine.example.com, then haproxy loadbalances the requests a lot better than the default kube-proxy 'random' ip-tables implementation which k8s service uses.
```
                HOST: ENGINE.EG.COM
          +-----------------------+
          |                       |
          |                       +
          |                +---> API
          v                |
 +------> LB +---> INGRESS |
                           |
                           +---> ENGINE
```

But this 'feels' like a bit of a hack in order to get haproxy loadbalancing for an internal service. Is this the right way of doing what I want? I cannot find any docs that deal with using ingress to loadbalance internal services and how to route to them. 

PS I cannot switch to `ipvs` based routing as i'm using a hosted k8s implementation (digitalocean) and seemingly have little control over how kube-proxy is initialised.

**Comment by bedis** [comment]
Hi

This looks like a common North/south and East/West traffic or to make it simple, an external versus internal traffic splitting.
I would leverage the "class" function provided by the HAProxy ingress and start up 2 different ingresses:
- one ingress to manage "external" traffic, deployed as a deamonSet and use host IP network (but other type of deployments are valid too).
  Set the Ingress Controller Configmap annotation `ingress.class` to "external"
- one ingress to manage "internal" traffic, deployed as a standard deployment + ClusterIP service
  This ingress would not have any `ingress.class`.

Now, you when you create your ingress rules, you can add an annotation such as `kubernetes.io/ingress.class: "external"` to expose it on the outside world.
If you don't set this annotation, it will be set by default to the internal ingress controller.
This also has this advantage of preventing service "leak"...

Last, you need to update your DNS to point your engine.eg.com to the ClusterIP of the internal LB. Kubernetes may help using https://kubernetes.io/docs/concepts/services-networking/service/#externalname

**Comment by cjroebuck** [comment]
Awesome, this sounds exactly what I wanted. Thanks!

**Comment by aep** [comment]
this is exactly what we're doing where shocked to discover that ingress ignores the class and routes all backends on all instances, so there the separation seems to work, but actually you can just use SNI on the external service to get to the internal one


```
curl -k -i  https://internal.service/ --connect-to internal.service:443:external-ip:443
```

**Comment by ericescalante** [comment]
In my case in GKE I installed the controller helm chart twice using different namespaces setting these values:

For internal-only traffic:
```
    --set controller.ingressClass=haproxy-internal \
    --set controller.ingressClassResource.name=haproxy-internal \
    --set controller.service.type=ClusterIP
```

For external-only traffic:
```
    --set controller.ingressClass=haproxy-external \
    --set controller.ingressClassResource.name=haproxy-external \
    --set controller.service.type=LoadBalancer
```

Then created Ingress resources setting the `ingressClassName` accordingly for either internal or external traffic.
