### ISSUE TITLE
http-request set-header X-DeviceAtlas-Data

### ISSUE THREAD

**Issue by nirmalpathak** [haproxytech/kubernetes-ingress#109]
Is it possible to add DeviceAtlas Device Detection support with ingress rule?

Ref:- https://fossies.org/linux/haproxy/doc/DeviceAtlas-device-detection.txt

**Comment by Mo3m3n** [comment]
This is possible since `haproxytech/kubernetes-ingress:1.4.0` 
You can use the `request-set-header` annotation documented here: https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#request-set-header
