### ISSUE TITLE
configure the proxy with amazon ALB

### ISSUE THREAD

**Issue by icy** [haproxytech/kubernetes-ingress#118]
Hi there,

I'd like to use haproxy however I get trouble finding a way to get it work with amazon ALB. Is that possible and if 'yes' do you have any documentation?

Thanks a lot.

**Comment by bedis** [comment]
Hi,

can you give us more details on the infra you want to set up and what issues you're facing?

**Comment by icy** [comment]
hi @bedis, I've found a lot of details in this article https://www.haproxy.com/blog/dissecting-the-haproxy-kubernetes-ingress-controller/ , I will try to follow it and get back if I have any issues. Thanks
