### ISSUE TITLE
Ingress status update on Kubernetes resource

### ISSUE THREAD

**Issue by inge4pres** [haproxytech/kubernetes-ingress#125]
Hello, thank you for developing this controller.
While testing we noticed that an ingress update on the backend does not update the Kubernetes Ingress API object `status` with the external address of the resource.
This is due to missing logic in [kubernetes-api.go#L255](https://github.com/haproxytech/kubernetes-ingress/blob/828787a95ee2072e2bdf66f2f034de2229542025/kubernetes-api.go#L255) where the API Informer is notified of an ingress it should later update the resource status with the `Service` routing traffic to ingress pods: this is achievable by reading the Service in which haproxy-ingress pods are deployed.
That'd be nice to have when reading ingress data from kubectl.
Ideas?

**Comment by Mo3m3n** [comment]
Hey @inge4pres 
Thank you for your feedback and your interest in our controller.
You're right, right now we don't update the ingress API `status`.
In addition to what you said, this also prevents tools relying on the `status` from working. External-dns as an example.
So this is in our roadmap and I hope it will be available before the end of the month.

**Comment by inge4pres** [comment]
Nice to hear! If I find enough time I try and craft a PR, just getting confident with the code right now so I can align to the current design 😄

**Comment by Mo3m3n** [comment]
Sure, We welcome PRs :)
Don't hesitate to get back to us if you have questions about  the code and design of the controller.
You can find us in "ingress-controller" channel in slack haproxy.slack.com

**Comment by Mo3m3n** [comment]
Hey @inge4pres 
This feature is available starting from 1.3.1 release. 
You can use it via the `--publish-service` argument https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md
Let us know if you have any feedback

**Comment by inge4pres** [comment]
Great news! Thanks 😊 Not sure we will have time to test this soon, but I have a question: is it a flag and you intend to have it as opt-in for testing? It should probably be the default behavior for an ingress controller to update the status of Kubernetes objects

**Comment by Mo3m3n** [comment]
Yes this is controller command line argument.
Well the controller is pushing the addresses of a Service endpoints, so it needs to know what service  to use. You have other scenario in mind ?

**Comment by inge4pres** [comment]
Ideally there should only be 1 service for all ingresses and this should be the `LoadBalancer` that connects the external world with the pods inside Kubernetes. You're saying it's left to the user determine which service endpoint is used for ingress, and this is just reflected in the ingresses `status`es?

**Comment by Mo3m3n** [comment]
> Ideally there should only be 1 service for all ingresses and this should be the LoadBalancer that connects the external world with the pods inside Kubernetes.

I agree, but afaik the controller won't be able to guess what is the right service and this needs to be provided as input.
> You're saying it's left to the user determine which service endpoint is used for ingress, and this is just reflected in the ingresses statuses?

Yes the user provides the service path: namespace/service-name. Or this can be automatically configured by third party tool like with Helm Chart: https://github.com/haproxytech/helm-charts/commit/33aea3e87d27d06bfa05e9a81548d36d4681d4da , because the service is defined within the Chart and there is no confusion about which service to use (unless the user overrides the default value)
