### ISSUE TITLE
case-insensitive path matching

### ISSUE THREAD

**Issue by Mo3m3n** [haproxytech/kubernetes-ingress#131]
Add an option to make the patch matching of ingress rules case-insensitive

**Comment by git001** [comment]
How about to use the new [Path Types](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) from the fresh updated [Ingress]( https://kubernetes.io/docs/concepts/services-networking/ingress/) doc.  
It's related to [Graduate Ingress to V1](https://github.com/kubernetes/enhancements/issues/1453)

**Comment by ailenli** [comment]
> How about to use the new [Path Types](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) from the fresh updated [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) doc.
> It's related to [Graduate Ingress to V1](https://github.com/kubernetes/enhancements/issues/1453)

Path Types : Exact Prefix
sometimes  wants to match regex

**Comment by Mo3m3n** [comment]
Path type (exact match and Prefix) are support from 1.5
Thanks for the initiative of suggesting it.
