### ISSUE TITLE
Improve logging infrastructure

### ISSUE THREAD

**Issue by interone-ms** [haproxytech/kubernetes-ingress#133]
During investigating a bug in which haproxy ended up creating backend rules that round-robin'd traffic to all workloads in a namespace instead of only the workload that was targeted (which turned out to be either a k8s or Rancher bug, I suspect the latter), I noticed that there is almost no logging infrastructure present, with `DEBUG_API` in `kubernetes-api.go` the only place with conditional logging, enabled at compile time.

I'd recommend setting up log levels (that also offer tracing detailed data what the controller obtains from k8s!) and an infrastructure to change the log levels and output at either runtime or start time via annotations.

edit: rancher itself uses logrus (https://github.com/sirupsen/logrus), this should be a drop-in replacement for the current log calls.

**Comment by Mo3m3n** [comment]
This issue went under the radar, but we have already [--log](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--log) controller arg to set debug level
