### ISSUE TITLE
Support for "SSL re-encryption

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#135]
In some cases, the connection to the server has to be ciphered.
This would required 2 things in the HAProxy configuration:
* add `ssl` sur the server line
* (optional) configure a `ca-file` to validate the cert presented by the server

If no `ca-file` is provided, then we should add `verify none` to disable server certificate validation

**Comment by bedis** [comment]
Of course, would be great to have a watcher to monitor the ca-file cert and to update HAProxy accordingly when it's updated.

**Comment by andreasdrougge** [comment]
I have done a simple version with no ca-file support here:
https://github.com/haproxytech/kubernetes-ingress/pull/143

**Comment by Mo3m3n** [comment]
server-ssl and server-ca and server-crt should answer this requirement.
