### ISSUE TITLE
Support for mTLS on the server side

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#136]
Might be related to #135 

Support for `crt`keyword on the server side in case a server requires mTLS

**Comment by bedis** [comment]
Of course, would be great to have a watcher to monitor the certificate and to update HAProxy accordingly when it's updated.

**Comment by Mo3m3n** [comment]
This is available in 1.5 via these [annotations](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#server-ca)
