### ISSUE TITLE
Add Ingress v2 Support

### ISSUE THREAD

**Issue by danehans** [haproxytech/kubernetes-ingress#137]
Ingress v2 [API's](https://docs.google.com/document/d/1BxYbDovMwnEqe8lj8JwHo8YxHAt3oC7ezhlFsG_tyag/edit?usp=sharing) and [use cases](https://docs.google.com/document/d/1OAzVO0HfmF4qD8AW41_eeUY0KP6xjqghusUVwhp4BNg/edit?usp=sharing) are being actively developed. An upstream [issue](https://github.com/kubernetes-sigs/service-apis/issues/4) has been filed to create an implementation of the API's. Should the API's be implemented in kubernetes-ingress or a new haproxytech project? Either way, add support for ingress v2 as the API's start to stabilize.

/cc @bedis

**Comment by Mo3m3n** [comment]
Hi @danehans 
Sorry for the delay getting back to this, needed sometime to go through the spec/sketch of the new API.
We think that there is no need to implement it in a new haproxytech project.
Kubernetes-ingress has already the building blocks to handle/generate the HAProxy configuration and we are currently doing some code refactoring to make further changes (like supporting v2) easier to integrate.

**Comment by danehans** [comment]
@Mo3m3n that's great to hear. Thanks for the update.

**Comment by Mo3m3n** [comment]
We will publish progress regarding this request in https://github.com/haproxytech/kubernetes-ingress/issues/386
