### ISSUE TITLE
Multiple whitelisted namspaces ignored

### ISSUE THREAD

**Issue by adrianleh** [haproxytech/kubernetes-ingress#138]
Hi all,

currently I have a set up with 2 namespaces in use: default & prometheus. As per the documentation ([https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md)) I configured my deployment's container with the following arguments:
```      containers:
      - name: haproxy-ingress
        image: haproxytech/kubernetes-ingress
        args:
          - --configmap=default/haproxy-configmap
          - --default-backend-service=haproxy-controller/ingress-default-backend
          - --namespace-whitelist=default
          - --namespace-whitelist=prometheus
```

Unfortunately though the logs show that only containers from the namespace default are found.

**Comment by Mo3m3n** [comment]
Hi,
Sorry this question has gone out of sight.
As of current stable (1.5) multiple whitelisted namespaces should work correctly and you can see the following log line:
```
2021/03/09 14:47:50 INFO    monitor.go:71 Whitelisted Namespaces: [default prometheus]
```
