### ISSUE TITLE
Listen on custom ports

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#139]
Hi,

Is it possible to make the Ingress controller to listen on different ports than the standard/default ones?
This is valid for http, https and stats?
Whatever solution that could then be used by the helm chart's controller.containerPort.* parameters would be good.

Use case is simple: run multiple ingress controllers as HostNetwork (daemonset) and having each of them listen on a custom port.

**Comment by bedis** [comment]
other use case: make a non-root pod listen on non secured ports (> 1024)

**Comment by prometherion** [comment]
Great news, thanks to db51a5dbb6a66ee4959730a96187b3fb141b5906 (and planned for the next upcoming release, `1.5.0`) the Ingress Controller is able to listen to custom ports.

> make a non-root pod listen on non secured ports

Maybe better open a new issue/feature request for this.

**Comment by Mo3m3n** [comment]
This is now available with 1.5
