### ISSUE TITLE
HTTP to HTTPs redirection rule ignores ':port' in the Host header

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#140]
Current HTTP to HTTPs redirection creates the following rules in the HTTP frontend:
`http-request redirect scheme https code 302 if !{ ssl_fc }`

The problem is that when I send this type of request:
>  GET http://domain.com:80/

I am redirected to this URL:

>   HTTP/1.1 302 Found
 content-length: 0
 location: https://www.domain.com:80/

which obviously will not work.
Something like this would do the trick:
`http-request redirect location https://%[hdr(host),field(1,:)]%[capture.req.uri]  code 302`

This may be related later to #139 if https is configured on a different port... the rule above would have to be adjusted cause for now, it redirects to 443.

**Comment by Mo3m3n** [comment]
This should be possible now with [ssl-redirect-port](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#https)
