### ISSUE TITLE
Support for HTTP/2 on the server side

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#142]
Hi there,

Could you please add an annotation to support HTTP/2 on the server side? 
Purpose is to support gRPC.
might have an impact on #135

**Comment by andreasdrougge** [comment]
What do we need to set on the backend/server config?
option http-use-htx
and
"ssl verify none alpn h2"
should it support Proto without pls too?
"proto h2"

**Comment by andreasdrougge** [comment]
I can't find alpn or h2 in models. https://github.com/haproxytech/models/blob/master/server.go
This has to be updated to support this right?

**Comment by bedis** [comment]
it should adapt to #135 (and #143 )
Basically, if `server-ssl` is enabled, then `alpn h2` should apply
if `server-ssl` is not enabled, then `proto h2` on the server line.
Note that `option http-use-htx` should be enabled in the defaults section to be compatible with HAProxy 1.9. (this option will be ignored with HAProxy 2.0)

**Comment by NickMRamirez** [comment]
The `Alpn` parameter is available on the [Bind](https://github.com/haproxytech/models/blob/master/bind.go) struct.

**Comment by bedis** [comment]
The Bind struct is on the frontend side, while the server is on the backend one ;)

**Comment by JohnGalt1717** [comment]
I'm having trouble setting this. I have a .net core grpc backend that doesn't do SSL, but relies on the proxy information to tell it that it's SSL anyhow.

The backend is being sent http/1.1 not http/2

How does one get it to pass has http/2? (or maintain whatever the client request was in preferably?)

**Comment by gitNas** [comment]
Hello,

I have the same problem.
Any response please ?

**Comment by Mo3m3n** [comment]
> I have the same problem.
> Any response please ?

Answer is here: https://github.com/haproxytech/kubernetes-ingress/issues/249
