### ISSUE TITLE
@Benjamin-Beeman your issue is not related to this, if you read the logs in there you have:

### ISSUE THREAD

**Issue by Benjamin-Beeman** [haproxytech/kubernetes-ingress#151]
@Benjamin-Beeman your issue is not related to this, if you read the logs in there you have:
```
cannot create listening socket [:::443]
cannot create listening socket [:::80]
```

_Originally posted by @oktalz in https://github.com/haproxytech/kubernetes-ingress/issues/113#issuecomment-581274168_

**Comment by Mo3m3n** [comment]
This can have different reasons depending on how you are deploying the controller.
How are you deploying the controller? (Helm, kubectl apply, etc)

**Comment by mshahat** [comment]
i have a similar issue, and i've deployed using helm chart `kubernetes-ingress-0.7.3` ... thanks
