### ISSUE TITLE
mTLS on the client side

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#158]
Would it be possible to load a ca-file on the frontend's bind in order to perform mTLS with the client?
We could set "verify optional" for now and improve this later while working on #36

**Comment by Mo3m3n** [comment]
You will need an annotation to provide the name of the secret holding the ca-file correct ?

**Comment by bedis** [comment]
I guess so, yes.

**Comment by lseelenbinder** [comment]
I came here looking for this feature. We use mTLS extensively, so having this for outward facing Ingress resources would make life simpler.

**Comment by narg95** [comment]
hi,

same here, are there any news on that, or is there a workaround e.g. with a `config-snippet`?

**Comment by Mo3m3n** [comment]
Released in v1.6 via [client-ca](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#authentication) annotation
