### ISSUE TITLE
[check] allow method, url and Host header to check on

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#16]
Current HTTP check method is very simple and we may want to enforce some specific parameters such as:
- method
- URL path
- Host header

**Comment by Mo3m3n** [comment]
Available in [v1.2.3](https://github.com/haproxytech/kubernetes-ingress/releases/tag/v1.2.3) release.

**Comment by bedis** [comment]
Thanks @Mo3m3n
