### ISSUE TITLE
Backend selection does not respect the IngressRule spec

### ISSUE THREAD

**Issue by efthymiosh** [haproxytech/kubernetes-ingress#161]
The Kubernetes [IngressRule](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#ingressrule-v1beta1-networking-k8s-io) defines `host` as:
```Host is the fully qualified domain name of a network host, as defined by RFC 3986```

[RFC 2616 for HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) defines the Host Header as:
```Host = "Host" ":" host [ ":" port ]```

The RFC does *not* explicitly state that clients should not set port when the port is 80 for HTTP or 443 for HTTPS. Thus, some clients may (and do) set the Host header for http as such: `Host: some.domain.com:80`.

The controller currently generates the condition with `condTest = fmt.Sprintf("{ req.hdr(host) -i %s } ", rule.Host)` (controller-backend-switching.go:90 in v.1.3.2, controller/backend-switching.go:91 in master)

From reading the ACL docs I figure that since the host header is a string, the default matcher is `str` which performs an exact-match comparison. As such, the configuration emitter is wrong: `rule.Host` by definition contains the fqdn and potentially not the entirety of the Host Header, if the request has the port set.

**Comment by Mo3m3n** [comment]
Hi @efthymiosh 
Thanks for reporting this this was fixed in `v1.4.3` 
Precisely in commit https://github.com/haproxytech/kubernetes-ingress/commit/aac95d5fef1377b26df9cde6d49efeb0b5a13001
