### ISSUE TITLE
TCP health checks set to "no check" after blue-green deployment

### ISSUE THREAD

**Issue by NickMRamirez** [haproxytech/kubernetes-ingress#163]
Controller Version: 1.3.3

## Set up:

Test a blue-green deployment as described here in [this blog post](https://www.haproxy.com/blog/rolling-updates-and-blue-green-deployments-with-kubernetes-and-haproxy/#blue-green-deployments).

When you create two Deployments that have different label selectors, and use a Service to target one or the other (blue vs green), and create an Ingress to watch that service, the Ingress Controller will route traffic to whichever Deployment the Service's selector matches.

When you enable TCP health checks on the Ingress Controller (either on the Ingress object or in the ConfigMap), it adds "check" parameters to the backend servers in HAProxy. 

When you watch the HAProxy Stats page, it displays a green health status for backend servers (the "blue" servers). 

## Description of Problem
After switching the label selector on the Service to the "green" Deployment label selector, the servers displayed on the Stats page are changed as expected. They are also routed to correctly, but they report a grey "no check" for their health status. This is even though, upon inspection, the HAProxy configuration file has added a "check" parameter to the servers.

Note: A regular rolling update is not affected and works as expected with health checks.

## Expected Behavior

After dynamically changing the backend servers using a blue-green deployment, the Stats page should show a green health status for the new servers instead of "no check" when "check" has been set in either the ConfigMap or Ingress.

**Comment by scalp42** [comment]
@NickMRamirez did you ever figure it out?

**Comment by NickMRamirez** [comment]
I don't think I ever figured it out. But I forgot about it too. :-)
