### ISSUE TITLE
Empty ingress.class is never ignored

### ISSUE THREAD

**Issue by ohardy** [haproxytech/kubernetes-ingress#165]
Hi,

It looks like the issue #31 is back for me.

I have two ingress controllers, one for internal domains, one for public domains.

So I configure public one with ingress.class = 'public' for example.

If I add ingress without ingress.class, this ingress controller will not ignore it !

Is it wanted ? Because for me it must not happen.

Thanks in advance

**Comment by Mo3m3n** [comment]
Thanks @ohardy  for another bug report.
It was fixed in related PR and available at `k8s.local/kubernetes-ingress:dev` while we prepare next release

**Comment by ohardy** [comment]
It's fixed in the dev image, thanks !

**Comment by Mo3m3n** [comment]
Released in `haproxytech/kubernetes-ingress:1.4.0`
