### ISSUE TITLE
Pull Request: Add weights via pod object annotations

### ISSUE THREAD

**Issue by dspitzer** [haproxytech/kubernetes-ingress#170]
This is regarding pull request #169 
I tried starting a discussion in the Haproxy mailing list and Moemen directed me to open an issue here.

This commit adds support for weights for backend endpoints via pod annotations. By adding a haproxy.org/weight annotation to a pod you can specify an explicit weight whenever that pod is being used in an endpoint as long as the TargetRef was added properly (usually automatically via services). Additionally, the default weight can be specified via the new --default-weight parameter. 

Moemen asked me the following questions which I'll gladly answer:

> We'd be interested to know more about the use case.
> 
> In a standard use case, pods are ephemeral and they are not expected to carry specific information. Thus they can be easily replaceable, scalable, etc
> 
> So typical questions:
> - What kind of pods are these? static pods or created via Service ?
> - How they are configured (annotation part in this case)?
> 
> So don't hesitate to give us more context about this in the github issue.

The reason for this patch is to be able to do some basic form of traffic shaping by sending more or less traffic to specific pods. There are two use-cases that I can come up with which were the main reason for creating this pull-request:

- Performance testing in a canary release or a/b testing scenario where you want to compare possible performance hits or improvements
- Pods running on different hardware nodes or virtual machine instances that can handle more or less traffic than others. Simply choosing a different lb algorithm is sometimes not enough as the backend might have internal timeouts that will force it to stop doing work and return in which case the response times / amount of requests can be similar in lower-specced systems but with detrimental effects elsewhere. This is particularly true f.e. in the programmatic ad-tech space.

The annotation that can be added to daemonsets/deployments or individual pods is haproxy.org/weight

>- Caching  pods objects, tracking them and syncing the corresponding configuration is an important amount of work which for now seems to be only useful for an edge case. That's why we would probably prefer having CLI arg to activate this.

I added this pull request without the cli parameter but will happily introduce it if requested here as well.

>- No need for reload since we can set server weight via the Runtime API (for example we do this already to change a server address via c.NativeAPI.Runtime.SetServerAddr)

**Unfortunately with the current code the weight is not applied without a reload. Can someone help here?** 

>My coworkers will probable have other thoughts to add once the github issue is created.

Please share them!

**Comment by oktalz** [comment]
Hi @dspitzer 
thank you for this, at first glance it looks really good, 
but allow us few days to closely examine this.

can you also add in `documentation/controller.md` documentation about `DefaultWeight` ?

Also currently I'm not sure where we need to add few words about weight also, since i don't prefer
to add another column (as we have with Config map, Ingress, Service)

One thing we definitely prefer is using Runtime API where we can, 
but we can help you with this in next couple of days

**Comment by dspitzer** [comment]
Hi @oktalz  
Thanks for your fast response - I added documentation in both `documentation/controller.md` as well as `documentation/README.md`. 

I'd love some help on the Runtime API - I thought that it'd work the way I implemented it but as I stated above, the changes aren't currently applied without a reload.

**Comment by Mo3m3n** [comment]
Hi,
Thanks for opening this discussion and providing more details.
>Performance testing in a canary release or a/b testing scenario where you want to compare possible performance hits or improvements

This was also asked before here https://github.com/haproxytech/kubernetes-ingress/issues/92 and my understanding that this can be done at the ingress level (as explained in the article shared in said github issue) which means:
- Using two ingress serving the same host 
- One of them will have the canary annotation with the appropriate weight.
Which in HAProxy configuration translates to having two different backends, one for each app (for example: stable, beta). Then use in haproxy something like this (supposing that the weight of the beta app is 20%):

      http-request set-var(req.random) rand(100)
      use_backend be_prod if { var(req.random) ge 20 }
      use_backend be_stable if { var(req.random) le 20 }
 
This solution have two advantages:
- *More flexibility*: using the canary/weight annotation at the ingress level will be useful for the user who wants to apply this at multiple applications (The ingress will then have rules for the aps in questions) and also to the user like you who is targeting single pods if am understanding correctly 
- *Easier to implement*: No need to track a whole set of k8s objects.
>Pods running on different hardware nodes or virtual machine instances that can handle more or less traffic than others. Simply choosing a different lb algorithm is sometimes not enough as the backend might have internal timeouts that will force it to stop doing work and return in which case the response times / amount of requests can be similar in lower-specced systems but with detrimental effects elsewhere. This is particularly true f.e. in the programmatic ad-tech space.

Same here, you can have a different set of deployments/daemonsets (with their corresponding services) that will each run on different type of hardware. Then in the ingress object configuring rules for services running in a specific type of hardware, you can specify the appropriate weight annotation.

Let me know what you think about this, if my thoughts were clear or not and especially if I have correctly understood your requirements.

**Comment by dspitzer** [comment]
Hi @Mo3m3n ,

I think the nginx way of doing this is interesting but comes with a few problems:

- It doesn't balance relative to other pods but relative to all traffic for an ingress rule. That means that in setups with a lot of traffic you'll have to do auto-scaling for canary releases which is additional work and makes it harder to compare (think: starting value, choosing pods to compare between).
- Even the nginx implementation does this only for a [single canary](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary) per ingress rule. It's not exactly easy to implement, having to merge ingress objects.

>>Pods running on different hardware nodes or virtual machine instances that can handle more or less traffic than others. Simply choosing a different lb algorithm is sometimes not enough as the backend might have internal timeouts that will force it to stop doing work and return in which case the response times / amount of requests can be similar in lower-specced systems but with detrimental effects elsewhere. This is particularly true f.e. in the programmatic ad-tech space.
>
>Same here, you can have a different set of deployments/daemonsets (with their corresponding services) that will each run on different type of hardware. Then in the ingress object configuring rules for services running in a specific type of hardware, you can specify the appropriate weight annotation.

Here the problem with scaling due to the weight being on a per-backend rather than per-server basis becomes even worse - I'd need to think and plan on a machine level now instead of seeing the cluster as "one" - the k8s pod scheduler can place pods on any node by default, potentially reducing the capacity I have on one "node type", meaning I'd  need to reserve capacity for my workload on specific node types. It'd also lead to either under- or over-utilization.

For our use-case this method wouldn't work well enough. 

Please let me know what you think of these points.

**Comment by Mo3m3n** [comment]
>I think the nginx way of doing this is interesting but comes with a few problems:

Correct if am wrong but this does not seem to be only the nginx way, the other ingress controllers that I had the time to look into were also putting the weight/canary annotation at the service/ingress level rather than at the pod level.
We don't have to follow existing paths but imo there should be a good reason to think this differently. 

> It doesn't balance relative to other pods but relative to all traffic for an ingress rule. That means that in setups with a lot of traffic you'll have to do auto-scaling for canary releases which is additional work and makes it harder to compare (think: starting value, choosing pods to compare between).

If you are putting annotation at the pod level and you have a lot of traffic is this going to be different that you don't have to autoscale? if yes curious to understand how

>Even the nginx implementation does this only for a single canary per ingress rule. It's not exactly easy to implement, having to merge ingress objects.

Maybe I should have started with this question to compare with ingress (or service) based annotation :) : 
when putting weights on pods how exactly you are going to put the annotation and update it (tools, commands, instructions). ?

**Comment by dspitzer** [comment]
> > I think the nginx way of doing this is interesting but comes with a few problems:
> 
> Correct if am wrong but this does not seem to be only the nginx way, the other ingress controllers that I had the time to look into were also putting the weight/canary annotation at the service/ingress level rather than at the pod level.
> We don't have to follow existing paths but imo there should be a good reason to think this differently.

I think both approaches are valid. There are instances where you want to direct a certain percentage of the total traffic towards a canary release. There are also instances (especially performance comparisons) where you want to direct a percentage relative to what production receives towards a canary release.

> If you are putting annotation at the pod level and you have a lot of traffic is this going to be different that you don't have to autoscale? if yes curious to understand how

Only the main deployment / production needs to be on auto-scaling or has enough pods to handle all traffic. The canary release can have a fixed number of pods in this scenario. If more traffic comes in, production will/should scale up.

> Maybe I should have started with this question to compare with ingress (or service) based annotation :) :
> when putting weights on pods how exactly you are going to put the annotation and update it (tools, commands, instructions). ?

It's sufficient to create a deployment (or daemonset, etc.) and put the annotation in the template metadata like so:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:                       
  labels:        
    run: demo-release
  name: demo-release
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      annotations:
        haproxy.org/weight: "200"
      labels:
        run: demo
    spec:
      containers:
      - image: strm/helloworld-http
        name: demo
        ports:
        - containerPort: 80
          protocol: TCP
```

This can easily be done automatically by any CI/CD pipeline that integrates with k8s. The ingress doesn't need to be modified at all - the service it targets just needs to have the right selectors which could be the same as in production or modified by the pipeline, that's mostly a matter of taste. 

I'd even volunteer to implement the Nginx approach as well as it makes a lot of sense for other scenarios. But then I think it'd be better if you created the specs for it or direct me to some form of documentation on how you'd want it implemented.

**Comment by bedis** [comment]
Please keep in mind the threshold for canary may be stored in a map and dynamically changed without reloading HAProxy at all

**Comment by Mo3m3n** [comment]
Thanks David,
Your last answer has cleared the requirements and how you intend it to work.
If am understanding correctly, you're going to have for example two deployments:
- stable-release: weight 80
- demog-release: weight 20
And both deployment will be exposed by the same service, so in the end all the pods will be in the same backend. Correct ?
If my understanding is correct I will proceed to code review.

**Comment by dspitzer** [comment]
@Mo3m3n correct, this is exactly how we intend to use it.

**Comment by dspitzer** [comment]
I'd need some help regarding applying the weight without a reload. I thought that with the existing code it should work but unfortunately it doesn't get applied unless I do the reload.

**Comment by Mo3m3n** [comment]
In your PR you are making the weight change in `handleEndpointIP` which is correct but this function is called every syncEveryNSeconds to sync the haproxy.cfg file (and make a reload if the file changes).

So updating the haproxy.cfg is required anyway but what if you want the weight to be changed dynamically without waiting for syncEveryNSeconds (that is as soon as the controller is notified by k8s that the weight has changed). In this case you will need to do the same as we do when we want to dynamically update a server address via HAProxy runtime socket as you can see it here: https://github.com/haproxytech/kubernetes-ingress/blob/3c4dc3db3e9e71a4d94af5589f271380b7e816af/controller/events.go#L370 

Don't hesitate to reach us on [slack](https://github.com/haproxytech/kubernetes-ingress/blob/master/README.md#discussion) for a longer discussion.

**Comment by dspitzer** [comment]
Oh - now I get it - thanks a lot @Mo3m3n, I'll add it to the pull request.

**Comment by bedis** [comment]
Forgot my comment about dynamic changes in a map, I was at the "service" level weighting. In this case, at the server level, changes should be straight forward :)

**Comment by Mo3m3n** [comment]
Closing this since corresponding [PR](https://github.com/haproxytech/kubernetes-ingress/pull/169) was not finished.
Otherwise, anyone looking for canary deployment can follow this [guide](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/canary-deployment.md)
