### ISSUE TITLE
Increase replicas for controller Deployment from 1 to 2

### ISSUE THREAD

**Issue by NickMRamirez** [haproxytech/kubernetes-ingress#175]
The default value for `replicas` in the controller's [Deployment manifest](https://github.com/haproxytech/kubernetes-ingress/blob/master/deploy/haproxy-ingress.yaml) is 1. Changing this to 2 will add redundancy and match the default behavior of the Helm chart.

**Comment by oktalz** [comment]
but it complicates design.
this is example yaml script for beginners and therefore I prefer it to stay as minimal as it can, but to have everything you need to start the controller.
