### ISSUE TITLE
setting up full passthrough (with proxy-protocol) to an internal haproxy pod ?

### ISSUE THREAD

**Issue by sandys** [haproxytech/kubernetes-ingress#176]
hi guys,
we are slowly migrating to haproxy ingress from a cloud setup with a haproxy reverse proxy (with plain vanilla haproxy.cfg)

To make this convenient for us - we would like haproxy ingress controller to pass everything through to a haproxy deployment and let it do the reverse proxying. and over a period of time, we will migrate everything to ingress style.

how does one do this - with the caveat that source ip be preserved in proxy-protocol form (so the internal pods, etc can work on it)

**Comment by Mo3m3n** [comment]
Hi,
If you are not going to use Ingress resources you will not need an ingress controller.
In this case better for a HAProxy in a docker container: https://hub.docker.com/r/haproxytech/haproxy-alpine
