### ISSUE TITLE
Merging multiple ingresses with the same host name?

### ISSUE THREAD

**Issue by zvickery** [haproxytech/kubernetes-ingress#177]
Hi, I'm curious if there is a way to control the ordering of "merged" ingresses using the same name?  For example, I have two ingresses like below:
```
  Host                              Path  Backends
  ----                              ----  --------
  myhost.domain.com
                                    /api/1/route1   backend:80 (10.10.10.211:8080)
                                    /api/2/route1   backend:80 (10.10.10.211:8080)
                                    /api/1/route2   backend:80 (10.10.10.211:8080)
                                    /api/2/route2   backedd:80 (10.10.10.211:8080)
```
and
```
  Host                              Path  Backends
  ----                              ----  --------
  myhost.domain.com
                                    /   default:80 (10.10.10.186:3000)
```
The basic idea is that I have a "default" backend which receives most traffic.  However I would like to inject other ingresses to override handling of certain paths.

The problem is that the haproxy configuration gets written with the default path first and this doesn't work.  I also haven't been able to figure out a way to influence the ordering of the merging in the generated haproxy.cfg file.  Is this sort of thing possible with the haproxy ingress controller?  I believe the nginx-ingress-controller supports this idea and I have definitely used it with marathon-lb in the context of mesos and marathon.

Thank you!

**Comment by Mo3m3n** [comment]
Hi,
>The basic idea is that I have a "default" backend which receives most traffic. However I would like to inject other ingresses to override handling of certain paths.
Why not use a real default backend (no host) which will handle any request that is not matched against all ingress rules ?

**Comment by zvickery** [comment]
Currently my ingresses have some annotations in order to work correctly.  Is it possible to accomplish things like ssl-redirect and request-set-header with the default backend?

**Comment by Mo3m3n** [comment]
> Is it possible to accomplish things like ssl-redirect and request-set-header with the default backend?

No it is not possible and yes if you're using annotations, then having an ingress rule used as default-backend for a given host makes sense.

However I am not quite understanding the need of ordering ingresses. Currently if you have following rules:
  myhost.domain.com /api/1/route1 
  myhost.domain.com /api/2/route1 
   myhost.domain.com /api/3/route1 
  myhost.domain.com /

any request for myhost.domain.com that does not match the api paths will go to the last rule.
Is this what you are looking for ?

**Comment by zvickery** [comment]
The problem is that in the generated haproxy.cfg, the rules look something like this:
```
   use_backend default if { req.hdr(host) -i myhost.domain.com } { path_beg / }
...
  use_backend backend-80 if { req.hdr(host) -i myhost.domain.com } { path_beg /api/1/route1 }
  use_backend backend-80 if { req.hdr(host) -i myhost.domain.com } { path_beg /api/2/route1 }
  use_backend backend-80 if { req.hdr(host) -i myhost.domain.com } { path_beg /api/1/route2 }
  use_backend backend-80 if { req.hdr(host) -i myhost.domain.com } { path_beg /api/2/route2 }
```
I know there is some length sorting in the ingress controller but it doesn't seem to account for multiple ingresses.  Is there a way to influence the ordering of rules in the generated configuration?

**Comment by Mo3m3n** [comment]
>  I know there is some length sorting in the ingress controller but it doesn't seem to account for multiple ingresses.

Exactly, it does not account for multiple ingresses.
It will only work if you have an ingress rule like:
```
 - host: myhost.domain.com
    http:
      paths:
      - backend:
          serviceName: default
          servicePort: 80
        path: /
      - backend:
          serviceName: app1
          servicePort: 80
        path: /api/1/route1
      - backend:
          serviceName: app2
          servicePort: 80
        path: /api/2/route1
      - backend:
          serviceName: app3
          servicePort: 80
        path: /api/3/route1
```
In this case the shortest path "/" will be the last one and make it work as a default backend.
But I think this does not help you as it seems that you are using different ingresses.
If that's the case I can patch the code to do the length sorting no only on paths of the same ingress rule but on paths of all ingress rules with the same Host.

**Comment by zvickery** [comment]
If that's doable, that would be great.  Thank you for your support!

**Comment by zvickery** [comment]
I did find that the ingress backend rules are sorted in reverse lexicographic order based upon their key.  Ingress name being the first part of the key and the most likely thing to influence ordering.

If I change https://github.com/haproxytech/kubernetes-ingress/blob/e1c8890d1e4a5df8bbd4760b34f824d9a648eb4f/controller/backend-switching.go#L115 to `-1` it sorts in forward order, which is more intuitive IMO.  This ordering allows me to accomplish what I need but is not very intuitive.

If forward ordering is desired I can make a PR with the above change.

**Comment by Mo3m3n** [comment]
Hey @zvickery 
I have already patched the code last week, but I was waiting for the next release (probably this week) to announce it here.
The commit in question is https://github.com/haproxytech/kubernetes-ingress/commit/5f9ecfe4aceec1d17fce08fbd8702f67b96f767f
If you want to try an image based on the current master and check the patch you can use `haproxytech/kubernetes-ingress:dev`

**Comment by zvickery** [comment]
I see the commit on master and it works great.  Thank you!
