### ISSUE TITLE
Concerning messages in logs

### ISSUE THREAD

**Issue by jhohertz** [haproxytech/kubernetes-ingress#18]
Was evaluating this and among other issues I saw this in the logs:

```
2019/06/27 15:02:34 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-42hcm
2019/06/27 15:02:34 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-cxx46
2019/06/27 15:02:34 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-sz2w9
2019/06/27 15:02:34 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-clusterchecks-6b99b5f5bd-zw2gv
2019/06/27 15:02:36 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-wqk4x
2019/06/27 15:02:37 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-clusterchecks-6b99b5f5bd-2m5sj
2019/06/27 15:02:38 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-c7j5j
2019/06/27 15:02:40 controller-events.go:229: Pod not registered with controller, cannot modify ! prometheus-prometheus-operator-prometheus-master-0
2019/06/27 15:02:41 controller-events.go:229: Pod not registered with controller, cannot modify ! datadog-lpf2k
```

Why, would the ingress be doing anything at all with these pods, unrelated to any ingress record or deployment, and why would it be trying to modify them in any way?

**Comment by oktalz** [comment]
Hi, 
I must change the message to better reflect what is not modified.

Controller does not modify anything outside his own data structures.
Certainly it does not modify any data regarding pods, services ...

This information is presented when controller receives data from k8s API,
to be exact `modified` status from API, but does not have info about that pods.
(first you have `added` status, later comes `modify` and registration of pods comes when API 
sends `added` status for pod.
So it just informing that k8s API has send some data about pods that controller does not know anything about.

**Comment by jhohertz** [comment]
Sounds like debug-level logging then. Thank you for clarifying.

**Comment by oktalz** [comment]
I've changed how that info is presented 
(and removed some confusing log messages)
