### ISSUE TITLE
No traffic being forwarded after pod deletes and new pods being created

### ISSUE THREAD

**Issue by rparth** [haproxytech/kubernetes-ingress#181]
API requests fail with

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

deleting the haproxy pods resolves the issue

Additional logs from the ingress pod below

2020/04/26 18:04:23 Modified: logiq-logiq-flash-9999 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-9999 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-2514 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-514 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-7514 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-8081 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-9998 - SRV_ppr1o - maint
2020/04/26 18:04:23 Modified: logiq-logiq-flash-20514 - SRV_ppr1o - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-9999 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-9999 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-9998 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-20514 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-2514 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-514 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-7514 - SRV_VYED4 - maint
2020/04/26 18:04:32 Modified: logiq-logiq-flash-8081 - SRV_VYED4 - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-9999 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-9999 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-8081 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-9998 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-20514 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-2514 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-514 - SRV_a0kdq - maint
2020/04/26 18:04:47 Modified: logiq-logiq-flash-7514 - SRV_a0kdq - maint
2020/04/26 18:08:13 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:13 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:18 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:23 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:28 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:33 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:38 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'api' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'webcli' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'relp' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'relptls' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'syslog' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'syslogtls' for service logiq-flash
2020/04/26 18:08:43 Could not find Targetport of 'grpc' for service logiq-flash
2020/04/26 18:10:10 Modified: logiq-logiq-flash-9999 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-9999 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-20514 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-2514 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-514 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-7514 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-8081 - SRV_ULPbh - ready
2020/04/26 18:10:10 Modified: logiq-logiq-flash-9998 - SRV_ULPbh - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-9999 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-9999 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-8081 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-9998 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-20514 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-2514 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-514 - SRV_a0kdq - ready
2020/04/26 18:11:30 Modified: logiq-logiq-flash-7514 - SRV_a0kdq - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-9999 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-9999 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-9998 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-20514 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-2514 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-514 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-7514 - SRV_giwmL - ready
2020/04/26 18:12:36 Modified: logiq-logiq-flash-8081 - SRV_giwmL - ready

**Comment by nvass** [comment]
We, too, see the same problem. It seems that haproxy's configuration wasn't updated by the controller and the backends' IPs are old:
```
root@kubernetes-0:~# kubectl get -n gitlab pod -o wide |grep webservice
gitlab-webservice-7d99d7f89c-j2zsr                           2/2     Running     0          47m     10.244.5.116   kubernetes-4   <none>           <none>
gitlab-webservice-7d99d7f89c-m5774                           2/2     Running     0          78m     10.244.6.207   kubernetes-3   <none>           <none>
gitlab-webservice-7d99d7f89c-q5p57                           0/2     Evicted     0          78m     <none>         kubernetes-4   <none>           <none>
root@kubernetes-0:~# kubectl exec -n gitlab ingress-kubernetes-ingress-r2s89    -- fgrep 10.244.6.207 /etc/haproxy/haproxy.cfg
  server SRV_ccID0 10.244.6.207:8080 check weight 128
  server SRV_ccID0 10.244.6.207:8181 check weight 128
root@kubernetes-0:~# kubectl exec -n gitlab ingress-kubernetes-ingress-ws2wd    -- fgrep 10.244.6.207 /etc/haproxy/haproxy.cfg
  server SRV_IzoOj 10.244.6.207:8080 check weight 128
  server SRV_IzoOj 10.244.6.207:8181 check weight 128
root@kubernetes-0:~# kubectl exec -n gitlab ingress-kubernetes-ingress-r2s89    -- fgrep 10.244.5.116 /etc/haproxy/haproxy.cfg
command terminated with exit code 1
root@kubernetes-0:~# kubectl exec -n gitlab ingress-kubernetes-ingress-ws2wd    -- fgrep 10.244.5.116 /etc/haproxy/haproxy.cfg
command terminated with exit code 1
root@kubernetes-0:~#
```

**Comment by prometherion** [comment]
Are you customizing the `sync-period` CLI flag or is it defaulted to the default value (`5s`)? It can be easily figured out from the Pod log.

How the new Pods are rolled out? (`helm`, `kubectl apply`, `kustomize`)

Please, provide further details as running Ingress Controller and Kubernetes versions, as any additional detail to give us more context.

**Comment by nvass** [comment]
Hi Dario,

Sync-period is the default one. We use helm with these values:
```
controller:
  kind: DaemonSet
  config: {"ssl-redirect":"false","servers-increment":"8"}
  daemonset:
    useHostPort: true
  defaultTLSSecret:
    secret: "domainname-wildcard"
    enabled: true
  logging:
    level: debug
  ingressClass: ingress
defaultBackend:
  replicaCount: 1
```
Chart version is kubernetes-ingress-1.6.2  and K8S is 1.18.2

Thanks!

**Comment by prometherion** [comment]
Can you check if the Endpoint list has been updated properly?

Just need to issue `kubectl -n my-namespace get endpoints <service-name>`.

JFI, the Backend Servers list should be equals to the Kubernetes Endpoints one per service.

**Comment by nvass** [comment]
kubectl -n gitlab get endpoints gitlab-webservice
NAME                ENDPOINTS                                                           AGE
gitlab-webservice   10.244.5.116:8080,10.244.6.207:8080,10.244.5.116:8181 + 1 more...   132d
root@kubernetes-0:~#

And backend configuration looks like this:
```
backend gitlab-gitlab-webservice-8080
  mode http
  balance roundrobin
  option forwardfor
  server SRV_Qt7Ka 127.0.0.1:8080 disabled check weight 128
  server SRV_ccID0 10.244.6.207:8080 check weight 128
  server SRV_YX3Wj 10.244.6.208:8080 check weight 128
  server SRV_ij0no 127.0.0.1:8080 disabled check weight 128
  server SRV_Vd02d 127.0.0.1:8080 disabled check weight 128
  server SRV_zrIkv 127.0.0.1:8080 disabled check weight 128
  server SRV_fE7oy 127.0.0.1:8080 disabled check weight 128
  server SRV_NuWFz 127.0.0.1:8080 disabled check weight 128
```

**Comment by prometherion** [comment]
@nvass please, can you set the log level to `debug` and scale manually pods?

I'm expecting to see on controller logs something as `2020/10/27 13:40:15 DEBUG   events.go:375 server 'default-podinfo-http/SRV_3ZyBS' changed status to ready` and no need to reload since it's required only on Ingress publishing or other kind of actions.

**Comment by Mo3m3n** [comment]
Closing this one as it has gone stale
