### ISSUE TITLE
Support for proxy-protocol

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#19]
I have use cases where I use HAProxy as an external load-balancer.
In this use case, the external load-balancer used proxy-protocol and tcp mode only to get connected to the ingress controllers.

This is dependent on the following issue in the client native, I guess:
https://github.com/haproxytech/client-native/issues/4

**Comment by bedis** [comment]
Thanks to @oktalz we have a working patch in the branch bind-accept-proxy. That said, I thought a bit more about this feature and I think I want to improve it this way:
* add an option to provide a list of source IP supposed to send the proxy protocol

The reason is simple: we may have a layer of External Load-balancer which can set the proxy protocol (ELB, HAProxy) and have in the mean time internal clients reaching directly the ingress controller without sending the proxy protocol.
If there is no source IP given with the configuration, then the rule will apply to entire traffic. If there is a list, then we'll enforce proxy protocol to this source IPs only

**Comment by bedis** [comment]
This would be useful as well to put the controller behind ELB

**Comment by the-nicolas** [comment]
Any update here? We have a hardware lb in front of ingress which adds client ip via proxy protocol to tcp connections and we need that information on our application...

**Comment by bedis** [comment]
Well, I did a first implementation "which works" but I was not satisfied by it (it was just a "enable/disable" kind of thing.).
I want something more granular where we can enforce Proxy-Protocol for some source IPs only (or all traffic of course).
but this require support for new tcp-request rules in the client-native library that will be available with v2 of it (in a couple of weeks).
In short, I'll restart working on this one in a couple of weeks.

**Comment by Mo3m3n** [comment]
Support for proxy-protocol has been added here https://github.com/haproxytech/kubernetes-ingress/commit/8c898cb3959d1d170e902dcb932057e4e686d85e
