### ISSUE TITLE
handle ssl-engine and ssl-mode-async

### ISSUE THREAD

**Issue by mythi** [haproxytech/kubernetes-ingress#192]
In order to configure kubernetes-ingress to use OpenSSL Engines and preferably use their async features, I'd need to be able to set `ssl-engine` and `ssl-mode-async` global options.

**Comment by Mo3m3n** [comment]
Hi @mythi 
Thanks for submitting this feature request. These global options and other ones (like tunebufsize, etc) are planned to be added next week. I will let you know once it is on master.

**Comment by mythi** [comment]
@Mo3m3n excellent, thanks!

**Comment by Mo3m3n** [comment]
We have added [config-snippet](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/README.md#config-snippet) annotation that you can use to add the configuration you want.
In this case you will need to  add an annotation to your configmap that looks like:
```
config-snippet: |
  ssl-engine rdrand
  ssl-mode-async
```
This is currently on master and available via the  `haproxytech/kubernetes-ingress:dev` tag, until next release

**Comment by mythi** [comment]
great, I'll give it a try later!

**Comment by punkprzemo** [comment]
Hi @Mo3m3n . Seems like `config-snippet` is still only in master branch (dev image) . Do you plan to merge that one into stable release?
The [doc](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#config-snippet) says ` "this is only available from next version, currently available in dev build"`. 
This option is very helpful for us to set some custom haproxy settings which are not available as standard ingress controller options.

Regards

**Comment by oktalz** [comment]
@punkprzemo this will be included in next release (1.5.0). 
I can't say exactly when, but it should be relatively soon.

**Comment by Mo3m3n** [comment]
`haproxytech/kubernetes-ingress:1.5.0` is available and can solve this issue.

**Comment by mythi** [comment]
Thanks!

**Comment by EmericBr** [comment]
Just for note: ssl-mode-async is useless on engine rdrand, since this engine doesn't use a device and was not blocking. ssl-mode-async was designed to work using intel quick assist engine.

**Comment by mythi** [comment]
> ssl-mode-async was designed to work using intel quick assist engine.

Right, yes. QAT Engine is my use case. We can use QAT (HW or SW crypto multi-buffer) engine accelerated ingress in kubernetes.
