### ISSUE TITLE
Controller does not support graceful shutdown 

### ISSUE THREAD

**Issue by Mo3m3n** [haproxytech/kubernetes-ingress#193]
When pods are terminated (for example for rolling updates) controller won't stop HAProxy gracefully which means waiting for a timeout before tearing down established connections.

**Comment by EFX-PXT1** [comment]
@Mo3m3n - can I confirm this is still outstanding.
Any pod deletion request immediately seem to result in everything collapsing pretty much instantly.
I see this on 1.4.10 (and as far as I can tell all versions)
I am confused given the presence of terminationGracePeriodSecond handling in chart, which suggests
it is intended to work ?

**Comment by Mo3m3n** [comment]
@EFX-PXT1 correct this is still outstanding.
we have already an internal patch but got deprioritized due to more urgent tasks.
We will look at it again and I think we will have that for next release

**Comment by EFX-PXT1** [comment]
Hi @Mo3m3n - did the internal patch you had in mind make it into 1.5 ?
Best Regards

**Comment by oktalz** [comment]
hi @EFX-PXT1 
it wasn't, but will end up there in next few weeks

**Comment by Mo3m3n** [comment]
Hi @EFX-PXT1 
This was reported by a couple of users, so am back on it this week.
We may be able to release it sooner, will keep you posted here.

**Comment by Mo3m3n** [comment]
@EFX-PXT1 
haproxytech/kubernetes-ingress:1.5.1 is out with the fix, you can give it a try.

**Comment by EFX-PXT1** [comment]
Hi @Mo3m3n - yes spotted change log of 1.5.1 yesterday and have been testing.
It's a big improvement - really appreciate you including in this release.
