### ISSUE TITLE
add support for selectorless services

### ISSUE THREAD

**Issue by xytis** [haproxytech/kubernetes-ingress#2]
Given existing codebase, you filter all pods by service selector and may optionally apply "check/check-interval" annotations.

I see the following issues:
1. You do not honor static (selectorless) Services. Manual Endpoints are not balanced to, since they do not have pods associated to them.
2. There could be an issue where pod readiness check changes between versions, but service annotation remains the same. Kubernetes (and Deployment mechanism) counts new pods as operational, where Ingress controller stops routing traffic to the pods in question, bringing the service down.

**Comment by oktalz** [comment]
Services without selectors are not supported yet, they will be in next version.

Regarding issue with service annotations and new pods: these are separate resources
and ingress controller will react on service changes. 
But even if service remains the same, controller will react to creation/deletion of pods and will set check annotations appropriately.

**Comment by xytis** [comment]
Should I split the second part, where there could be a logical conflict between what Haproxy treats as active endpoints and what Kubernetes treats as active endpoints, to a separate issue?

**Comment by aiharos** [comment]
> Should I split the second part, where there could be a logical conflict between what Haproxy treats as active endpoints and what Kubernetes treats as active endpoints, to a separate issue?

If you still think this could be an issue, please do and if possible, provide more context on how you suspect this could happen.

**Comment by xytis** [comment]
No, I made a mistake in determining how you select ports to perform check on. From documentation it appeared to me that you can define full line, as in haproxy config, `... check port XX`. Since you are depending on pod exposed port, this should not be an issue.

**Comment by aiharos** [comment]
Thanks a lot for following up on this!

**Comment by oktalz** [comment]
Hi, 
version 1.1.2 is using Endpoints api from k8s, so selector-less services are now possible to use
