### ISSUE TITLE
Adding global support for HTX

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#205]
Actually, just the `stats` frontend got the HTX enabled
https://github.com/haproxytech/kubernetes-ingress/blob/14e300202f91ba3a50c44437ba41f84f53405d48/fs/etc/haproxy/haproxy.cfg#L63-L70

It would be interesting having that enabled at the `default` level, maybe using an _annotation_.

**Comment by Mo3m3n** [comment]
Actually thee is even no need for http-use-htx for stats.
Since this [commit](https://github.com/haproxy/haproxy/commit/319303739ac029ba0fb160c4d2ef02a0949c7a1f) (haproxy 2.1) HTX is the defacto mode and legacy mode was deprecated.  
So we will just have to remove that line from frontend stats.
