### ISSUE TITLE
/healthz-port (1042) not referenced and documented incorrectly

### ISSUE THREAD

**Issue by cruwe** [haproxytech/kubernetes-ingress#213]
Apparently by default, the haproxytech/kubernetes-ingress exposes prometheus-metrics on `1042` - rendered without further configuration I have 
```
frontend healthz 
  mode http
  bind 0.0.0.0:1042 name healtz_1
  monitor-uri /healthz
  option dontlog-normal
```

Both the daemonset and the deployment under `kubernetes-ingress/deploy/` do not reference `1042` and the documentation [Viewing Metrics](https://www.haproxy.com/documentation/hapee/1-9r1/installation/kubernetes-ingress-controller/#viewing-metrics) claim `1024` to be responsible for both.

Either the `/healthz`-config is due to a typo (which given the wording of the documentation I strongly suspect) or the documentation incorrectly merges the `stats` and `healthz` section under one port.

**Comment by Mo3m3n** [comment]
1042 is for monitoring haproxy 
1024 is for Prometheus stats
```
frontend stats
   mode http
   bind *:1024
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable
   stats uri /
   stats refresh 10s
```
Another ports choice would have been better to avoid confusion but the deployment manifests and the docs seems correct to me:
1024 is the port to use in order to get haproxy stats AND prometheus metrics

**Comment by cruwe** [comment]
Ok. That I understand. Thanks for the clarification.
