### ISSUE TITLE
Abnormal CPU usage due to defaultResyncPeriod

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#216]
## The issue

We were planning to implement the HAProxy Tech Kubernetes Ingress controller for our Kubernetes clusters that are roughly handling the following resources (mileage may vary):

- ~20,000 Ingress
- ~20,000 Service
- ~20,000 Service
- ~20,000 Secret

What we noticed upon installation (although in idle mode and not yet serving traffic), was the really high amount of CPU usage as you can see here from the Grafana snapshot.

![Screenshot from 2020-07-09 17-16-33](https://user-images.githubusercontent.com/9697646/87058094-f50c3900-c207-11ea-9eb0-72dc4707b551.png)

As it's visible on the graph, the average CPU consumption is more than one vCPU.

Thanks to the `pprof` server offered by the Ingress Controller, I had the chance to figure out the root cause of these spikes.

![Screenshot from 2020-07-08 14-26-55](https://user-images.githubusercontent.com/9697646/87058288-313f9980-c208-11ea-9622-454a3f625132.png)

This is the flame graph of a profile session and it's spending ~30% of the CPU time doing garbage collection activities ([profile file is available here for further investigation](https://github.com/haproxytech/kubernetes-ingress/files/4897755/pprof.haproxy-ingress-controller.samples.cpu.001.pb.gz)).

## Root cause

I started digging out the code and noticed this:
https://github.com/haproxytech/kubernetes-ingress/blob/b5889b501b37992a34c7e3b7465280a801ab3c5b/controller/kubernetes.go#L101-L157

The third argument of the `cache.NewInformer` function is the `defaultResyncPeriod`, a trivial parameter that allows setting the time period when the reconciliation between in-memory cache and the controller must be executed: when this happens, all the attached handlers will be called even if an update hasn't been applied, that means all the objects in the in-memory cache will be sent back to the handlers (without retrieving them from the Kubernetes API Server, so no relist action is executed)

Although low values are preferred in order to ensure the desired state is achieved, this is putting so much pressure on the binary since all the objects are going to be processed by the _handler funcs_, escaping from the heap and causing those GC clean-up tasks.

## Proposed solution

I've tested a custom-build using a higher value for the `defaultResyncPeriod` (_30 mins_) and the result is the following:

![Screenshot from 2020-07-09 17-32-17](https://user-images.githubusercontent.com/9697646/87059902-28e85e00-c20a-11ea-8dcf-68687aaf2864.png)

([available profiling output here](https://github.com/haproxytech/kubernetes-ingress/files/4897835/pprof.haproxy-ingress-controller.samples.cpu.009.pb.gz))

Essentially, we're just executing the first reconciliation loop (the cause of the first spikes), and then it calms down except some spikes due to the changes in the production cluster.

Using a value could be tough and not suitable for all the Ingress Controller deployments since there is no one-size-fits-all, so making it dynamic through a CLI option could do the trick.

**Comment by oktalz** [comment]
I think we need to raise this to much higher value by default, since it seems that higher value does not impact when event are coming.  
I can't pinpoint exactly, but i had issues with 30mins period because of how internally k8s api works  
(something with websockets time limits) and this may not be relevant anymore since api has changed quite a bit.
So something a bit less than that would be ideal.

Next stage then would be make this configurable via CLI to fine tune it if necessary.
