### ISSUE TITLE
Allow PROXY protocol for HTTP and HTTPS frontends

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#219]
Although could sound weird, I faced many installations where the Ingress Controller of a Kubernetes Cluster was receiving connections from an external load balancer using the PROXY protocol.

Would be great having this flag into the Ingress Controller annotations, something as boolean with the name `frontend-accept-proxy`.

I'm assuming a single flag both for HTTP and HTTPS since an odd behavior would be a non-sense, in my opinion.

**Comment by Mo3m3n** [comment]
Hi
This is already possible I think you need this [annotations](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#proxy-protocol)

**Comment by prometherion** [comment]
Thanks a lot @Mo3m3n , you're totally right: going to close this feature request.
