### ISSUE TITLE
ClusterRole extension required for publish-service feature

### ISSUE THREAD

**Issue by dschuldt** [haproxytech/kubernetes-ingress#225]
In order to use the "--publish-service" flag (1) to update the loadbalancer status of an ingress resource (2), an extension of the ClusterRole "haproxy-ingress-cluster-role" is necessary:

The verb "patch" has to be added to the ingress, ingress/status resource section of the ClosterRole object.

Thanks for your hard work on this great software.

(1) https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md
(2) https://github.com/haproxytech/kubernetes-ingress/issues/125

**Comment by Mo3m3n** [comment]
Hi,
Right we did it for the [Helm Chart](https://github.com/haproxytech/helm-charts/commit/6ac3c9c3cd701f5eaca425c5575b646927b6de44) and forgot about it the [manifests file](https://github.com/haproxytech/kubernetes-ingress/blob/master/deploy/haproxy-ingress.yaml)
This has just been fixed. Thanks
