### ISSUE TITLE
haproxy ingress controller - whitelist annotations for kubernetes not working

### ISSUE THREAD

**Issue by gabrilabs75** [haproxytech/kubernetes-ingress#229]
Hi all,
I want to made unaccessible from public internet some internal url's.
To do this I'm trying to set a list of IPs or CIDRs introducing a whitelist annotations  as follows:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    haproxy.org/whitelist: x.x.x.x/x (ip or CIDR)
...
...

Seems that something do not work properly cause if I try to exec a request via curl I receive RC 403

[ansible@k8s-caas-ansible-installer ~]$ curl -v -k https://myurl.myurl.com -H 'Host: myurl.myurl.com'
* About to connect() to myurl.myurl.com port 443 (#0)
*   Trying x.x.x.x...
* Connected to myurl.myurl.com (x.x.x.x) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
...
...
...
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: myurl.myurl.com
>
< HTTP/1.1 403 Forbidden
< content-length: 93
< cache-control: no-cache
< content-type: text/html
< connection: close
<
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
* Closing connection 0

Otherwise the blacklist directive worked as expected.  

Please let me know if i wrong something or if you have some suggestions.
thx and regards,
Gabriele

**Comment by Mo3m3n** [comment]
Hi,
Are you using `ssl-passthrough` if yes there was a related bug fixed on master and available via dev image: `haproxytech/kubernetes-ingress:dev`

Otherwise, are you sure that the source IP of the curl request arriving at HAProxy is whitelisted (mind any intermediate NAT,etc) 
You can see the source IP logged when enabling traffic logs. (via Helm [values](https://github.com/haproxytech/helm-charts/blob/3d60bad285f38f8225cf43def4c239ea85a4f90c/kubernetes-ingress/values.yaml#L183) for example)

**Comment by gabrilabs75** [comment]
Hi,
we use ssl-passthrough for other service related on the same ingress.
I've tried to install dev image but we observed the same behavior 

[ansible@myhost ~]$ curl -v -k https://myurl.myurl.com -H 'Host: myurl.myurl.com'

About to connect() to myurl.myurl.com port 443 (#0)
Trying x.x.x.x...
Connected to myurl.myurl.com (x.x.x.x) port 443 (#0)
Initializing NSS with certpath: sql:/etc/pki/nssdb
skipping SSL peer certificate verification
SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
...
...
...
GET / HTTP/1.1
User-Agent: curl/7.29.0
Accept: /
Host: myurl.myurl.com

< HTTP/1.1 403 Forbidden
< content-length: 93
< cache-control: no-cache
< content-type: text/html
< connection: close
<

403 Forbidden

In addition I'm sure that the source IP whitelisted is not natted over the network.

Thanks in advance.
Regards,
Gabriele

**Comment by gabrilabs75** [comment]
Hi all,
any idea about this issue?
Could you please let me know the number of bug fixed on master?

In addition the versions of chart and app used on our environment

Chart version: kubernetes-ingress-1.6.0 
App version: 1.4.6

Regards,
Gabriele

**Comment by Mo3m3n** [comment]
Hi @gabrilabs75 
Can you enable traffic logs (via Helm [values](https://github.com/haproxytech/helm-charts/blob/3d60bad285f38f8225cf43def4c239ea85a4f90c/kubernetes-ingress/values.yaml#L183) for example) make a curl request then send back all controller logs (from controller startup)  ?

**Comment by gabrilabs75** [comment]
Hi @Mo3m3n ,
here you can find the logs requested (after enabling traffic logs)

From Host with ip whitelisted: (myhost)

[ansible@myhost ~]$ curl -v -k https://myurl.myurl.com -H 'Host: myurl.myurl.com'

* About to connect() to myurl.myurl.com port 443 (#0)
*   Trying x.x.x.x...
* Connected to myurl.myurl.com (x.x.x.x) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*******,OU=*******,O=*****,L=*****,ST=*******,C=**
*       start date: Sep 07 13:00:51 2020 GMT
*       expire date: Sep 05 13:00:51 2030 GMT
*       common name: myurl.myurl.com
*       issuer:  CN=*******,OU=*******,O=*****,L=*****,ST=*******,C=**
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: myurl.myurl.com
>
< HTTP/1.1 403 Forbidden
< content-length: 93
< cache-control: no-cache
< content-type: text/html
< connection: close
<
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
* Closing connection 0

Response from pod ingress controller:

127.0.0.1:36936 [08/Sep/2020:12:26:34.325] https~ https/<NOSRV> 0/-1/-1/-1/0 403 212 - - PR-- 2/1/0/0/0 0/0 "GET - HTTP/1.1"
xx.xx.xx.xx:50654 [08/Sep/2020:12:26:34.150] ssl https/https 168/0/176 1889 CD 1/1/0/0/0 0/0 myurl.myurl.com

Please let me know if you have some suggestion.
Thanks,
Gabriele

**Comment by Mo3m3n** [comment]
Thanks @gabrilabs75, I see the issue:  the https proxy is getting 127.0.0.1 as source proxy
This should have been fixed already, you are sure you are using the dev image, what is the first line of the controller logs, it should look like this:`2020/09/08 18:49:17 HAProxy Ingress Controller v1.4.5 77fb077.dev`
Also can you send the HAProxy config: `kubectl exec -it $POD cat /etc/haproxy/haproxy.cfg` and will be able to have a closer look

**Comment by gabrilabs75** [comment]
Thanks @Mo3m3n , 
now I've installed this image `HAProxy Ingress Controller v1.4.5 1b81eb6.dev` and the problem seems solved.
Probably last time something gone wrong with reinstallation of image.
Anyway...do you have an idea about the avaibility of the mainstream version?
Could you let me know the bug number related to this issue?

Many Thanks,
Gabriele

**Comment by Mo3m3n** [comment]
>  Anyway...do you have an idea about the avaibility of the mainstream version?

Fixes were just released under `haproxytech/kubernetes-ingress;1.4.7`
