### ISSUE TITLE
Annotations blacklist/whitelist aren't work 

### ISSUE THREAD

**Issue by margarita-markova** [haproxytech/kubernetes-ingress#233]
I would like to configure prometheus with accessible from internet URL. I would like to get something like `https://xxxx.xyz/prometheus` (reverse proxy for prometheus), but prometheus should be accessible only from corporate network. Prometheus [doesn't support basic auth and proposes to use proxy layer's security settings](https://prometheus.io/docs/guides/basic-auth/). So, HAproxy still doesn't support basic auth #48 , but docs have some options for network restrictions: [blacklist](https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/#blacklist) and [whitelist](https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/#whitelist) annotations. I've tried to configure this options using Ingress and I receive errors.

My code:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /$1
    haproxy.org/blacklist: "0.0.0.0/0"
    haproxy.org/whitelist: "x.x.x.x/x"
  namespace: monitoring
  name: prom-ingress
spec:
  rules:
    - http:
        paths:
          - path: /prometheus
            backend: 
              serviceName: prometheus
              servicePort: 443
```
I've tried to use only whitelist annotation (without blacklist), but received the next log in both (only whitelist and whitelist with blacklist) situations.

Log of the HAproxy Ingress Controller:

```
2020/09/29 08:59:21 HAProxy Ingress Controller v1.4.7 e913aaf  
2020/09/29 08:59:21 Build from: git@github.com:haproxytech/kubernetes-ingress.git 
2020/09/29 08:59:21 Build date: 2020-09-15T10:35:48
2020/09/29 08:59:21 ConfigMap: default/smth-kubernetes-ingress  
2020/09/29 08:59:21 Ingress class: 
2020/09/29 08:59:21 Publish service: 
2020/09/29 08:59:21 Default backend service: default/smth-kubernetes-ingress-default-backend  
2020/09/29 08:59:21 Default ssl certificate: default/tls-secret 
2020/09/29 08:59:21 Controller sync period: 5s  
2020/09/29 08:59:21 controller.go:254 Running with HA-Proxy version 2.1.8 2020/07/31 - https://haproxy.org/ 
2020/09/29 08:59:21 INFO    controller.go:259 Starting HAProxy with /etc/haproxy/haproxy.cfg 
2020/09/29 08:59:21 INFO    controller.go:264 Running on smth-kubernetes-ingress-67d5449b5c-qggrx 
2020/09/29 08:59:21 INFO    controller.go:95 Running on Kubernetes version: v1.16.9 linux/amd64
[NOTICE] 272/085921 (19) : New worker #1 (20) forked  
2020/09/29 08:59:29 INFO    controller.go:213 HAProxy reloaded
2020/09/29 09:02:22 ERROR   controller.go:197 14: ERR transactionId=0f7f863b-08a2-4021-a0ef-7aca8aea40b1 
line=46 msg="error detected while parsing an 'http-request deny' condition failed to open pattern file </etc/haproxy/maps/4858751323694566701.lst>." 
2020/09/29 09:02:22 ERROR   monitor.go:140 14: ERR transactionId=0f7f863b-08a2-4021-a0ef-7aca8aea40b1
line=46 msg="error detected while parsing an 'http-request deny' condition failed to open pattern file </etc/haproxy/maps/4858751323694566701.lst>."  
2020/09/29 09:02:27 ERROR   controller.go:197 14: ERR transactionId=2e3af0bd-96d4-424f-a31c-00740b6a5c7d 
line=46 msg="error detected while parsing an 'http-request deny' condition failed to open pattern file </etc/haproxy/maps/4858751323694566701.lst>." 
2020/09/29 09:02:27 ERROR   monitor.go:140 14: ERR transactionId=2e3af0bd-96d4-424f-a31c-00740b6a5c7d
line=46 msg="error detected while parsing an 'http-request deny' condition failed to open pattern file </etc/haproxy/maps/4858751323694566701.lst>."
```

Can you help me? 
1) Does HAproxy have any other options for my problem?
2) Am I correctly use blacklist and whitelist annotations? It is a bug?

And, please, raise a priority of #48 enhancement.

**Comment by margarita-markova** [comment]
I've entered inside a pod, which consist haproxy application and checked files. Folder `/etc/haproxy/maps/` contains two `.lst` files with my ip ranges, but no one hasn't the mentioned in the log filename (`4858751323694566701.lst`)

**Comment by Mo3m3n** [comment]
Hi @margarita-markova 
Currently Ingress annotations relies only on the `host` field in ingress rules.
In your Ingress resources there is no `host` field but only paths, that's why this is not working.
This is a limitation we are aware of and we are working on, we will have it fixed this week.

**Comment by Mo3m3n** [comment]
Yes it wil

**Comment by Mo3m3n** [comment]
@margarita-markova 
This is available in latest release `haproxytech/kubernetes-ingress:v1.4.8`

**Comment by margarita-markova** [comment]
@Mo3m3n, thanks for update!
