### ISSUE TITLE
Azure Specify Static IP Assigned to cluster?

### ISSUE THREAD

**Issue by JohnGalt1717** [haproxytech/kubernetes-ingress#234]
How does one specify the static ip assigned to the cluster when setting up ha proxy's load balancer?

**Comment by prometherion** [comment]
I think you should take a look at this [guide](https://docs.microsoft.com/en-US/azure/aks/static-ip).

tl;dr; you can easily set the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group` to your Azure Resource name: once there, the Cloud Controller will update the `loadBalancerIP` spec with the IP address assigned by Azure.

**Comment by JohnGalt1717** [comment]
Thanks!
