### ISSUE TITLE
`hard-stop-after=30s` is  hardcoded since 1.4.7

### ISSUE THREAD

**Issue by punkprzemo** [haproxytech/kubernetes-ingress#247]
Last week I have opened an issue #245  for high CPU/memory utilisation. At that time we were using `dev` image version of IC and you suggested in issue to switch to latest stable `1.4.9` image.
After the switch to stable `1.4.9` CPU and memory graphs looks much better. 

But now I have an issue with latest stable branch. We are  using guacamole and xrdp desktop pods on our k8s cluster. Each time haproxy is reloaded by controller the rdp sessions are disconnected for a 5-10 seconds which is annoying for users.
I started to dig and found out that there was a commit in `1.4.7` that is causing this: https://github.com/haproxytech/kubernetes-ingress/commit/848105331eaf5eab06b5c1dabbdfadb3d3f2e355 .
This commit introduces `hard-stop-after 30s` default value which in stable branch can’t be changed without touching manually haproxy.cfg inside container. Documentation states that you can tweak that value via configmap but only using `dev` branch images.
 Do you have any suggestions how we should deal with RDP sessions on HAProxy IC?
 It looks like we can use dev branch but we will have cpu/memory issues or we can use stable branch but we will have disconnection issue for RDP connections.

**Comment by punkprzemo** [comment]
so i changed this morning manually in container with image `1.4.9` the value of `hard-stop-after` to `12h` . And of course memory and CPU usage start growing fast.
![image](https://user-images.githubusercontent.com/36777025/99507949-50072700-2984-11eb-9266-c3e4fad86556.png)
That's bad... 
@Mo3m3n Is the haproxy mechanism of ["Hitless Reloads"](https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/) implemented in the `haproxy ingress controller` ?

**Comment by Mo3m3n** [comment]
@punkprzemo 
You can now tune this parameter via [hard-stop-after](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#hard-stop-after) annotation in `haproxytech/kubernetes-ingress:1.4.10`

**Comment by ufou** [comment]
@punkprzemo what was your resolution of this in the end, do you set the hard-stop-after value to something that is in between 30s and 12hr to avoid increased cpu/mem or another workaround? We are facing the similar issue in that we would like to be able to hpa scale our backend service but that means that current TCP sessions are disconnected until the haproxy config is reloaded... (maybe this is subtly different problem, but smells the same)

**Comment by punkprzemo** [comment]
@ufou I have tried to increase `hard-stop-after `  value to 12h but for our type of workload it didn't help and caused memory and CPU utilization start growing very quickly.  So as a quick solution we have switched to `nginx ingress controller` which seems to be much more stable and better implemented in terms of memory/CPU utilization. 
You have same reloads in nginx but you can also set there `worker-shutdown-timeout` which is similar to haproxy `hard-stop-after`. After having set `worker-shutdown-timeout` to big value like 12hr or 7days  CPU and memory looks much better for nginx ingress controller.
Just to show how did it look like  for our workloads:

Below is haproxy memory/cpu utilization without `hard-stop-after` set  or set to big value like 7days.
![image](https://user-images.githubusercontent.com/36777025/100725517-6cfc1b00-33c4-11eb-96eb-953ec45c0f1c.png)

As you can see on the above graph haproxy instance went to CPU/memory limits almost everyday around ~3PM and crashed. Also during high cpu/memory usage we had random `503` errors because some endpoints in haproxy.cfg  weren't updated correctly.

Below is same graph for nginx ingress controller which has `worker-shutdown-timeout` set to 7 days for same type of workload.
![image](https://user-images.githubusercontent.com/36777025/100726582-6cb04f80-33c5-11eb-9bb7-30ee0380886a.png)

On the graph for nginx , CPU usage is quite stable . Memory usage is growing but not to the limit  and it's nicely going down during the night. 

Generally speaking reloads are not good for long live connections like websockets connections and rdp. I think it's a good idea to separate this type of workloads to dedicated ingress controller so you can have dedicated configuration and you won't be affected so much by frequent reloads caused by other type of deplyments.

**Comment by Mo3m3n** [comment]
> Is the haproxy mechanism of "Hitless Reloads" implemented in the haproxy ingress controller ?

Yes it is, thats what makes you keep all your old connections when reloading.

The problem experienced here is related to two factors:
- How much time you want to keep your old connections `hard-stop-after` in HAProxy controller and `worker-shutdown-timeout` in Nginx controller.
- How many times controller is reloading.

So if you have a long timeout and controller is reloading many times in between you will end with many old instances thus increasing resource memory/cpu consumption. 
@ufou we've done important work on `1.5` to decrease the number of reloads this will let you have bigger values for `hard-stop-after` with less impact on resource usage. We will have a RC the next few days.
