### ISSUE TITLE
how to enable HTTP2 GRPC Proctol without SSL

### ISSUE THREAD

**Issue by aliridha1510** [haproxytech/kubernetes-ingress#249]
Hello

I have problems with the setting. I have a **.net core grpc backend** that does **not handle SSL** but relies on the proxy information to tell it that it is SSL anyway.

I added annotations` Server-SSL:"true" `in `Configmap`, so backend is sent _http/2_ and _SSL_ , which I expect backend to send only http/2 without SSL 

Basically, if server-ssl is enabled, then alpn h2
if server-ssl is not activated, then proto h2 on the server line.

There is annotation that only enables Http2, and SSL disabled ?

How do you get it to have http/2? (or preferably keep whatever the customer request was?)

i have searched the code for , and there is [code](https://github.com/haproxytech/kubernetes-ingress/blob/master/controller/haproxy/server.go#L84)

can somebody suggest idea or fix please ?

Best regards.

**Comment by Mo3m3n** [comment]
Hi 
Currently the controller will either enable both TLS + H2 altogether via 'server-ssl` annotation or won't enable either of them.  
So if am understanding correctly you want to have only H2 on backend side in order to use insecure gRPC via h2c correct ?

**Comment by aliridha1510** [comment]
@Mo3m3n  Thank you for your response

I forked the project to active HTTP2 without SSL, and I have this now in the haproxy.cfg file,

`server SRV_XjBvz 127.0.0.1:9090 disabled check alpn h2 weight 128 verify none
`

But i have all the time 502 exception, despite in the logs I see that


`172.18.6.2:52569 [18/Nov/2020:23:37:16.167] http haproxy-controller-service-9898/SRV_zXX0N 0/0/0/-1/0 502 229 - - PH-- 1/1/0/0/0 0/0 "POST foo.bar:32455/v.SettingsService/LoadConfig HTTP/2.0"
`

**Comment by Mo3m3n** [comment]
> server SRV_XjBvz 127.0.0.1:9090 disabled check alpn h2 weight 128 verify none 

You can strip 'verify none' too

> 172.18.6.2:52569 [18/Nov/2020:23:37:16.167] http haproxy-controller-service-9898/SRV_zXX0N 0/0/0/-1/0 502 229 - - PH-- 1/1/0/0/0 0/0 "POST foo.bar:32455/v.SettingsService/LoadConfig HTTP/2.0" 

The [termination state](https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#8.5) is telling that error is coming from the server.
you can try `echo "show errors" | socat stdio /var/run/haproxy-runtime-api.sock`  maybe you will get more info

**Comment by aliridha1510** [comment]
when I call the service directly, it answers correctly
i found this error in socket 
```

[19/Nov/2020:00:11:24.932] backend haproxy-controller-settingsservice-9090 (#7): invalid response
  frontend http (#3), server SRV_zXX0N (#40), event #3, src 172.18.6.2:62190
  buffer starts at 0 (including 0 out), 16321 free,
  len 63, wraps at 16336, error at position 0
  H1 connection flags 0x00000000, H1 stream flags 0x0000401c
  H1 msg state MSG_RPBEFORE(8), H1 msg flags 0x00001404
  H1 chunk len 0 bytes, H1 body len 0 bytes :

  00000  \x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x04\x00@\x00\x00\x00\x05\x00@
  00019+ \x00\x00\x00\x06\x00\x00 \x00\xFE\x03\x00\x00\x00\x01\x00\x00\x04\x08
  00037+ \x00\x00\x00\x00\x00\x00?\x00\x01\x00\x00\x08\x06\x00\x00\x00\x00\x00
  00055+ \x00\x00\x00\x00\x00\x00\x00\x00

/run #      
```

**Comment by Mo3m3n** [comment]
Actually I think you will need `proto h2` rather than `alpn h2` 
if this works for you it won't be difficult for us to patch the controller for unencrypted H2.

**Comment by aliridha1510** [comment]
how can i enable` proto h2` this paramater? there is a config map ?

**Comment by Mo3m3n** [comment]
Can you jump on our [slack-channel](https://github.com/haproxytech/kubernetes-ingress#discussion) to discuss this and later put results here ?

**Comment by Mo3m3n** [comment]
Enabling HTTP2 without SSL is possible starting form `haproxytech/kubernetes-ingress:1.5.0` 
Via [server-proto](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#server-proto)

**Comment by ubarar-poolside** [comment]
Hi @Mo3m3n , could you provide some guidance on how to use `server-proto`? I've tried:
- Adding the `haproxy.org/server-proto: h2` annotation to my Ingress
- Adding the `haproxy.org/server-proto: h2` annotation to my Backend
- Adding the `server-proto: h2` entry to my `haproxy-ingress-kubernetes-ingress`
  - This changed the protocol to h2 for the `kube-system_prometheus_http` backend, but my application backend.

When I look at the rendered config on the controller I see the following:
```
backend staging-codeexec_staging-codeexec-rpc-headless-0_http
  mode http
  server SRV_1 10.173.138.66:10022 enabled
  server SRV_2 127.0.0.1:10022 disabled
  server SRV_3 127.0.0.1:10022 disabled
  server SRV_4 127.0.0.1:10022 disabled
...
```

Any help would be appreciated :) Thank you

**Comment by ubarar-poolside** [comment]
Solved the above issue by adding

```
    default_server:
      proto: h2
```

to the `Backend` resource.
