### ISSUE TITLE
Lowercasing of path

### ISSUE THREAD

**Issue by ocdi** [haproxytech/kubernetes-ingress#251]
I was experimenting with this ingress controller and combining this with the [cert manager](https://cert-manager.io/docs/configuration/acme/http01/).

At first the ingress was created, however the challenge was constantly failing. I managed to determine that the challenge path had uppercase characters and the rules in the `haproxy.cfg` don't allow this at all.

I believe the lowercasing from this rule should be removed, per:

```diff
-http-request set-var(txn.path) path,lower
+http-request set-var(txn.path) path
```

I made my own docker image with this change and was successful in having a certificate issued after this.

I can certainly create a PR to this effect, however I wanted to check if my understanding of this solution is a good one and whether the PR would be accepted first.

**Comment by Mo3m3n** [comment]
Which controller version you are using ?

**Comment by ocdi** [comment]
The latest image on docker hub,  1.4.10

I had one cert work but somehow the lower keyword has returned which prevented a second host name from validating. I was investigating how that's possible but I'm still checking.

**Comment by Mo3m3n** [comment]
Currently v1.4 is not case sensitive when it comes to host and path matching.
If you confirm this is causing an issue for certmager we can work on fixing this. 
You can enable [HAProxy logs](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#syslog-server) where incoming request host/path is logged,  in case this makes the debug easier for you

**Comment by ocdi** [comment]
So the haproxy version running is HA-Proxy version 2.1.10-7aff177 2020/11/05

I enabled logs and it logged the 404, being routed through to the intended service (but not the ACME solver pod).

I made a new version of the docker image with this change, and that seemed to work.

```diff
index 497ff7f..2deed39 100644
--- a/controller/requests.go
+++ b/controller/requests.go
@@ -154,7 +154,7 @@ func (c *HAProxyController) FrontendHTTPReqsRefresh() (reload bool) {
                        Type:     "set-var",
                        VarName:  "path",
                        VarScope: "txn",
-                       VarExpr:  "path,lower",
+                       VarExpr:  "path",
                }
                c.Logger.Error(c.Client.FrontendHTTPRequestRuleCreate(frontend, setVarRule))
                // STATIC: SET_VARIABLE txn.host (to use in http rules)
```


This is the ACL rule that appeared to not be working
```
use_backend default-cm-acme-http-solver-bwpq2-8089 if { var(txn.host) hostname.here } { var(txn.path) -m beg /.well-known/acme-challenge/qfo5KRPBJ9ciRXryz8onvRrhdqgiKKWEGzCkBr46_Zw }
```

Reading the docs it would appear that the rules are case sensitive
https://www.haproxy.com/blog/introduction-to-haproxy-acls/#flags


`-i` Perform a case-insensitive match (so a sample of FoO will match a pattern of Foo)
