### ISSUE TITLE
Ingress returns 503s while Master is unavailable

### ISSUE THREAD

**Issue by lukasged** [haproxytech/kubernetes-ingress#257]
**HAProxy Ingress controller version**:
1.4.10

**Kubernetes version** (use `kubectl version`):
v1.18.6

**What happened**:
Whenever there's an outage of the Kubernetes Master node (either planned or not), all the apps behind the HAProxy Ingress controller fail with a "503 Service Unavailable. No server is available to handle this request.", and as soon as the Master is back the correct behaviour resumes.

**What you expected to happen**:
I expect that the Ingress controller should continue working as usual for the already deployed applications with a Master / control plane outage. I don't expect the Ingress controller to be aware of changes to backends, but it should continue to function with the backends it already knows about.

**How to reproduce it** (as minimally and precisely as possible):
Use a K8S cluster with single master, install HAProxy ingress and hello world service and restart master. App will return `HTTP 503` until master is back.

As a side note, it seems that almost an identical behaviour also happens with other Ingress controllers like Traefik or nginx. Does it make sense? Is it expected?

**Comment by ivanmatmati** [comment]
Hi lukasged,
I didn't manage to reproduce the issue you reported. I tested with the following protocol running inside Kind.
- create a pod shell with ab (apache bench) installed.
- carry out ab for 10 seconds onto controller adress.
- stop the master containers of kube-apiserver, kube-controller-manager and kube-scheduler during the interval.
- the containers are automatically restarted.
- the results of ab shows no failed requests.

Concerning the cluster setup, I used the same version of IC as yours and deployed a nginx server as default backend.
Can you check with this setup ?
Can you also give me the haproxy.cfg file in the faulty case to make a double check ?
