### ISSUE TITLE
deploy/haproxy-ingress.yaml uses wrong resource name in ClusterRole (ingressClasses -> ingressclasses)

### ISSUE THREAD

**Issue by alainvanhoof** [haproxytech/kubernetes-ingress#269]
The resource in  deploy/haproxy-ingress.yaml  'ingressClasses' is wrong, it should be: 'ingressclasses '

The wrong name generates this error in the haproxy-controller (1.5.0) 

User "system:serviceaccount:haproxy-controller:haproxy-ingress-service-account" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**Comment by Mo3m3n** [comment]
Thank you for reporting this.
Fixed https://github.com/haproxytech/kubernetes-ingress/commit/4700559761b4ac365acda6579902872320ae1645
