### ISSUE TITLE
Why 2 HAProxy k8s ingress controller projects?

### ISSUE THREAD

**Issue by mecampbellsoup** [haproxytech/kubernetes-ingress#272]
Hi guys -

We are looking at different API gateway solutions for a project we are embarking on.

We wanted to see what HAProxy-as-k8s-ingress options were out there, and immediately you see that in addition to this project there is another:

https://github.com/haproxy-ingress/charts

I [asked the other project](https://github.com/haproxy-ingress/charts/issues/10#issuecomment-767682699) for a little context on why such a split existed in the community (as compared to e.g. the NGINX/OpenResty gateway people which have all coalesced around [Kong](https://github.com/Kong/kong/)), but I was curious to see your perspective on it.

* Are there important differences that potential new users like us should be aware of starting out?
* Is documentation significantly better/worse?
* etc.

Thanks for your help in evaluating our options here.

**Comment by kowshikn** [comment]
@daniel-corbett Hello, can you share more details about the scaling issue. I am in particular interested to know about any benchmark or production systems that have used  **haproxytech/kubernetes-ingress**  with multiple ingress resources. I have a usecase where we will be running multiple ingress resources(about thousand) with high throughput. Would be great if you can share more details about it.

**Comment by bluebrown** [comment]
But what is the actual difference?

**Comment by mecampbellsoup** [comment]
> But what is the actual difference?

Read the maintainer's response [here](https://github.com/haproxy-ingress/charts/issues/10#issuecomment-767682699).
