### ISSUE TITLE
haprox-ingress pod stuck in Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by S-Hurion** [haproxytech/kubernetes-ingress#274]
Hello,

We use a baremetal kubernetes cluster in v1.20.1, running on Debian 9.12 nodes.

I tried to apply the newest version of the  haproxy-ingress deploy with :
`kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml`

The "haproxy-ingress" pod  fail to deploy with "Init:CrashLoopBackOff" status.

Here's what I get when I use the describe command on the pod:
https://gist.github.com/S-Hurion/49a61d11b16c9122920a28f94976c6e5

I then tried to use the 1.4 version, so I deleted the 1.5 version to recreate in 1.4:
`kubectl delete -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml`
`kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.4/deploy/haproxy-ingress.yaml`

But the pod is now stuck in CrashLoopBackOff, for another reason.
Here is the pod logs:
https://gist.github.com/S-Hurion/a14a459198d0cb290d50f7f72fa6f7cc
And the pod "describe":
https://gist.github.com/S-Hurion/d1d0f1cd342692aa4d479dd1fd1bf2fd

The workaround I found is to use the 1.4 deploy with the ClusterRole from 1.5.
That's not ideal. Is this issue caused the nature of our cluster ? Did i miss something ? 
Can you help us to get the 1.5 deploy working on our cluster ?

Thanks in advance,

Best regards.

**Comment by Mo3m3n** [comment]
Hi @S-Hurion 
Can you send the controller logs when you have first tried:
```
kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml
```
The logs you have sent here https://gist.github.com/S-Hurion/a14a459198d0cb290d50f7f72fa6f7cc are about running 1.5 Ingress Controller with a 1.4 deploy manifest so it makes sense to see those errors (incorrect permissions with clusterrole)
But It would be useful to know what you had a CrashLoopBackOff when deploying IC with 1.5 deploy by looking in controller logs

**Comment by S-Hurion** [comment]
Hello @Mo3m3n ,

Thanks for your answer,

I cannot get the logs when I do 
`kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml`
Because the pod is stuck in Init:CrashLoopBackOff , so when i try to do 
`kubectl logs haproxy-ingress-67f7c8b555-4mp98 -n haproxy-controller` 
I get the following message:
`Error from server (BadRequest): container "haproxy-ingress" in pod "haproxy-ingress-67f7c8b555-4mp98" is waiting to start: PodInitializing`
When I do 
`kubectl logs haproxy-ingress-67f7c8b555-mrds4 -n haproxy-controller --previous`
I get the following message:
`Error from server (BadRequest): previous terminated container "haproxy-ingress" in pod "haproxy-ingress-67f7c8b555-mrds4" not found`

The only relevant info I  can get is this part in the describe:

```
Init Containers:
  sysctl:
    Container ID:  docker://9c7296f5eb8a458e1e6cdef0c820cac17a3b1b143b8fa569a29c343596337e5e
    Image:         busybox:musl
    Image ID:      docker-pullable://busybox@sha256:2b299b7f6cd9fd88b5deea6fcd86583537c0f6f09f0c6bee11fdb3810e143134
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      sysctl -w net.ipv4.ip_unprivileged_port_start=0
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 08 Mar 2021 11:06:22 +0100
      Finished:     Mon, 08 Mar 2021 11:06:23 +0100
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from haproxy-ingress-service-account-token-mvl29 (ro)
```
It looks like the busybox container trying to run "sysctl -w net.ipv4.ip_unprivileged_port_start=0" fail and send an error back, preventing the pod from starting.

Do I need to change something to my cluster to allow sysctl command to run ?

Best regards,

**Comment by S-Hurion** [comment]
Some more info:
For testing purpose, I ran a busybox:musl pod and tried to do
`sysctl -w net.ipv4.ip_unprivileged_port_start=0`
I got the following error:
`sysctl: error: 'net.ipv4.ip_unprivileged_port_start' is an unknown key`
However, if I try 
`/bin/sh -c sysctl -w net.ipv4.ip_unprivileged_port_start=0`
I got no error message.

Does the init busybox:musl pod run " /bin/sh", "-c" and "sysctl -w net.ipv4.ip_unprivileged_port_start=0" separately, causing the error ?

**Comment by dkorunic** [comment]
Host Linux kernel seems to be older than `4.4`. Either don't use binding to privileged ports and remove the whole initContainers or use newer kernel, ie. any more recent from stretch-backports. Also, do you know that we also offer Helm chart (https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress) that is much easier to deploy then with raw YAML configuration?
