### ISSUE TITLE
Docs unclear: how to run Sample?

### ISSUE THREAD

**Issue by realulim** [haproxytech/kubernetes-ingress#279]
I am referring to this page of the docs:
https://www.haproxy.com/documentation/kubernetes/latest/usage/ingress/

It says there, after installing the sample service and ingress resource:

`Make requests to the echo service through the ingress controller’s IP address and port, e.g. http://192.168.99.100:32063/echo.`

But it is unclear what is meant by "IP address and port of ingress controller". Doing a `kubectl get ingress` shows:
```
NAME           CLASS    HOSTS   ADDRESS   PORTS   AGE
echo-ingress   <none>   *                 80      24s
```
How can I find the IP address and port to hit the echo service?

**Comment by Mo3m3n** [comment]
This depends on how you expose your Ingress Controller.
That is the configuration you put in the Ingress Controller's [service](https://kubernetes.io/docs/concepts/services-networking/service/)

**Comment by realulim** [comment]
My suggestion for the docs would be to make the hello world example self-contained, so a new user could follow it along and get a result. If that is too time-consuming, then I think at least mentioning prerequisites as "exercise for the reader - do this first" would be useful.

**Comment by Mo3m3n** [comment]
Thanks for your feedback @realulim 
I have reported this to the website team and will keep this ticket open to follow the progress of a "hello world" example.

**Comment by sandys** [comment]
same here - i would also request for a hello world example and links to point to OFFICIAL images/repos of haproxy ingress.

**Comment by Tolga-Karahan** [comment]
I'm using minikube. Installed haproxy via helm install and  deployed echo-server, its service as a cluster-ip, and a ingress that with a hostname. I also added this host to the /etc/hosts file with IP address of the minikube cluster, but no luck. My ingress is not working.

**Comment by Mo3m3n** [comment]
The reported issues should have been addresses in the online doc by the time of writing.
