### ISSUE TITLE
alpine-3.12.1 openssl vuln - bump to 3.12.4

### ISSUE THREAD

**Issue by EFX-PXT1** [haproxytech/kubernetes-ingress#281]
Can the next 1.5.2 release be bumped to alpine-3.12.4 which includes the openssl remediation ?
- https://alpinelinux.org/posts/Alpine-3.10.6-3.11.8-3.12.4-released.html
1.5.1 is based on 3.12.1.

Many Thanks.

**Comment by dkorunic** [comment]
@EFX-PXT1 We don't bump base image versions by hand. Base image for Ingress Controller is `haproxytech/haproxy-alpine` which in return is based on `alpine:3.12`. That will get automatically bumped either when Docker base image `alpine:3.12` gets rebuild or when we rebuild `haproxytech/haproxy-alpine` on next major build.

**Comment by EFX-PXT1** [comment]
Hi @dkorunic - thanks for the comment.
Just to educate myself, that means waiting for 2.2.10 ?
- https://github.com/haproxytech/haproxy-docker-alpine/blob/master/2.2/Dockerfile#L1
And _then_ a 1.5.x that picks up 2.2.10 ?
Not a 1.6.x

**Comment by dkorunic** [comment]
@EFX-PXT1 We use HAProxy CE `2.3.x` releases on Alpine base image for now, so we would wait for a new `2.3.6` image. Incidentally, it has just been released and I've pushed a rebuild of Ingress Controller version `1.5.1` against latest HAProxy CE `2.3.6` base image.

**Comment by dkorunic** [comment]
`v1.5.1` of Ingress Controller has been rebuilt.

**Comment by EFX-PXT1** [comment]
Many thanks @dkorunic for flagging 2.3.6 and rebuilds
