### ISSUE TITLE
How to import multiple certificates

### ISSUE THREAD

**Issue by Kamaradeivanov** [haproxytech/kubernetes-ingress#285]
If I understand your documentation we can add multiple certificates with RSA and ECDSA format in the ingress controller side : 
https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#tls-secret

But how to generate the secret with multiple certificates and keys ?

There is no information to do that, and adding the secret into the ingress-rules is not relevent for us because we dont want to copy ours certificates in each namespace.

**Comment by ivanmatmati** [comment]
Hi @Kamaradeivanov , I'm not sure what you're trying to do exactly. If my guess is correct, you want the command to create the secret with RSA and ECDSA certificates. You can find the information in this [reference](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret). For example with literal values, you could issue:
`kubectl create secret generic mycertificatessecrets --from-literal=rsa.key=rsakey --from-literal=rsa.crt=rsacertificate --from-literal=ecdsa.key=ecdskey --from-literal=ecdsa.crt=ecdsacertificate`
Feel free to provide more context if that's not what you expected.

**Comment by Kamaradeivanov** [comment]
Hello, my first wish was to add multiple certificate to the ingress controller like :

- *.test.io
- *.test.com
- *.test.ninja

If I understand well your documentation [here](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#tls-secret), you mention : `certificate secret with rsa and ecdsa certificates`. So I had supposed that if I use RSA or ECDSA format I could attach multiple certificates to be default certificates.

But maybe i'm wrong and we couldnt add multiple certificates to the haproxy ingress controller.

**Comment by ivanmatmati** [comment]
Hi @Kamaradeivanov , RSA and ECDSA are two different formats. Even if theoretically you could insert two differents certificates in the same secret they're supposed to be the same in different formats. Still,the default certificate is supposed to be unique.

**Comment by Mo3m3n** [comment]
Hi the doc may be not clear about this, but as even mentioned the controller accepts only one format per secret.
HAProxy though supports loading multiple formats of the same certificate (rsa, dsa, ecdsa) but this is not yet supported in Ingress Controller.
Tagging issue with enhancement label to consider adding this in the future.

**Comment by Mo3m3n** [comment]
After looking closer, this is a regression and controller should support this.
So it is fixed now in https://github.com/haproxytech/kubernetes-ingress/commit/50d5f6649e16ac1542483807bda8e13f497b5e61 and patch released in `haproxytech/kubernetes-ingress:1.5.5`
Also documentation was [updated](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#ssl-certificate) to make it clearer how to provide expected input.
