### ISSUE TITLE
Missing configmap error

### ISSUE THREAD

**Issue by benjamin-bergia** [haproxytech/kubernetes-ingress#289]
Hi, I got myself in some troubles during the deployment of the daemonset using the yaml files provided. I didn't notice the different names/namespaces used for the configmap on the deployment and daemonset. I spent quite a bit of time finding the cause.

Currently when a pod starts and cannot find the configmap passed with `--configmap=`. The pod fails with:

> [NOTICE] 069/125456 (34) : New worker #1 (35) forked
2021/03/11 12:55:23 INFO    controller.go:168 Stopping Ingress Controller
2021/03/11 12:55:23 ERROR   controller.go:169 waitid: no child processes

It would probably be a good idea to add a test and throw a more explicit error when the pod cannot find the configmap.

**Comment by Mo3m3n** [comment]
Hi, 
Thanks for reporting, this was handled in https://github.com/haproxytech/kubernetes-ingress/commit/740648d2fe59c06ac1ddf78f2a815dfc783cab29 and available in `1.5.4`.
In 1.6 ConfigMap will no more be mandatory.
