### ISSUE TITLE
Protect stats page with basic auth

### ISSUE THREAD

**Issue by guanzo** [haproxytech/kubernetes-ingress#293]
Hi, the routes my HAProxy serves are all public, but I want the stats page behind basic auth.

Seems like all I need is this config

```
frontend stats
 # other default config
  stats auth hi:mom
```

but i can't find a way to get my `stats auth hi:mom` config there? There's a `global-config-snippet`, `backend-config-snippet`, but no `frontend-config-snippet`.

HAProxy errors when I put `stats auth hi:mom` in the `global-config-snippet`.

**Comment by Mo3m3n** [comment]
Hi
You can use [stats-config-snipppet](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#stats-config-snippet) currently in `haproxytech/kubernetes-ingress:dev` and will be available in 1.6 release scheduled for 04/2021

**Comment by guanzo** [comment]
Love the quick response, thanks!!

**Comment by Mo3m3n** [comment]
Available starting from Ingress Controller v1.6
