### ISSUE TITLE
Trying to set defaultTLSSecret value but it throws weird error

### ISSUE THREAD

**Issue by barisvelioglu** [haproxytech/kubernetes-ingress#300]
I have a secret which is generated by cert-manager. I can see it when I query it.

![image](https://user-images.githubusercontent.com/1805891/113726804-367d3680-96fd-11eb-936d-b09154dc12d0.png)

When I try to set defaultTLS

`helm install haproxy-controller  --set-string "controller.defaultTLSSecret.secret=default/mqtttls" haproxytech/kubernetes-ingress
`
When I looked at the pod logs, it says:

> invalid argument for flag `--default-ssl-certificate' (expected utils.NamespaceValue): expected two strings separated by a /

But It is already seperated by / => default/mqtttls

What's wrong ?

Thanks,

**Comment by Mo3m3n** [comment]
Can you send the result of `kubectl describe pod <ic-pod-name>`  ?

**Comment by barisvelioglu** [comment]
PS D:\projects\ha-proxy-details> kubectl describe pods haproxy-controller-kubernetes-ingress-6f9b89ddd4-t74cw

Name:         haproxy-controller-kubernetes-ingress-6f9b89ddd4-t74cw
Namespace:    default
Priority:     0
Node:         aks-agentpool-38058373-vmss000001/10.240.0.5
Start Time:   Tue, 06 Apr 2021 17:35:42 +0300
Labels:       app.kubernetes.io/instance=haproxy-controller
              app.kubernetes.io/name=kubernetes-ingress
              pod-template-hash=6f9b89ddd4
Annotations:  <none>
Status:       Running
IP:           10.244.1.38
IPs:
  IP:           10.244.1.38
Controlled By:  ReplicaSet/haproxy-controller-kubernetes-ingress-6f9b89ddd4
Containers:
  kubernetes-ingress-controller:
    Container ID:  containerd://512a7a90ba23098643bd264eb88b8ed3ccab4823044004207c5ae317e6c792f9
    Image:         haproxytech/kubernetes-ingress:1.5.3
    Image ID:      docker.io/haproxytech/kubernetes-ingress@sha256:bf5075d90a73241e2fe5b617bb04351798ca54e64e767eaeb8269799e9b0e30a
    Ports:         80/TCP, 443/TCP, 1024/TCP, 3306/TCP, 1883/TCP, 18083/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --default-ssl-certificate=default/default/mqtttls
      --configmap=default/haproxy-controller-kubernetes-ingress
      --default-backend-service=default/haproxy-controller-kubernetes-ingress-default-backend
      --log=info
      --configmap-tcp-services=default/tcp
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 06 Apr 2021 17:35:59 +0300
      Finished:     Tue, 06 Apr 2021 17:35:59 +0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 06 Apr 2021 17:35:44 +0300
      Finished:     Tue, 06 Apr 2021 17:35:44 +0300
    Ready:          False
    Restart Count:  2
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   http-get http://:1042/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:1042/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:    http-get http://:1042/healthz delay=0s timeout=1s period=1s #success=1 #failure=20
    Environment:
      POD_NAME:       haproxy-controller-kubernetes-ingress-6f9b89ddd4-t74cw (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from haproxy-controller-kubernetes-ingress-token-lrxcm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  haproxy-controller-kubernetes-ingress-token-lrxcm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  haproxy-controller-kubernetes-ingress-token-lrxcm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned default/haproxy-controller-kubernetes-ingress-6f9b89ddd4-t74cw to aks-agentpool-38058373-vmss000001
  Normal   Pulled     5s (x3 over 21s)  kubelet            Container image "haproxytech/kubernetes-ingress:1.5.3" already present on machine
  Normal   Created    5s (x3 over 21s)  kubelet            Created container kubernetes-ingress-controller
  Normal   Started    5s (x3 over 21s)  kubelet            Started container kubernetes-ingress-controller
  Warning  BackOff    5s (x4 over 20s)  kubelet            Back-off restarting failed container

**Comment by Mo3m3n** [comment]
The end result is not good:
` --default-ssl-certificate=default/default/mqtttls` 
I guess this is due to the Helm Chart expecting just a simple secret name to append it to the release NS as you can see in:
https://github.com/haproxytech/helm-charts/blob/b363778dfbd5ac41246b67e0043dbe01c5afc83b/kubernetes-ingress/templates/controller-deployment.yaml#L80

The quick fix is just to provide the secret name to the Helm Chart:
```
helm install haproxy-controller --set-string "controller.defaultTLSSecret.secret=mqtttls" haproxytech/kubernetes-ingress 
```
But an issue needs to be opened in the chart repo to allow for a secret input with a ns/name format

**Comment by barisvelioglu** [comment]
I think this is a bug and it needs to be opened.

**Comment by Mo3m3n** [comment]
If the above did not fix your issue then it is an ingress controller bug, if it did fix your issue then it is related to Helm chart so this should be opened here: https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress which I just did in https://github.com/haproxytech/helm-charts/issues/67
