### ISSUE TITLE
Ingress not working

### ISSUE THREAD

**Issue by gauravmeena83** [haproxytech/kubernetes-ingress#303]
The ingress objects are not assigned any IP.

I am using a 3 master cluster with kubernetes 1.20.2, and using the latest haproxyte kubernetes ingress controller. I have another ingress controller too using nginx, which works fine.

Using kube-vip for load balancing, I m on bare-metal, using centos as base, and I define static IP for load balancer service type for haproxy-ingress.

**Comment by Mo3m3n** [comment]
I think you will need to enable [--publish-service](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--publish-service)

**Comment by gauravmeena83** [comment]
> I think you will need to enable [--publish-service](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--publish-service)

Have tried that too...
My arguments read
--publish-service haproxy/haproxy-ingress

**Comment by gauravmeena83** [comment]
My problem is that, even though the VIP or the loadBalancerIP is statically defined in the HAproxy serivce, and kubevip does assign a new VIP (ping to the IP goes through) after applying the service, the controller (and its default bachend) is not reachable on that IP (http://<IP>/).

Exactly similar setup for nginx-ingress just works, and I am able to reach the controller as well as any ingress created here.

**Comment by Mo3m3n** [comment]
Can you provide:
- Startup logs of Ingress Controller (We need to be able to see in logs the IC version and the configured options)
- a `kubectl get ingress  <your-ingress>  --output yaml` of one of the ingresses that you were expecting them to have an assigned IP.

**Comment by gauravmeena83** [comment]
The --publish-service problem is resolved .. there was a typo, a night's sleep was the solution.... I am still working on getting the expected result.

On a different note, I was not able to create the controller on 80, 443 binding, finally changed the ports to 8080 and 84443. Can you suggest what privilages can be given to the pods/container or the linux machine to be able to bind on 80 and 443 ports?

**Comment by gauravmeena83** [comment]
all the things are [here](https://gist.github.com/gauravmeena83/e8da87fbc1e632a0ea426091acf62367)

Lemme know what else we need.

I played with several installation of kubevip as well, if there was problem, can share that setup too if need be. current setup, allow any service to define a loadbalancer and start receiving traffic on that (I already tries with several, before and after haproxy deployment)... however, haproy never seems to take the traffic.
