### ISSUE TITLE
Whitelist tcp services ?

### ISSUE THREAD

**Issue by tili41** [haproxytech/kubernetes-ingress#306]
Hello, I didn't find a solution to add a whitelist for TCP services (tcp mode). 

The whitelist parameter works only for http frontend. Same for frontend-config-snippet and we obviously can't use the Ingress object for tcp service.

Ideally we should be able to add a whitelist by tcp service in addition to having a global whitelist, maybe in the tcp-services configmap ?

**Comment by Mo3m3n** [comment]
Hi,
Right currently annotations will be set either in the http frontends (ingress annotations) or in the application backend (service annotations)
Thus the only way to handle this is by using [backend-config-snippet](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#backend-config-snippet) by annotating the kubernetes service of your application which is going to put the config in your tcp backend.
We are currently working on making tcp services more configurable, but we don't want to continue overloading annotations so we are working on a dedicated CRD instead.

**Comment by tili41** [comment]
Thanks for the tip, it's a good way to manage the tcp services whitelist while waiting for a CRD easier to configure than annotations.

```
backend-config-snippet: |
  tcp-request connect deny if !{ src -f patterns/ips }
```

See https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md/#--configmap-patternfiles
