### ISSUE TITLE
Namespace Whithlisted Issue if configmap namespace not in range

### ISSUE THREAD

**Issue by sysadmfrds** [haproxytech/kubernetes-ingress#308]
Hello everyone ! 
I'm bringing up a bug that I just encountered while upgrading from version 1.5.4 to any other higher version.
I can only focus on the functional part as I am not a developer.

Since version 1.5.5, we have noticed an abnormal behavior with the management of namespace whitelist

If we configure the controller with whitelisted namespaces.
`...--namespace-whitelist=rec --namespace-whitelist=test...`

And that the configmap used is still in another namespace
`--namespace-whitelist=rec --namespace-whitelist=test --configmap=kube-system/hap-rec-cm`

The ingress controller runs but does not detect any of our ingress objects.

After analysis, we notice in the logs : 

```
2021/05/04 12:46:22 WARNING monitor.go:167 configmap Namespace 'kube-system' not whitelisted. Whitelisting it anyway
2021/05/04 12:46:22 INFO monitor.go:169 Whitelisted Namespaces: [kube-system]
```
It seems that the security that automatically adds the namespace of the configmaps to the withlist if it is not in the config list at controller level would **actually overwrite the whitelisted namespace list instead of adding this namespace to the allowed list**.

We can even say that!  
Because if we add the namespaces of the configmaps in the controller configuration we get the desired behavior

`--namespace-whitelist=rec --namespace-whitelist=test --namespace-whitelist=kube-system --configmap=kube-system/hap-rec-cm`

Log: 

```
2021/05/04 13:00:07 INFO monitor.go:169 Whitelisted Namespaces: [ rec ep-system kube-system]
```
----- 

I think we are facing this exception because our ingress controller deployments are not in the same namespaces as the pods they serve so we don't need to whitelist the namespace of the configmap of the ingress controller because there is no ingress ressource to listen in this namespace.

I hope this analysis can help you.

**Comment by Mo3m3n** [comment]
Released in `1.6.1`
