### ISSUE TITLE
how to accept `proxy-protocol` on the Ingress controller

### ISSUE THREAD

**Issue by eslam-gomaa** [haproxytech/kubernetes-ingress#314]
My Case is that I have an `external Load balancer (HAProxy)` in TCP Mode ---->  `HAProxy Ingress controller`

since it's operating in TCP mode, the way to send client IP is by enabling the `proxy-protocol`

* The ingress controller already has an option to send the `proxy protocols` to backend pods
* But There must be an option on the `HAProxy Ingress controller` to accept the `proxy-protocol` from a different proxy

---

The result of what I'm asking for is as follows  (adding the keyword `accept-proxy`) to bind

![image](https://user-images.githubusercontent.com/33789516/118245051-94d9c980-b4a0-11eb-8d98-c8023a6630ab.png)

I've tested it by adding it to the Ingress controller configurations manually and worked 😃 

---

***The question***: How to configure the `HAProxy Ingress controller` to accept the `proxy-protocol` from a different proxy ?

**Comment by prometherion** [comment]
Hi @eslam-gomaa, did you take a look at [this ConfigMap option](https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/#proxy-protocol)?

You can also set a 0.0.0.0/0 CIDR block to accept any connection.

Just a remark: proxy protocol can be enabled only for [HTTP and HTTPS (as well SSL in case of passthrough)](https://github.com/haproxytech/kubernetes-ingress/blob/d2930f578c28b1eba345a68609d8225aa631d11c/controller/handler/proxy-protocol.go#L56-L59).

**Comment by eslam-gomaa** [comment]
Thank you @prometherion for your reply 

I've already tried that before with the IP of the reverse proxy and tried it now with 0.0.0.0/0 cider as you advised, but still doesn't work

![image](https://user-images.githubusercontent.com/33789516/118263238-4cc5a180-b4b6-11eb-9858-c3dc062a0b59.png)

![image](https://user-images.githubusercontent.com/33789516/118267404-505c2700-b4bc-11eb-9abe-092b6f179ad5.png)

**Comment by Mo3m3n** [comment]
@eslam-gomaa Can you enable HAProxy logs (you can send them to stdout) as described [here](https://www.haproxy.com/blog/logging-with-the-haproxy-kubernetes-ingress-controller/#haproxy-logs) and provide the traffic logs corresponding to "400 bad request"

**Comment by Mo3m3n** [comment]
Also "400 bad request" is probably about the client not sending Proxy Protocol info in the request.
In addition to the logs can you also provide the generated haproxy.cfg: `kubectl exec -it $POD cat /etc/haproxy/haproxy.cfg`

**Comment by eslam-gomaa** [comment]
### First, That's the External Load balancer config

(Just testing with the stats page for starters)

![image](https://user-images.githubusercontent.com/33789516/118287549-d6379c80-b4d3-11eb-855a-c2a1d472445e.png)

---

### Logs

I found this one 😅 but don't understand why

![image](https://user-images.githubusercontent.com/33789516/118288349-a210ab80-b4d4-11eb-9972-24a8901f717d.png)

---

### config

```
# _version=11
# HAProxy Technologies
# https://www.haproxy.com/
# this file is not meant to be changed directly
# it is under haproxy ingress controller management

global
  localpeer local
  master-worker
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy-runtime-api.sock level admin expose-fd listeners
  stats timeout 1m
  tune.ssl.default-dh-param 2048
  ssl-default-bind-options no-sslv3 no-tls-tickets no-tlsv10
  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
  log stdout format raw daemon
  server-state-file global
  server-state-base /var/state/haproxy/

defaults
  log global
  log-format '%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs "%HM %[var(txn.base)] %HV"'
  option redispatch
  option dontlognull
  option http-keep-alive
  timeout http-request 5s
  timeout connect 5s
  timeout client 50s
  timeout queue 5s
  timeout server 50s
  timeout tunnel 1h
  timeout http-keep-alive 1m
  load-server-state-from-file global

peers localinstance
  peer local 127.0.0.1:10000

frontend healthz
  mode http
  bind 0.0.0.0:1042 name v4
  bind :::1042 name v6 v4v6
  monitor-uri /healthz
  option dontlog-normal

frontend http
  mode http
  bind 0.0.0.0:80 name v4
  bind :::80 name v6
  tcp-request connection expect-proxy layer4 if { src -f /etc/haproxy/maps/proxy-protocol-827c05ecc804eacf23a63899ca0ffcf6.map }
  http-request set-var(txn.base) base
  http-request set-var(txn.path) path
  http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
  http-request set-var(txn.host_match) var(txn.host),map(/etc/haproxy/maps/host.map)
  http-request set-var(txn.host_match) var(txn.host),regsub(^[^.]*,,),map(/etc/haproxy/maps/host.map,'') if !{ var(txn.host_match) -m found }
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map(/etc/haproxy/maps/path-exact.map)
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map_beg(/etc/haproxy/maps/path-prefix.map) if !{ var(txn.path_match) -m found }
  http-request replace-path (.*) / if { var(txn.path_match) -m dom 43b315f758eafb40dea2961a0801639d }
  use_backend %[var(txn.path_match),field(1,.)]
  default_backend kube-system-haproxy-kubernetes-ingress-default-backend-http

frontend https
  mode http
  bind 0.0.0.0:443 name v4 crt /etc/haproxy/certs/frontend ssl alpn h2,http/1.1
  bind :::443 name v6 crt /etc/haproxy/certs/frontend ssl alpn h2,http/1.1
  tcp-request connection expect-proxy layer4 if { src -f /etc/haproxy/maps/proxy-protocol-827c05ecc804eacf23a63899ca0ffcf6.map }
  http-request set-var(txn.base) base
  http-request set-var(txn.path) path
  http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
  http-request set-var(txn.host_match) var(txn.host),map(/etc/haproxy/maps/host.map)
  http-request set-var(txn.host_match) var(txn.host),regsub(^[^.]*,,),map(/etc/haproxy/maps/host.map,'') if !{ var(txn.host_match) -m found }
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map(/etc/haproxy/maps/path-exact.map)
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map_beg(/etc/haproxy/maps/path-prefix.map) if !{ var(txn.path_match) -m found }
  http-request set-header X-Forwarded-Proto https
  http-request replace-path (.*) / if { var(txn.path_match) -m dom 43b315f758eafb40dea2961a0801639d }
  use_backend %[var(txn.path_match),field(1,.)]
  default_backend kube-system-haproxy-kubernetes-ingress-default-backend-http

frontend stats
  mode http
  bind *:1024
  bind :::1024 name v6
  stats enable
  stats uri /
  stats refresh 10s
  http-request set-var(txn.base) base
  http-request use-service prometheus-exporter if { path /metrics }

frontend tcp-90
  mode tcp
  bind 0.0.0.0:90 name v4
  bind :::90 name v6 v4v6
  option tcplog
  default_backend default-echo-service-http

backend default-echo-service-http
  mode tcp
  balance leastconn
  server SRV_1 10.244.3.194:8080 check weight 128 send-proxy

backend default-wordpress-2-80
  mode http
  balance roundrobin
  option forwardfor
  server SRV_1 10.244.2.77:80 check weight 128 send-proxy
  server SRV_2 10.244.2.96:80 check weight 128 send-proxy
  server SRV_3 10.244.3.165:80 check weight 128 send-proxy
  server SRV_4 10.244.3.195:80 check weight 128 send-proxy

backend grafana-my-grafana-service
  mode http
  balance roundrobin
  option forwardfor
  server SRV_1 10.244.3.208:3000 check weight 128 send-proxy

backend kube-system-haproxy-kubernetes-ingress-default-backend-http
  mode http
  balance roundrobin
  option forwardfor
  server SRV_1 10.244.2.94:8080 check weight 128 send-proxy
  server SRV_2 10.244.3.192:8080 check weight 128 send-proxy

backend monitoring-prometheus-grafana-service
  mode http
  balance roundrobin
  option forwardfor
  server SRV_1 10.244.2.62:3000 check weight 128 send-proxy

```

**Comment by Mo3m3n** [comment]
@eslam-gomaa  the log message is quite straight forward,  a PROXY protocol header was not found in a connection were HAProxy was expecting one.

**Comment by eslam-gomaa** [comment]
@Mo3m3n Please check the first picture in last answer, ***the external LB is configured to send the `proxy-protocol`***

![image](https://user-images.githubusercontent.com/33789516/118511614-5eb37880-b732-11eb-8cb9-74ac4ffcd0d1.png)

---

Moreover I did a manual test and worked !

* I logged in to the ingress controller pod
  * Edited the config file to add the keyword `accept-proxy` after the bind directive -- [Reference](https://stackoverflow.com/a/50428423)

and it worked !!

##### Also tried both versions of the protocol `proxy-protocol-v1` and `proxy-protocol-v2`

**Comment by eslam-gomaa** [comment]
Hello @Mo3m3n 

***Not yet***, and please allow me to reform the the question 

##### How to configure `HAProxy ingress controller` to accept the proxy protocol, so that the HAProxy configuration is affected by adding `accept-proxy` after `bind` directives ❓❗

**Comment by Mo3m3n** [comment]
You will need to use [proxy-protocol](https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/#proxy-protocol) annotation, can you do that and check that you have `accept-proxy` in the bind lines of http frontends?

**Comment by eslam-gomaa** [comment]
Still not working, please tell me if i'm doing something wrong

---

Here is the `configmap`

![image](https://user-images.githubusercontent.com/33789516/119838682-e56f0f00-bf03-11eb-8f61-b79f1b73c44f.png)

---

The config

![image](https://user-images.githubusercontent.com/33789516/119839115-367f0300-bf04-11eb-97d9-dd08f24d16d7.png)

**Comment by Mo3m3n** [comment]
Sorry @eslam-gomaa 
It is not the `accept-proxy` keyword that you should be looking for but rather this directive:
```
tcp-request connection expect-proxy <pattern-file>
```
Basically it is the same, but expect-proxy allows for more fine grained setting as explained in the [accpet-proxy](https://www.haproxy.com/documentation/hapee/2-3r1/onepage/#5.1-accept-proxy) doc (end of paragraph)
If you have that directive in your config then proxy-protocol is enabled for the list of  ips in the pattern file.

**Comment by eslam-gomaa** [comment]
Thank you @Mo3m3n 

It accepts the proxy for the `http` and `https` frontends only and I was testing with the stats page 😅 , Thanks for the tip

![image](https://user-images.githubusercontent.com/33789516/119901210-e759c200-bf45-11eb-8f28-bcdb7ac164fa.png)

**Comment by Mo3m3n** [comment]
You're welcome.
By the way, if you want any thing specific in the stats frontend, you can have a look to [stats-config-snippet](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#config-snippet)
