### ISSUE TITLE
Feature request: OpenTracing

### ISSUE THREAD

**Issue by franklinkim** [haproxytech/kubernetes-ingress#329]
Hi guys,

wanted to ask if there are any plans to support OpenTracing as announced [here](https://www.haproxy.com/blog/announcing-haproxy-2-3/#opentracing-spoe)? 

Looking at the code you're currently building from [haproxytech/haproxy-alpine:2.3](https://github.com/haproxytech/kubernetes-ingress/blob/0b71f11cbcc9e72b885357c84d4cbd5f520b787f/build/Dockerfile#L39) which builds without the `USE_OT=1` flag so you can't configure frontend with sth like:

```
frontend ... 
  ...
  filter opentracing id ot-test-ctx config ctx/ot.cfg
  ...
```

Would be great if open tracing could be easily enabled through the helm-charts without adding custom volume mounts for `ot.cfg` and `cfg-jaeger.yml`.

**Comment by dkorunic** [comment]
@franklinkim As much as we would like to add it, problem here is that prerequisites for building this are quite heavy and not really Docker image friendly, ie. https://github.com/haproxytech/opentracing-c-wrapper and all dependancies required. This would make a default Docker image somewhat bigger for everyone, let alone a much more complex build as well as much more error-prone.
Sadly, I have to mark this as no-go.

**Comment by mateuszdrab** [comment]
Could this be potentially re-evaluated?
Tracing is supported in the Nginx Ingress Controller.

I don't quite understand how adding the plugin would significantly affect the controller image size - a build container can be leveraged to build the plugin and artifact can be copied out. Isn't the plugin going to just be a single file - a library?

**Comment by dkorunic** [comment]
@mateuszdrab This is more challenging than you would expect. This requires HAProxy CE base images to have already precompiled OpenTracing C Wrapper which in return requires for instance Jaeger SDK, Hunter and various other dependancies. This precompiled OT wrapper and Jaeger SDK and everything else required has to be compiled for Debian, Alpine and Ubuntu base images (for their respective base images) for 386, amd64, arm/v6, arm/v7, arm64 platform flavours.
While we can precompile this libraries in advance (and use such libraries in multi-stage Docker builds), it is still quite a lot of builds that *have* to work to be able to proceed with OT compiles and this images have to be recompiled each time we upgrade HAProxy CE base images. What's  even worse, some of this tracing plugins have various stability issues depending on distro (for instance Alpine) used and/or platform, making a single, uniform and stable solution that works for everyone almost impossible -- and have in mind that Docker image build issues in such complex layout could also impact future HAProxy CE release builds which are very popular.
On top of all this potential issues, there is very little interest in OT and we rarely get any such requests so there is a question if its worth the time and effort (and increased build complexity).

**Comment by bedis** [comment]
I confirm that OpenTracing is obsolete as a project. So we won't spend time on it.
That said, OpenTracing has been replaced by opentelemetry and this may something we could consider if that makes sense. But this is more an HAProxy issue for now.

**Comment by mateuszdrab** [comment]
That is also true, I just bucketed it all under the same umbrella but you're right, OpenTracing is a no-go atm.
Hopefully, OpenTelemetry can be implemented at some point since it can drive metrics as well...
