### ISSUE TITLE
Porting from /jcmoraisjr/haproxy-ingress no-tls-redirect-locations or similar annotation

### ISSUE THREAD

**Issue by alexcpn** [haproxytech/kubernetes-ingress#341]
Is there a configuration like `ingress.kubernetes.io/no-tls-redirect-locations`  in Haporxytech ingress controller to support LetsEncrypt certificate generation

See https://github.com/jcmoraisjr/haproxy-ingress/issues/160

**Comment by ivanmatmati** [comment]
Hi @alexcpn , currently there's no support for LetsEncrypt but could be an enhancement.

**Comment by oktalz** [comment]
Hi @alexcpn, 
maybe its not exactly what you were asking, but
there is a way to use lets-encrypt with our ingress controller: https://www.haproxy.com/blog/enable-tls-with-lets-encrypt-and-the-haproxy-kubernetes-ingress-controller/

**Comment by alexcpn** [comment]
thanks @oktalz @imatmati  for the response

**Comment by Mo3m3n** [comment]
@alexcpn did the link shared below answer your requirement ?

**Comment by alexcpn** [comment]
@Mo3m3n this is a manual way of doing. What we wanted in haporxytech is similar feature parity to the annotation given by jcmoraisjr/haproxy-ingress. reason https://github.com/kubernetes/ingress-nginx/pull/2203. I will ask my team members to comment here

**Comment by pramod0310** [comment]
@Mo3m3n  This was required for us since we want to rotate the certs automatically using the cert-manager as in those cases else we may have to change the annotations manually to temporarily open for port 80..
