### ISSUE TITLE
Exposing TCP and UDP services

### ISSUE THREAD

**Issue by MaxHorstmann** [haproxytech/kubernetes-ingress#342]
Kubernetes Ingress does not support exposing TCP/UDP services, but NGINX Ingress Controller provides a [workaround](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services) for that.

Does a similar workaround exist for HAProxy?

Related: [Exposing multiple TCP/UDP services using a single LoadBalancer on K8s](https://stackoverflow.com/questions/61430311/exposing-multiple-tcp-udp-services-using-a-single-loadbalancer-on-k8s)

**Comment by daniel-corbett** [comment]
What kind of UDP services are you interested in exposing? HAProxy does not support generic UDP but has been working on supporting UDP for specific protocols where it can add value. For example, in HAProxy 2.3 [1] support was added for incoming Syslog over UDP and TCP.

[1] https://www.haproxy.com/blog/announcing-haproxy-2-3/#syslog-protocol-udp-tcp

**Comment by MaxHorstmann** [comment]
Not specifically interested in UDP, just included it because NGINX talks about both TCP/UDP on the linked page. 

Interested in exposing TCP services such as SSH.

**Comment by oktalz** [comment]
Hi @MaxHorstmann 
for UDP, @daniel-corbett  has already explained it.
for TCP services you can use custom config-map with predefined format: [doc.yaml](https://github.com/haproxytech/kubernetes-ingress/blob/d10c41fb9e7a95322427208b780633797c2e9d8c/documentation/doc.yaml#L12)

**Comment by MaxHorstmann** [comment]
Awesome, thank you!
