### ISSUE TITLE
(Multiple ingress same node) vs (stats port 1024 and healthz port 1042 )

### ISSUE THREAD

**Issue by zbebeto** [haproxytech/kubernetes-ingress#348]
The network mode of ingress in this scenario is : useHostNetwork: true
The stats port 1024 and healthz port 1042 are binding in ip 0.0.0.0 ...  so if  I have more than one ingress controller in the same node it does not work ...
How can I bind the stats port and healthz port to an specific ip ? (just like the http and https ports)
I realized that there is a third uncontrolled port  : 127.0.0.1: 10000
So this 3 ports (0.0.0.0:1024 0.0.0.0:1042 127.0.0.1:10000) do  not allow multiple ingress in  the same nodes with useHostNetwork: true.
The nginx  ingress controller allow this configuration. I was using it when I decided to migrate to haproxy.
Thanks  a lot in advance.

**Comment by ivanmatmati** [comment]
Can you describe what went wrong and version you use ? FYI, I could scale the controller to multiple instances  in latest version.
