### ISSUE TITLE
Trouble with SSL termination 

### ISSUE THREAD

**Issue by ganasubrgit** [haproxytech/kubernetes-ingress#353]
Greetings!

I'm trying to setup the following,

Client=>HAproxy-Ingress SSL (https://example.com) =>K8s externalservice to Backend AWS ECR SSL (https://54656778.dkr.ecr.us-east-1.amazonaws.com)

I'm having trouble connecting to a SSL enabled app endpoint via SSL enabled HAproxy ingress-controller.
If I add annotation for passthought it works but thoughts SSL error on cert name.
not sure how to configure this right using haproxy ingress.

curl https://ecr.dev.glip.net/
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

**Comment by ivanmatmati** [comment]
Hi  @ganasubrgit , please ask question on forums or slack [here](https://slack.haproxy.org/)
