### ISSUE TITLE
Configure spoa filter

### ISSUE THREAD

**Issue by git001** [haproxytech/kubernetes-ingress#357]
I haven't found a option to add a spoa filter into he ingress, is this possible with the current version?
I try to create something similar like this setup with openpolicyagent and haproxy.
https://spiffe.io/docs/latest/microservices/envoy-jwt-opa/readme/

**Comment by ivanmatmati** [comment]
You can try to inject any unmanaged feature in Ingress Controller with config snippet and auxiliary config file.

**Comment by Mo3m3n** [comment]
I have added the documentation label, so we can work on a documentation example on how to use spoa filter with IC

**Comment by git001** [comment]
thank you

**Comment by mecampbellsoup** [comment]
@Mo3m3n did you guys produce any docs for this? 😄

**Comment by Mo3m3n** [comment]
@mecampbellsoup I left the project a while ago.
When I did there was no doc yet for this example, maybe if you try to connect with the team and see if this has changed.

**Comment by oktalz** [comment]
@mecampbellsoup you can look at [extending haproxy with the stream processing offload engine](https://www.haproxy.com/blog/extending-haproxy-with-the-stream-processing-offload-engine/) blog post

Blog explains what need to be added in frontend config snippet and auxiliary file. There are many use cases and there you can even find examples how to write SPOA agent in multiple languages

**Comment by mecampbellsoup** [comment]
i'm curious if anyone has an example of using a SPOA alongside haproxy, and if so how they setup the k8s deployments/helm charts to run them together?
