### ISSUE TITLE
Deployment and Daemonset update to HAProxy 2.4

### ISSUE THREAD

**Issue by git001** [haproxytech/kubernetes-ingress#358]
I have installed today the latest haproxy ingress via helm chart and have seen that the used HAProxy is `HAProxy version 2.3.12-b99e499, released 2021/07/08` any chance to upgrade it to 2.4?

**Comment by oktalz** [comment]
hi @git001 
our nightly docker image already is on 2.4, 
but upgrading HAProxy on stable branch is being done only in `minor` version changes, so 
2.4 will be available in 1.7 version of ingress controller and 1.6 will remain on 2.3 version of HAProxy
