### ISSUE TITLE
global config map settings are not applied to the default backend

### ISSUE THREAD

**Issue by nbraun-wolf** [haproxytech/kubernetes-ingress#360]
Hi , I noticed that none of the settings from the [global config map](https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/) are applied to the [default backend](https://www.haproxy.com/documentation/kubernetes/latest/configuration/controller/#--default-backend-service). 

It would be useful if the configuration also applied to that service like any other service.  For example SSL redirect or IP whitelisting.

The currently deployed tag is[ 1.6.6](https://hub.docker.com/layers/haproxytech/kubernetes-ingress/1.6.6/images/sha256-84d0d49940e389c3e6f620fbb659f2a083420a09d608bf9758b18ae125bf69fc?context=explore).

**Comment by oktalz** [comment]
The default backend is a service which handles all URL paths and catches requests that are not mapped with an Ingress.
default backend exposes two URLs:
    /healthz that returns 200
    / that returns 404

so there is really no need for applying any settings to it.

Yes, you can put any service there, but per ingress definition this is not by standard.
Currently there are no plans to support this behavior.
