### ISSUE TITLE
Feature Request: Creating stick-table backends

### ISSUE THREAD

**Issue by nick-bob** [haproxytech/kubernetes-ingress#365]
Hi everyone,

I mentioned this over at the [helm-charts repo](https://github.com/haproxytech/helm-charts/issues/100#issue-981346715) but I think this is probably the more appropriate place to make this request.

I'm trying to create two different stick-tables to track POST vs GET requests, then apply different rates request-limits for each.

I don't really see a way to do that with the current set of rate-limiting configs from the "kubernetes layer" of configs. Currently I'm trying to create the config with the backend-config-snippet. But I don't know how I'll be able to refer to two different tables in the same backend. My current annotation:

```
backend-config-snippet: |
      stick-table type ip size 102400 store http_req_rate(1000)
      http-request track-sc0 src if METH_HEAD
      http-request deny deny_status 429 if { sc_http_req_rate(0) gt 10 }
```

Thanks for any help or suggestions.

**Comment by Mo3m3n** [comment]
Hi @nick-bob 
This is something that the [auxCfg](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/secondary-config.md) is supposed to handle.
However there is an issue currently about having cross reference config between main and aux cfg, we are currently fixing this and will get back to you this week with the appropriate solution

**Comment by oktalz** [comment]
changes are already implemented in underlying packages (today), so the update in ingress controller should happen soon
