### ISSUE TITLE
Namespace whitelist and ingress class are ignored

### ISSUE THREAD

**Issue by kriscode1** [haproxytech/kubernetes-ingress#366]
[v1.6.6](https://github.com/haproxytech/kubernetes-ingress/compare/v1.6.5...v1.6.6) introduced a bug where all ingresses in the cluster will have their address updated when the ingress controller service address changes.

Steps to reproduce:
1. deploy with `--namespace-whitelist` and `--ingress.class` args
2. create an ingress in a non-whitelisted namespace without the correct ingress class
3. confirm the ingress does not have an address set
4. manually edit the external IP of the kubernetes ingress controller service
5. logs will print "Addresses of Ingress Controller service changed, status of all ingress resources are going to be updated"
6. view the ingress address again, the address will be incorrectly set

**Comment by cbajumpaa** [comment]
This [commit](https://github.com/haproxytech/kubernetes-ingress/commit/3dc3c4ffde6057e44231ca460cc8162b317aaa78) appears to be the one which causes this bug.

**Comment by cbajumpaa** [comment]
It would appear to be the call to `status.UpdateIngress` in `Start` in `controller/controller.go`.

Particularly `status.UpdateIngress` isn't checking the namespace whitelist or blacklist. Nor is it verifying ingress.class.

**Comment by ivanmatmati** [comment]
Hi @cbajumpaa , can you check it's fixed with latest version 1.7.1 ?

**Comment by cbajumpaa** [comment]
This is working for me now.
