### ISSUE TITLE
Ingress is not working in Minikube

### ISSUE THREAD

**Issue by Tolga-Karahan** [haproxytech/kubernetes-ingress#372]
We're considering to use haproxy in a deployment of the company that I'm working in, so in order to learn it better I found some examples and tried somethings, but I couldn't manage to run it properly.

I installed haproxy ingress controller via Helm and got these components when I entered kubectl get pods and kubectl get svc commands:

`haproxy-ingress-kubernetes-ingress-d5fb97dfc-45lgv                1/1     Running   0          4h54m `
`haproxy-ingress-kubernetes-ingress-d5fb97dfc-jsk8v                1/1     Running   0          4h54m`
`haproxy-ingress-kubernetes-ingress-default-backend-5454996p9qrx   1/1     Running   0          4h54m`

`haproxy-ingress-kubernetes-ingress                   NodePort    10.99.199.229    <none>        80:31900/TCP,443:32240/TCP,1024:32389/TCP   4h56m
`
`haproxy-ingress-kubernetes-ingress-default-backend   ClusterIP   None             <none>        8080/TCP                                    4h56m`

Then I deployed these yaml files:

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: echo
  template:
    metadata:
      labels:
        run: echo
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
    name: echo-service
    annotations:
      haproxy.org/forwarded-for: "enabled"
spec:
    selector:
      run: echo
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: echo-ingress
    #annotations:
        #haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-service
            port:
              number: 80  

Then I added foo.bar to /etc/hosts file with the IP address of $(minikube IP), but when I typed foo.bar/ to browser just got unable to connect.

**Comment by NickMRamirez** [comment]
Version 1.6 requires the `kubernetes.io/ingress.class: haproxy` annotation on the Ingress. This is a new requirement. Maybe it's that? I'll be updating the documentation soon to say this.

**Comment by Tolga-Karahan** [comment]
@NickMRamirez , after adding this annotation Ingress is able to catch IP address of the Haproxy controller's NodePort:
NAME           CLASS    HOSTS     ADDRESS        PORTS   AGE
echo-ingress   <none>   foo.bar   10.98.208.76   80      3m52s

I added an entry for this ip address and foo.bar domain to the /etc/hosts as below, but when I type foo.var to browser it is not working:

10.98.208.76 foo.bar

**Comment by NickMRamirez** [comment]
It is not mandatory. The ingress controller will watch for Ingress resources defined in any and all namespaces, although it will only use them if the Ingress has specified `ingress.class: haproxy`. You can disable this behavior when you install the controller by setting `--set controller.ingressClass=null` when calling `helm install`.

It is possible to have it watch only a certain namespace. Read this blog post, which explains how to do it using the `--namespace-whitelist` controller argument. https://www.haproxy.com/blog/multi-tenant-kubernetes-clusters-with-the-haproxy-kubernetes-ingress-controller/ That would allow you to run, for example, a controller per namespace.

**Comment by Tolga-Karahan** [comment]
@NickMRamirez, great. Thanks!
