### ISSUE TITLE
Change deployment YAML files to be consistent with Helm chart

### ISSUE THREAD

**Issue by NickMRamirez** [haproxytech/kubernetes-ingress#382]
The Helm chart creates objects that have different names and are in a different namespace that how the YAML files in the "deploy" folder do it. We should update the YAML files to match the Helm chart.

| Field          | Helm chart | haproxy-ingress.yaml |
|------------|------------|------------------------|
| namespace | default     | haproxy-controller       |
| ConfigMap name | kubernetes-ingress | haproxy |
| ServiceAccount name | kubernetes-ingress | haproxy-ingress-service-account |
| Default service name | kubernetes-ingress-default-backend | ingress-default-backend |
| Service name | kubernetes-ingress | haproxy-ingress |

Or, should the Helm chart change? It doesn't say "haproxy" very often in its naming.

**Comment by Mo3m3n** [comment]
@NickMRamirez We are going to update the name of deployed resources to match Helm which are more consistent.
So we will  substitute "haproxy" for the "helm release-name" which going to result in "haproxy-kubernetes-ingress" for the reported resources.
However we will keep the "haproxy-controller" as namespace it is tidier than deploying in default namespace where user can already have a mix of resources. Helm users do have the ability to install resources in a dedicated NS.

**Comment by NickMRamirez** [comment]
From a consistency standpoint (such as in the examples we show in the documentation, where the namespace is shown), it is better if everything is the same across the board. If putting the resources into a named namespace is better, I recommend updating the Helm chart to do that too.

**Comment by Mo3m3n** [comment]
Another possibility would be to update the doc in order to use a dedicated namespace with helm like we do in our deployment files, so this amounts to appending `--namespace haproxy-controller` in the docs. 
I think this is safer than trying to update the default ns used in helm or in the deploy files as there may be users already using these default behaviors (both in helm and deploy files).

**Comment by dkorunic** [comment]
@NickMRamirez Helm Charts by default can use any namespace that customers provide and all our resources and parameters have been templated so that the customer can use any namespace he provides without any problems.

**Comment by NickMRamirez** [comment]
In that case, it could be better to make the YAML deployment files (instead of the Helm chart) consistent with that, by making them deploy the ingress conroller to the _default_ namespace. This change should not have a big impact because the IC watches resouces in all namespaces or can be configured to watch a specific namespace, but the namespace in which it runs is less consequential. But making it consistent is worthwhile for showing examples in the documentation.

**Comment by Mo3m3n** [comment]
This was handled in 6f75288dce213c2873cafa435cbfbaa10d861ba1 and  5eace9593e1be052d225131a37baef6e4b3c32b2
