### ISSUE TITLE
1.7 version broke proxy-protocol IP filtering

### ISSUE THREAD

**Issue by gtrubach** [haproxytech/kubernetes-ingress#388]
Hello,

I'm running HAProxy ingress through Helm chart in Kubernetes. And I see one problem with proxy protocol:

* In 1.6.7 version `expect-proxy` is generated like below
  ```
  tcp-request connection expect-proxy layer4 if { src -f /etc/haproxy/maps/proxy-protocol-ebb075b84270e946b0a45b78f29871dd.map }
  ```
* In 1.7.0 version  `expect-proxy` is generated like below
  ```
  tcp-request connection expect-proxy layer4
  ```

So statement misses if condition in latest controller.

I put proxy-protocol into config map.

**Comment by Mo3m3n** [comment]
Fixed in `haproxytech/kubernetes-ingress:1.7.1`
