### ISSUE TITLE
possible to use haproxy ingress external mode as an overall service router?

### ISSUE THREAD

**Issue by husa570** [haproxytech/kubernetes-ingress#395]
Hi.
Use case
Several kubernetes klusters with its own ingress controller.
Klusters have some ingress with overlapping hostname and context.
**For example**
K8s-c1 (consist of worker k8s-c1-w1,k8s-c1-w2 and k8s-c1-w3)
mydomain.com/app1
mydomain.com/app2
subdomain1.mydomain.com/app1
K8s-c2 (consist of worker k8s-c2-w1,k8s-c2-w2 and k8s-c2-w3)
mydomain.com
mydomain.com/app1
subdomain1.mydomain.com/app1
subdomain1.mydomain.com/app2

As I understand the docs Its not possible to use the node name/IP or a label on the ingress as the backend server when using the ingress in external mode.

If the ingress can read the host and context from ingress and route that to the right cluster then haproxy could be a general service router.
The backend name could be the nodes or just the possibility to use a label in the ingress, that would with the example above resault in a backend config: 

For host/context
mydomain.com backend servers
k8s-c2-w1,k8s-c2-w2 and k8s-c2-w3

mydomain.com/app1 backend servers
k8s-c1-w1,k8s-c1-w2 and k8s-c1-w3
k8s-c2-w1,k8s-c2-w2 and k8s-c2-w3

mydomain.com/app2 backend servers
k8s-c1-w1,k8s-c1-w2 and k8s-c1-w3

subdomain1.mydomain.com/app1 backend servers
k8s-c1-w1,k8s-c1-w2 and k8s-c1-w3
k8s-c2-w1,k8s-c2-w2 and k8s-c2-w3

subdomain1.mydomain.com/app2 backend servers
k8s-c2-w1,k8s-c2-w2 and k8s-c2-w3

Is that possible with the ingresscontroller in external mode today?

**Comment by Mo3m3n** [comment]
Hi
> If the ingress can read the host and context from ingress and route that to the right cluster then haproxy could be a general service router.

The above is not clear, cause to be able to read from an ingress resource then you should be already running inside a k8s cluster, but at the same time you want the Ingress Controller to be an overall service router. So I don't exactly get your requirement here.

**Comment by husa570** [comment]
`The above is not clear, cause to be able to read from an ingress resource then you should be already running inside a k8s cluster, but at the same time you want the Ingress Controller to be an overall service router.`
There is no problem to access the API-server from outside a kubernetes cluster, for example the same ways as kubectl works.

I try to explain the usecase
Today we use HAproxy as a external loadbalancer for our K8s master and the worker nodes, in the worker we have a ingress deployed as daemonset. A very vanilla setup.
Every cluster has its own HAproxy as external loadbalancer.

The consequence of that setup are that every context under a DNS name have to be deployed in the same K8s cluster, since the DNS name point to that loadbalacing HAproxy.

mydomain.org/context1 -> Cluster 1
mydomain.org/context2 -> Cluster 1
mydomain.org/context3 -> Cluster 1

If Haproxy could read the ingresses from different API-server and K8s cluster and update the config it would be possible to have one instance of HAproxy to loadbalance traffic to workers that belongs to separate K8s cluster.

mydomain.org/context1 -> Cluster 1
mydomain.org/context2 -> Cluster 2
mydomain.org/context3 -> Cluster 3

[Inspiration from traefik.io/traefik proxy](https://traefik.io/traefik/)

**Comment by Mo3m3n** [comment]
>  There is no problem to access the API-server from outside a kubernetes cluster, for example the same ways as kubectl works.

Right, I should have rather said, you should be already connected to a k8s cluster 

> The consequence of that setup are that every context under a DNS name have to be deployed in the same K8s cluster, since the DNS name point to that loadbalacing HAproxy.

Still not clear, I guess by a "context"  you mean the path, no? and also I don't understand what deploying a context means, maybe you're referring to the ingress resource.
>If Haproxy could read the ingresses from different API-server and K8s cluster and update the config it would be possible to have one instance of HAproxy to loadbalance traffic to workers that belongs to separate K8s cluster.

It is possible to connect to a different cluster and read its ingress resources, but it is not clear how to know which cluster requests should be routed to .
In case it would be easier, we can talk about this in our #ingress-controller channel in  [slack](https://slack.haproxy.org/)

**Comment by ivanmatmati** [comment]
Hi @husa570 , external mode is nothing more than running the ingress controller from outside the k8s cluster and it still connects to one and single one cluster (api server). Considering the current functioning the best approaching design I can see (but still not feasible now) is to have a cluster where services of ingresses are without selector  and are mapped in any way to reach the external clusters.
