### ISSUE TITLE
HAProxy ingress seems to open and expose port 1024 statistics port by default on GCP

### ISSUE THREAD

**Issue by sniip-code** [haproxytech/kubernetes-ingress#397]
HAProxy ingress seems to open and expose port the 1024 statistics  port by default in GCP how do you disable this from being exposed on the external load balancer?

**Comment by ivanmatmati** [comment]
Hi @sniip-code, If you're using Helm for your cluster, you can disable ports with this [value](https://github.com/haproxytech/helm-charts/blob/48f59523c7c7cb51047184632ba93153c2c09f67/kubernetes-ingress/values.yaml#L347). If you're not using it, you can change the service manifest accordingly.
