### ISSUE TITLE
[Feature Request] Add extra annotation field for configmap in helm chart

### ISSUE THREAD

**Issue by ethernoy** [haproxytech/kubernetes-ingress#399]
HAProxy ingress controller currently loads configmap using Kubernetes API (`--configmap={{ .Release.Namespace }}/{{ template "kubernetes-ingress.fullname" . }}`). This causes an issue when installing HAProxy ingress controller using Spinnaker and the official helm chart: Spinnaker by default adds a version suffix to all secrets and configmaps in the manifests rendered by helm (e.g. `haproxy` to `haproxy-v000`), and modify the mounting of secrets and configmaps by adding the same suffix in order to implements its version control feature. HAProxy ingress controller will fail to load the configmap in this scenario as it does not use config mounting to load the configmap. Example screenshot attached below, note the inconsistency between configmap name and args reference:

Configmap:
![image](https://user-images.githubusercontent.com/15870761/144366557-7c5f2057-740c-45ec-9e89-37abe85469e4.png)

HAProxy pod args:
![image](https://user-images.githubusercontent.com/15870761/144366611-6a25e46d-650b-4dc6-b076-1eb937d05c97.png)

To tackle this issue, we can either:
- load configmap via volume mount (can somebody explain why this wasn't implemented? I believe this is more idiomatic compared to using Kubernetes API to load the configmap)
- allow adding extra annotation in helm chart. Spinnaker uses annotation to decide whether to add the suffix or not, we can leverage this annotation to remove the suffix from configmap.

Happy to submit PR if this is OK :)

**Comment by oktalz** [comment]
hi @ethernoy 
> load configmap via volume mount (can somebody explain why this wasn't implemented? I believe this is more idiomatic compared to using Kubernetes API to load the configmap)

adding volumes and watchers does not seem like an efficient solution. 

> allow adding extra annotation in helm chart. Spinnaker uses annotation to decide whether to add the suffix or not, we can leverage this annotation to remove the suffix from configmap.

this looks OK

> Happy to submit PR if this is OK :)

\o/ you can create a PR in [helm-charts](https://github.com/haproxytech/helm-charts)

**Comment by ethernoy** [comment]
@oktalz 

OK I will PR soon :)

> adding volumes and watchers does not seem like an efficient solution.

Meanwhile can you elaborate a bit more about this? I am very curious

**Comment by oktalz** [comment]
hi @ethernoy , 
Sorry for not answering your question sooner

> Meanwhile can you elaborate a bit more about this? I am very curious

main reason is unnecessary I/O - our configmap is not static, if you change it during run, controller will react to it, so that would mean monitoring of files, I say files since every key appears as a single file.

**Comment by ethernoy** [comment]
> hi @ethernoy , Sorry for not answering your question sooner
> 
> > Meanwhile can you elaborate a bit more about this? I am very curious
> 
> main reason is unnecessary I/O - our configmap is not static, if you change it during run, controller will react to it, so that would mean monitoring of files, I say files since every key appears as a single file.

Understood, thx for your kind explanation :)
