### ISSUE TITLE
ERROR   global.go:159 default service: service '/' does not exist

### ISSUE THREAD

**Issue by connatix-cradulescu** [haproxytech/kubernetes-ingress#411]
Hello,

I am seeing on kubernetes-ingress logs below error and I have no clue from where is coming.
Version  HAProxy Ingress Controller v1.7.3 faab78d
```
2022/01/03 13:44:48 ERROR   global.go:159 default service: service '/' does not exist
2022/01/03 13:45:18 ERROR   global.go:159 default service: service '/' does not exist
2022/01/03 13:45:23 ERROR   global.go:159 default service: service '/' does not exist
2022/01/03 13:45:43 ERROR   global.go:159 default service: service '/' does not exist
2022/01/03 13:45:53 ERROR   global.go:159 default service: service '/' does not exist
```

Any advice? 

Thank you!

**Comment by ivanmatmati** [comment]
Hi @connatix-cradulescu , do you have an ingress refering to a selectorless service ?

**Comment by connatix-cradulescu** [comment]
Hi @ivanmatmati. No ingress in the cluster. The cluster is newly deployed ( like 1h ago) and fresh haproxy ingress controller.  I have no ingress called "service"  on default ns, as haproxy complains.

**Comment by ivanmatmati** [comment]
By which method did you create your cluster ? What is the value of the controller argument default-backend-service ?

**Comment by connatix-cradulescu** [comment]
> 

Is an EKS AWS cluster and the defaultBacked disabled.

**Comment by ivanmatmati** [comment]
How did you disable it ?

**Comment by connatix-cradulescu** [comment]
```
## Default 404 backend
defaultBackend:
  enabled: false
  name: default-backend
  replicaCount: 2
```

**Comment by ivanmatmati** [comment]
Actually, this error message should be ignored. We'll probably skip it in a future release.It's the consequence of the absence of a default backend service specification which is perfectly correct.
