### ISSUE TITLE
Unreliable pod-maxconn behavior

### ISSUE THREAD

**Issue by hugorodrigues** [haproxytech/kubernetes-ingress#418]
When `pod-maxconn` is set to `10`, I see the following behavior:
- Session Limit (on Statistics Report): `2`
- Observed concurrent request inside pod: `4`

I was expecting to see a limit of `10` and observe a max of `10` concurrent connections inside the pod. Also, any `pod-maxconn` value lower than `4` is ignored.

I noticed the following notes in the documentation:
> NB, If multiple HAProxy instances are running, the maxconn will be pod-maxconn number devided by the number of haproxy instances.

But I only have 1 HAProxy instance running in the cluster.

### Tested versions (via helm):
- `1.19.0`
- `1.18.0`
- `1.17.9`

### Enviroment
- GKE
- 1.21.6-gke.1500

Am I missing something? Thanks in advance!

**Comment by ivanmatmati** [comment]
Hi @hugorodrigues , Can you check my fix in the latest master branch ?

**Comment by Mo3m3n** [comment]
This should be fixed in `v1.7.6`
Don't hesitate to reopen the issue if it is not the case.
