### ISSUE TITLE
Route to backend  

### ISSUE THREAD

**Issue by alexkayzer** [haproxytech/kubernetes-ingress#419]
Hi!I have two backends per host, I need to distribute requests between backends focusing only on the path. But only part of the way is known:
**/something/something/web/something else or empty**
**/something/something/maybe something else/tv/something else or empty/**
how to route it correctly?

**Comment by Mo3m3n** [comment]
@alexkayzer 
You can have a look to the official Ingress [documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/) especially the [path types](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) part.
