### ISSUE TITLE
ssl-redirect on gke does not seem to be working

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [haproxytech/kubernetes-ingress#42]
I tried all the locations and annotations to force the redirect, but cannot seem to make it run on v1.12.7-gke.25. Is there any known issue?

The version of the controller is 1.1.4

**Comment by Mo3m3n** [comment]
For future reference, the correct annotation here is [ssl-redirect](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#https)
