### ISSUE TITLE
Haproxy doesn't reload srv config after new deployment 

### ISSUE THREAD

**Issue by praveenk0535** [haproxytech/kubernetes-ingress#422]
We are seeing this on  ingress  rule which uses server side ssl. If we do a new deployment for the app it returns with error in the browser with  <<Bad Request - This combination of host and port requires TLS.>>. If I delete the ingress daemon set pods it works fine again .  Fixing the problem temporarily.

Ingress rule details:
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      haproxy.org/server-ssl: "true"
  spec:
    rules:
    - host: <<<FQDN>>>
      http:
        paths:
        - backend:
            service:
              name: service-name
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific

Version using : haproxytech/kubernetes-ingress:1.4.3

**Comment by Mo3m3n** [comment]
@praveenk0535 
Currently the last version is `1.7.5` can you give it a try and see if the issue persists ?
