### ISSUE TITLE
split configmap for errorfiles 

### ISSUE THREAD

**Issue by dosmanak** [haproxytech/kubernetes-ingress#423]
I've got errorfiles with inline CSS for each errorpage and the final configmap exceeded metatadata.annotation size.
It would be greate if I could configure `--configmap-errorfile500`, `--configmap-errorfile503` etc. to split data in several configmaps.
`--configmap-errorfiles` would be mutual exclusive with `--configmap-errorfile[0-9]{3}`.

Pleas evaluate if such /feature-request is feasable.

**Comment by dosmanak** [comment]
I did not realize the errorfile must be [16kB max](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-errorfile), so this issuse is invalid and I close it.

**Comment by Mo3m3n** [comment]
Yes they should not exceed the configured buffer size which is 16kB by default.
The default bufsize can be updated via [tune.bufsize](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.2-tune.bufsize).
