### ISSUE TITLE
Error: INSTALLATION FAILED: configmaps "kubernetes-ingress" already exists

### ISSUE THREAD

**Issue by mdbr000** [haproxytech/kubernetes-ingress#424]
I have a chart that references the official kubernetes-ingress chart (`~1.19.0`) as a dependency.  My parent chart is pretty simple; it defines custom controller values and a ConfigMap that overrides the default ConfigMap provided by the kubernetes-ingress chart.

The docs state that the default ConfigMap is created at installation and that this ConfigMap can be overwritten by applying your own ConfigMap with the same name.  The example in the docs uses kubectl to apply a custom ConfigMap (https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/)

Helm apparently has an issue with this the default ConfigMap.  When I try to install my chart that has the dependency with this command: `helm install test-ingress helm/test-ingress` I get this error:

`Error: INSTALLATION FAILED: configmaps "test-ingress-kubernetes-ingress" already exists`

Is there a workaround to this issue?  I need to have the installation of this chart completely automated and scriptable, with no required "post processing" with kubectl necessary in order to apply my custom ConfigMap settings to the installation.

Helm version: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}`

**Comment by Mo3m3n** [comment]
Hi @mdbr000 
If you think this is a Helm issue, then you may have the right answer if you ask the question here https://github.com/haproxytech/helm-charts

**Comment by mdbr000** [comment]
Hi @Mo3m3n, the Helm folks have suggested that I apply a post-install hook using a kubectl sidecar container, which may be the right solution...

However, I am wondering if there is a way to disable the creation of the ConfigMap in kubernetes-ingress so as not to run into this issue in the first place?  If the ConfigMap creation is disabled, there would be no naming contention and I would be able to apply my custom ConfigMap using the happy Helm path.  Or, is the initial ConfigMap creation absolutely required by kubernetes-ingress in order to function?

**Comment by Mo3m3n** [comment]
>The docs state that the default ConfigMap is created at installation and that this ConfigMap can be overwritten by applying your own ConfigMap with the same name.

To be more precise, the configmap is not created by the IC (Ingress Controller) but by the tool used to deploy the IC, which in your case is Helm.
So if you want to use your own configmap there are two easy options supported by our Helm Chart:
- Put your configmap content in in the [config value](https://github.com/haproxytech/helm-charts/blob/90ba5515e59b3f91738aa1d2f2dcc7228fca292f/kubernetes-ingress/values.yaml#L282) of the Chart: this will make Hem create the configmap based on the content you provide.
- Point the IC to your own configmap and you can do that via the [extraArgs value](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml#L275) of the Chart by adding an argument like: `--configmap=yourNS/yourConfigmap` where "yourNS/yourConfigmap" is a configmap you have already created.

**Comment by Mo3m3n** [comment]
Closing this since a solution was provided.

**Comment by mdbr000** [comment]
@Mo3m3n Excellent, I went with the option of just adding the values from my ConfigMap to the `controller.config` section of the chart via `values.yaml`. Works perfectly and much easier than doing a sidecar that injects values post deploy. Thanks!
