### ISSUE TITLE
SRV Check code: 405, info: "Method Not Allowed"

### ISSUE THREAD

**Issue by connatix-cradulescu** [haproxytech/kubernetes-ingress#429]
Hello,

I am using an svc headless and the haproxy SRV check fails with the below error:

```
[WARNING]  (819) : Server incubator-api-incubator-api-headless-http/SRV_1 is DOWN, reason: Layer7 wrong status, code: 405, info: "Method Not Allowed", check duration: 1ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING]  (819) : Server incubator-api-incubator-api-headless-http/SRV_2 is DOWN, reason: Layer7 wrong status, code: 405, info: "Method Not Allowed", check duration: 2ms. 0 active and 0 backup servers left. 
```

Using curl:

```
curl -I -X 'GET' 'http://incubator-api.ops.connatix.com/-/live' -H 'accept: text/plain'
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
date: Thu, 10 Mar 2022 16:00:38 GMT
server: Kestrel
transfer-encoding: chunked

```

My question is if ''accept: text/plain' is an issue for haproxy SRV check?

**Comment by Mo3m3n** [comment]
Hello
> My question is if ''accept: text/plain' is an issue for haproxy SRV check?

Actually that is the question we need to ask you :) 
 is the "accept" header mandatory?
 because the health checks wont' send it by default which looks more like the following curl request
`curl -X 'GET' 'http://incubator-api.ops.connatix.com/-/live'`

**Comment by Mo3m3n** [comment]
> I know the health check is done via httpGET but how is done SRV check?

We don't have something called "SRV check" the SRV you see in the logs is just the backend server name (SRV_1, SRV_2, etc)
So these checks are health checks sent to the backend servers.
By default health checks are just TCP checks (only establish a tcp connection)
But if you use [check-http](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#check-http) (which seems to be the case looking to the logs) haproxy will use http checks done by default via http get.
You can make a traffic capture to have a deeper look into the checks.

**Comment by connatix-cradulescu** [comment]
Hi @Mo3m3n. Everything is clear now!

Thank you so much!
