### ISSUE TITLE
feat: build Dockerfile from scratch

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [haproxytech/kubernetes-ingress#43]
A suggestion: as the image is security relevant (certs etc.) the Dockerfile should not include bash etc. Similarly dumb-init should be copied from builder.

Ref: https://hub.docker.com/_/scratch

**Comment by oktalz** [comment]
hi @eljefedelrodeodeljefe,

bash (and make) are already removed from image in last commit.
regarding dumb-init, than can be also moved to builder.

I would like to encourage you to create a pull request for that :)

**Comment by oktalz** [comment]
Hi, 
since I've removed bash, I'm closing this issue, 
after some thinking i do not see any benefit of moving dumb-init, it would not reduce number of layers in image.
