### ISSUE TITLE
Ingress backend-config-snippet annotation not added when Ingress created

### ISSUE THREAD

**Issue by mprocterncs** [haproxytech/kubernetes-ingress#431]
I'm using HAProxy Ingress Controller v1.7.6 c88c805.

I have found that an Ingress backend-config-snippet annotation is not being added to the haproxy.cfg backend section when an Ingress is created.  However, if I uninstall haproxy-ingress and re-install whilst the Ingress is already present, then the haproxy.cfg backend section does have the backend-config-snippet annotation content from my ingress.  If I then uninstall my Ingress and then re-install, the haproxy.cfg backend section does not have the backend-config-snippet annotation content from my ingress.

Therefore, I think there is a problem when the controller is already running and detects that an Ingress has been created, that on creating the haproxy.cfg backend section for it, it doesn't add the backend-config-snippet annotation content.  However, when the controller starts and finds an existing Ingress (as part of it's init?), it does seem to add the backend-config-snippet annotation content for the ingress' backend.

Please let me know if you need any further information.

**Comment by mprocterncs** [comment]
I have found commit 0a24262f895624021b482cffb115ec5603b746fd and wondered if the problem was due to removing my Ingress and then re-applying it, and hitting the issue this commit has resolved (I don't know the code well enough to know if that could be possible).  So I've updated to using HAProxy Ingress Controller v1.7.7 07e10cd and done the same test, and it still has the same problem.

**Comment by Mo3m3n** [comment]
Thanks @mprocterncs for the report.
This should have been fixed now with https://github.com/haproxytech/kubernetes-ingress/commit/78f92aa27c383c378198463258fc2e31d4f057a3
You can built current master to use it, wait for nightly built to be available or wait for the next backport and release of  a path version for `v1.7` (we will let you know).

**Comment by Mo3m3n** [comment]
Fix available in `v1.7.8`
