### ISSUE TITLE
publish-service not working with v1.7.7?

### ISSUE THREAD

**Issue by cspargo** [haproxytech/kubernetes-ingress#434]
i've found that the Address status in an ingress is not getting updated when I create an ingress. If I restart the controller pods it does get updated, but only then.

If I downgrade to v1.7.6 it works. I also tried building from the master branch, and it still didn't work. I then tried reverting commits, and found that it does work if I revert this commit https://github.com/haproxytech/kubernetes-ingress/commit/07e10cdfa63e3cdf179a9b8eaaadac966613ff04

**Comment by dschuldt** [comment]
I can confirm it does not work with current version 1.7.7 in our clusters (RKE).

Status loadbalancer in ingress is empty 

status:
  loadBalancer: {}

Restarting the Controller deployment does NOT work either.

Nevertheless, Controller is fully functional.

**Comment by ivanmatmati** [comment]
Hi, could you check if this commit 91a5c0d45758eba0e8c66c3f18b7b825dff3fbce solves your problem ?

**Comment by cspargo-apptio** [comment]
Yes it does fix the problem. Thanks!

**Comment by cspargo** [comment]
Yes it does fix the problem. Thanks!

**Comment by dschuldt** [comment]
Thanks for this fast bugfix release!
