### ISSUE TITLE
multiple custom acls

### ISSUE THREAD

**Issue by tanjfzzz** [haproxytech/kubernetes-ingress#442]
Hi,
For some reasons, I have a need to route traffic with multiple custom acls, like `use_backend if mybackend { hdr(myheader) -i 1 } { nbsrv(mybackend) gt 0 }`. How can I implement this?

**Comment by ivanmatmati** [comment]
Hi @tanjfzzz , You can try the [frontend-config-snippet](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#frontend-config-snippet) annotation to insert your own built ACLs into frontend routing rules.
