### ISSUE TITLE
Feature request: additional backends e.g. for haproxy spoa

### ISSUE THREAD

**Issue by dani-CO-CN** [haproxytech/kubernetes-ingress#449]
We are currently using haproxy ingress controller in combination with cloudflare zero-trust. Cloudflare Zero trust handles the access control for you and the traffic for authorized users gets forwards to an ip address of choice. To verify the integrity of the request cloudflare adds a jwt in the header, which we need to verify. We decided on using the haproxy spoa feature to do the verification process, but to implement that we need an additional backend for the verification service. 

We found a dirty hack to achieve our goal by creating a tcp-service, a tcp-service creates a frontend and a backend and we rely on the name of the created backend to be repurposed as spoa backend. I think it would make sense to add the option for additional backends.

**Comment by mecampbellsoup** [comment]
> there already is an option to use [secondary-config file](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/secondary-config.md?rgh-link-date=2022-06-29T14%3A53%3A37Z) and you can put basically anything in there.

i'm curious how one would do this in a k8s context. we are working on a SPOA as well for something similar (authN/authZ) and i'm curious how e.g. the pod IPs for the new SPOA deployment can be dynamically generated into our haproxy.cfg file...
