### ISSUE TITLE
The ingress controller is unable to handle a large list of IP addresses

### ISSUE THREAD

**Issue by uint** [haproxytech/kubernetes-ingress#45]
Hello!

When you provide a long list of IPs to whitelist through ingress annotations, haproxy crashes upon being reloaded, ending up in a crash loop.

```
2019/07/29 10:57:54 controller-haproxy.go:150: 14: ERR transactionId=7bb0ca3b-59b5-4acc-8420-af3a8520cb46                                                                                                                                                                       
msg="parsing [/tmp/haproxy/haproxy.cfg.7bb0ca3b-59b5-4acc-8420-af3a8520cb46:16]: line too long, truncating at word 65, position 920: <192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50
.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50
.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 192.168.50.1/24 }>."      
line=16 msg="error detected while parsing an 'http-request allow' condition missing closing '}' in condition."
```

This stems from the fact haproxy itself has a limit to how many words a single line of haproxy.cfg can include.

I've tested around and a valid workout is to put the whitelist in a separate file and use the `{ src -f /path/to/whitelist.lst }` syntax in the config file (assuming `whitelist.lst` is the file with CIDRs separated by newlines).

Would it be desirable to make the Ingress controller do it that way rather than putting the IP ranges inline?

**Comment by oktalz** [comment]
Hi @uint 

yes definitely, we shouldn't be limited in controller if HAProxy has different way of handling it.

**Comment by thyn** [comment]
Any updates here? Is it implemented?

**Comment by Mo3m3n** [comment]
This is fixed by putting the list IPs in a pattern file.
