### ISSUE TITLE
HAProxy is getting restarted constantly

### ISSUE THREAD

**Issue by lukasged** [haproxytech/kubernetes-ingress#452]
We used to run the HAProxy Ingress controller Helm chart version 1.11.1 without any issues for the past couple years.

Since we upgraded to Helm chart version 1.21.1 which uses HAProxy 1.7.9 we noticed that the controller is restarting HAProxy in a loop (apparently every 10 minutes by default, which is the value of `cache-resync-period`).

Is this supposed to work like that or it's a bug?

Below is a snippet from the HAProxy controller logs which are repeating all the time, with frequency set by `cache-resync-period`:

```
2022/06/02 15:29:47 INFO    controller.go:208 HAProxy reloaded
[WARNING]  (256) : Reexecuting Master process
[WARNING]  (256) : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[WARNING]  (267) : Proxy healthz stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (267) : Proxy http stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (267) : Proxy https stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (267) : Proxy stats stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (267) : Stopping frontend GLOBAL in 0 ms.
[WARNING]  (267) : Stopping backend backend1 in 0 ms.
[WARNING]  (267) : Stopping backend backend2 in 0 ms.
[WARNING]  (267) : Stopping backend backend3 in 0 ms.
[NOTICE]   (256) : New worker #1 (275) forked
[WARNING]  (256) : Former worker #1 (267) exited with code 0 (Exit)
2022/06/02 15:30:53 INFO    controller.go:208 HAProxy reloaded
[WARNING]  (256) : Reexecuting Master process
```

**Comment by fabianonunes** [comment]
I think this is intentional. I bisect between 1.6.7 and 1.7.10 and I found out this behavior started with commit 
 07e10cdfa63e3cdf179a9b8eaaadac966613ff04 `MEDIUM: Don't skip any Ingress event`, first released in version 1.7.7.

In the commit message, the author says this will _(...) increases the risk of triggering the sync method for no reason in case the k8s update is irrelevant._

**Comment by lukasged** [comment]
> I think this is intentional. I bisect between 1.6.7 and 1.7.10 and I found out this behavior started with commit [07e10cd](https://github.com/haproxytech/kubernetes-ingress/commit/07e10cdfa63e3cdf179a9b8eaaadac966613ff04) `MEDIUM: Don't skip any Ingress event`, first released in version 1.7.7.
> 
> In the commit message, the author says this will _(...) increases the risk of triggering the sync method for no reason in case the k8s update is irrelevant._

Thanks for having a look at this @fabianonunes . The commit author says it will increase the risk of triggering sync, but in my case it has been triggering all the time for the past month since upgrading the HAProxy Ingress controller, exactly every 10 minutes. So I'm not sure which Ingress event it's being triggered by, for sure there's no pod lifecycle events happening that often. 

Maybe it's just reacting to readiness probes? Although those shouldn't be Ingress events, as the probes are successful most of the time ...

**Comment by fabianonunes** [comment]
Hi @lukasged,

Can you increase the log level to debug (add `--log=debug` to field `extraArgs`) and post the logs?

I'm getting the same issue, but my instances are restarting while yours are reloading. In my case, the syslog-server comparison algorithm was the culprit. I have already submitted a PR to fix this (#451).

After enabling debug level, these were my logs (formatted, for easier reading):

```
2022/06/02 00:41:59 DEBUG   global.go:82 Global log targets updated:
[
slice[0].Address: stdout != /run/shared/log
slice[0].Facility: daemon != local0
slice[0].Format: raw != 
slice[0].Level: notice != info

slice[1].Address: /run/shared/log != stdout
slice[1].Facility: local0 != daemon
slice[1].Format:  != raw
slice[1].Index: 0 != 1
slice[1].Level: info != notice
]
Restart required
```

If you can, post the `values.yaml` to help with debugging

**Comment by ivanmatmati** [comment]
Hi @lukasged , In your case, you should probably increase the `cache-resync-period` parameter. It's voluntarily low in the default configuration but you can increase the value to accomodate your need.  The purpose of the cache resync period parameter is subtle and certainly differs from what you expect. Please refer to this issue [response](https://github.com/kubernetes-sigs/controller-runtime/issues/521#issuecomment-518457302). The important part is :
> The problem was that nobody actually understood what this knob did -- it doesn't relist from the API server (which is what most people thought it did). All it does is force a re-reconcile of everything in the cache. Generally, you probably don't want to do this -- it's often expensive, it'll mask subtle bugs, and it's usually not necessary. It's actually probably fine to set this to never, except it might save you in production if you've got bugs in your reconcile logic because you didn't write a level-based controller.

As you can see you can increase the value even to 10 hours if you prefer. Have a nice day.

**Comment by lukasged** [comment]
> Hi @lukasged,
> 
> Can you increase the log level to debug (add `--log=debug` to field `extraArgs`) and post the logs?
> 
> I'm getting the same issue, but my instances are restarting while yours are reloading. In my case, the syslog-server comparison algorithm was the culprit. I have already submitted a PR to fix this (#451).
> 
> After enabling debug level, these were my logs (formatted, for easier reading):
> 
> ```
> 2022/06/02 00:41:59 DEBUG   global.go:82 Global log targets updated:
> [
> slice[0].Address: stdout != /run/shared/log
> slice[0].Facility: daemon != local0
> slice[0].Format: raw != 
> slice[0].Level: notice != info
> 
> slice[1].Address: /run/shared/log != stdout
> slice[1].Facility: local0 != daemon
> slice[1].Format:  != raw
> slice[1].Index: 0 != 1
> slice[1].Level: info != notice
> ]
> Restart required
> ```
> 
> If you can, post the `values.yaml` to help with debugging

Sure, I deployed another controller with debug enabled and here are the logs I'm getting now:

```
2022/06/07 13:22:18 INFO    controller.go:208 HAProxy reloaded
[WARNING]  (255) : Reexecuting Master process
[WARNING]  (255) : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[WARNING]  (371) : Proxy healthz stopped (cumulated conns: FE: 120, BE: 0).
[WARNING]  (371) : Proxy http stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (371) : Proxy https stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (371) : Proxy stats stopped (cumulated conns: FE: 1, BE: 0).
[WARNING]  (371) : Stopping frontend GLOBAL in 0 ms.
[WARNING]  (371) : Stopping backend kube-system-ingress-haproxy-test-restarts-kubernetes-ingress-default-backen-ht
[NOTICE]   (255) : New worker #1 (379) forked
[WARNING]  (255) : Former worker #1 (371) exited with code 0 (Exit)
2022/06/07 13:32:18 DEBUG   global.go:138 Defaults config updated: [ErrorFiles: <nil slice> != [0xc000926ca8]]
Reload required
2022/06/07 13:32:18 WARNING service/endpoints.go:33 Ingress 'kube-system/ingress-haproxy-test-restarts-kubernetes-tp'
2022/06/07 13:32:18 DEBUG   controller.go:165 ingress 'pushgateway/prometheus-pushgateway' ignored: no matching In

2022/06/07 13:32:18 INFO    controller.go:208 HAProxy reloaded
[WARNING]  (255) : Reexecuting Master process
```

And these are my `values.yaml`:
```yaml
controller:
  config:
    timeout-client: 30m
    timeout-server: 30m
  daemonset:
    hostPorts:
      http: 80
      https: 443
      stat: 1024
    useHostNetwork: false
    useHostPort: false
  extraArgs:
  - --configmap-errorfiles=kube-system/errorfile
  - --log=debug
  ingressClass: haproxy-test-restarts
  kind: Deployment
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
  service:
    enabled: true
    type: LoadBalancer
  serviceMonitor:
    enabled: true
    extraLabels:
      release: prometheus-operator
defaultBackend:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/defaultbackend-amd64
    runAsUser: 65534
    tag: 1.5
  name: default-backend
  replicaCount: 2
```

**Comment by fabianonunes** [comment]
Hi, @lukasged.

That's indeed a bug. Try removing the `- --configmap-errorfiles=kube-system/errorfile` flag and see if gratuitous reload will stop.

I will investigate and try to make a PR.

To help with debugging, please post the contents of ConfigMap `kube-system/errorfile`.

**Comment by ivanmatmati** [comment]
I will discuss that with older team members tomorrow but the current implies that a change event from k8s will produce a reload. And guess what, the cache resync creates such events. We will see if we can do otherwise and if there's a specific reason to do that in the current way. Anyway, as the reference says you can perfectly disconnet this cache resync by setting `--cache-resync-period=0s` for the controller.

**Comment by fabianonunes** [comment]
Hi, @ivanmatmati.

I'm debugging this right now and seems there is a bug in the comparison between `newDefaults` (from annotations) and `haproxy.DefaultsGetConfiguration` when using errorfiles.

I've fixed two similar scenarios in PRs #455 (reloads) and #451 (restarts):
- In PR #455 I've described a bug that causes unnecessary reloads because of a bug when comparing `client-crt-optional` and `ca-file` with the current HAProxy state.
- In PR #451, the bug is on the syslog-server comparison (which is the worst because it's not a reload but a restart that interrupts ongoing requests).

I know reload is a [seamless operation](https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/) in HAProxy and we could disable cache resyncs, but shouldn't we fix these comparison bugs and avoid reloads anyway?

**Comment by fabianonunes** [comment]
Consider commit 2f200cf43edf3fc2ec33eb85bf0adbe159d16d85, where, to avoid unnecessary reloading, we chose to update the HAProxy map files dynamically.

In that commit, the author avoided an unnecessary reload, but his effort is useless without fixing these comparison bugs. Even with dynamic file maps updates, we will have a reload because this bug (or those described in #455 and #451) will force a reload anyway.

**Comment by lukasged** [comment]
> Hi, @lukasged.
> 
> That's indeed a bug. Try removing the `- --configmap-errorfiles=kube-system/errorfile` flag and see if gratuitous reload will stop.
> 
> I will investigate and try to make a PR.

Thanks @fabianonunes for investigating this.

I guess there's no need to specify the contents of my `--configmap-errorfiles`, as it's just a plain HTML document in the following format:
```yaml
data:
  "503": "HTTP/1.0 503 Service Unavailable\nCache-Control: no-cache\nConnection: close\nContent-Type:
    text/html\n\n<html>HTML_CONTENT</html>"
```

But I confirm that if I re-deploy the HAProxy Helm chart removing the `--configmap-errorfiles` option, the continuous reload problem disappears.

**Comment by Jibux** [comment]
Hello,
We have similar issue - it seems react to Ingress events... but every minutes!
```
...
2022/07/01 16:13:11 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:11 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:11 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:11 INFO    handler/https.go:123 removing client TLS authentication
[NOTICE]   (256) : Reloading HAProxy
2022/07/01 16:13:11 INFO    controller.go:166 HAProxy reloaded
[NOTICE]   (256) : haproxy version is 2.5.7-2ef551d
[WARNING]  (256) : config : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[WARNING]  (437) : Proxy healthz stopped (cumulated conns: FE: 26, BE: 0).
Proxy healthz stopped (cumulated conns: FE: 26, BE: 0).
[WARNING]  (437) : Proxy http stopped (cumulated conns: FE: 0, BE: 0).
Proxy http stopped (cumulated conns: FE: 0, BE: 0).
[NOTICE]   (256) : New worker (444) forked
[NOTICE]   (256) : Loading success.
[WARNING]  (437) : Proxy https stopped (cumulated conns: FE: 0, BE: 0).
Proxy https stopped (cumulated conns: FE: 0, BE: 0).
[WARNING]  (437) : Proxy stats stopped (cumulated conns: FE: 1, BE: 0).
Proxy stats stopped (cumulated conns: FE: 1, BE: 0).
[NOTICE]   (256) : haproxy version is 2.5.7-2ef551d
[WARNING]  (256) : Former worker (437) exited with code 0 (Exit)
10.72.0.117:33352 [01/Jul/2022:16:13:33.055] stats stats/<PROMEX> 0/0/0/0/0 200 365665 - - LR-- 1/1/0/0/0 0/0 "GET 10.72.2.231:1024/metrics HTTP/1.1"
2022/07/01 16:13:51 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:51 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:51 DEBUG   controller.go:123 ingress 'XXXXX' ignored: no matching IngressClass
2022/07/01 16:13:51 INFO    handler/https.go:123 removing client TLS authentication
[NOTICE]   (256) : Reloading HAProxy
2022/07/01 16:13:51 INFO    controller.go:166 HAProxy reloaded
...
```
Is there a way to avoid those reloading? We wonder if this is dangerous for production environment.

**Comment by fabianonunes** [comment]
Hi, @Jibux 

This was corrected in #455 but has not yet been released.

**Comment by Jibux** [comment]
Ok understood. Many thanks.

**Comment by ivanmatmati** [comment]
Hi @Jibux , you can check the fix in nightly build version.

**Comment by Jibux** [comment]
Hi @ivanmatmati, I confirm it is fixed in the nightly build version.
