### ISSUE TITLE
ssl-redirect override regression

### ISSUE THREAD

**Issue by ThinkChaos** [haproxytech/kubernetes-ingress#469]
Hi,

It seems that for versions 1.7.0 to latest (1.8.3 at time of writing), a `ssl-redirect` annotation on an Ingress cannot override the value from the controller's ConfigMap.

In my case, I have `ssl-redirect: "true"` in the ConfigMap, and `haproxy.org/ssl-redirect: "false"` in the Ingress.  
This works as expected with 1.6.9, but it seems newer version ignore the Ingress' annotation and do a redirect.

I didn't test all versions between 1.7.0 and 1.8.3, but the couple random ones I did all had the issue.

**Comment by ivanmatmati** [comment]
Hi @ThinkChaos , Indeed there's a bug. Thanks for reporting, a fix will be provided as soon as possible.

**Comment by ivanmatmati** [comment]
Hi @ThinkChaos , after verification I don't see major difference between results of current code and v1.6.9. If I set ssl-redirect: "true" on configmap and ssl-redirect: "false" on a particular ingress, I can see in both case that configuration has a redirect rule with an id not present in map file for the particular ingress. To illustrate, I have this in haproxy.cfg:

**Comment by ivanmatmati** [comment]
Hi, fixed in v1.8.4.
