### ISSUE TITLE
haproxy doesn't start

### ISSUE THREAD

**Issue by fcomte** [haproxytech/kubernetes-ingress#47]
Hey,

I am running kubernetes on dcos 1.13.3.
Kubernetes version is 1.14.3

`kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml
`
When I try to start haproxy ingress controller, the healtcheck is not responding.

When I desactivate it, and I exec /bin/sh inside the pod.. I see only this process :

`PID   USER     TIME  COMMAND
    1 root      0:00 /dumb-init -- /start.sh --configmap=default/haproxy-configmap --defau....
    6 root      0:00 /haproxy-ingress-controller --configmap=default/haproxy-configm....
   38 root      0:00 /bin/sh
   46 root      0:00 ps
` 

`netstat -l` doesn't show any listenning port

And when I try to lauch manually haproxy : 
`/ # haproxy -d -f /etc/haproxy/haproxy.cfg 
[WARNING] 213/140024 (78) : config : missing timeouts for frontend 'healthz'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 213/140024 (78) : config : missing timeouts for frontend 'http'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 213/140024 (78) : config : missing timeouts for frontend 'https'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 213/140024 (78) : config : missing timeouts for frontend 'stats'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 213/140024 (78) : config : missing timeouts for backend 'default-nginx-service-80'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 213/140024 (78) : config : missing timeouts for backend 'kube-system-ingress-default-backend-8080'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero value: 'client', 'connect', 'server'.
Note: setting global.maxconn to 536870846.
Available polling systems :
epoll : pref=300, test result OK
poll : pref=200, test result OK
select : pref=150, test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
[SPOE] spoe
[COMP] compression
[CACHE] cache
[TRACE] trace
Killed`

**Comment by bedis** [comment]
Could you send us your kubectl logs for this pod?

**Comment by fcomte** [comment]
`root@~/kubernetes-ingress[09:26:25]# kubectl logs -f --namespace haproxy-controller haproxy-ingress-5f689bc454-nmsjw
2019/08/03 21:26:36 
 _   _    _    ____                                            
| | | |  / \  |  _ \ _ __ _____  ___   _                       
| |_| | / _ \ | |_) | '__/ _ \ \/ / | | |                      
|  _  |/ ___ \|  __/| | | (_) >  <| |_| |                      
|_| |_/_/   \_\_|   |_|  \___/_/\_\\__, |                      
 _  __     _                       |___/             ___ ____  
| |/ /   _| |__   ___ _ __ _ __   ___| |_ ___  ___  |_ _/ ___| 
| ' / | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|  | | |      
| . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \  | | |___ 
|_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/ |___\____| 
															 

2019/08/03 21:26:36 HAProxy Ingress Controller v1.1.5 06d5e2a

2019/08/03 21:26:36 Build from: git@github.com:haproxytech/kubernetes-ingress.git
2019/08/03 21:26:36 Build date: 2019-07-30T09:07:53

2019/08/03 21:26:36 ConfigMap: default/haproxy-configmap
2019/08/03 21:26:36 Ingress class: haproxy
2019/08/03 21:26:36 main.go:83: Default backend service: haproxy-controller/ingress-default-backend
2019/08/03 21:26:36 main.go:84: Default ssl certificate: default/tls-secret
2019/08/03 21:26:36 controller.go:90: Starting HAProxy with /etc/haproxy/haproxy.cfg
2019/08/03 21:26:52 controller.go:70: Running on Kubernetes version: v1.14.3 linux/amd64
2019/08/03 21:26:57 controller-https.go:80: secret not found tls-secret
root@~/kubernetes-ingress[09:27:07]# 
`

**Comment by fcomte** [comment]
This pod is destroyed by kubernetes because livenessprobe are unhealthy

**Comment by bedis** [comment]
Could you try to create the default tls secret 'default/tls-secret' in your case?
Or point the controller to a tls secret which exists?

**Comment by bedis** [comment]
This is how HAProxy is supposed to be started up:
`haproxy -f /etc/haproxy/global.cfg -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid`

Can you start it up this way and add '-d' for debug output?

**Comment by fcomte** [comment]
`/ # haproxy -d -f /etc/haproxy/global.cfg -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
[WARNING] 217/085059 (74) : Can't open server state file '/var/state/haproxy/global': No such file or directory
[WARNING] 217/085059 (74) : Can't open server state file '/var/state/haproxy/global': No such file or directory
Note: setting global.maxconn to 536870861.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
Killed
`

**Comment by bedis** [comment]
I like the `Note: setting global.maxconn to 536870861`...
Can you try adding "maxconn 10000" in your global section in /etc/haproxy/global.cfg  and try a new manual start?

**Comment by fcomte** [comment]
This seem to be good now : 
`/ # haproxy -d -f /etc/haproxy/global.cfg -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
[WARNING] 225/145934 (12906) : Can't open server state file '/var/state/haproxy/global': No such file or directory
[WARNING] 225/145934 (12906) : Can't open server state file '/var/state/haproxy/global': No such file or directory
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
Using epoll() as the polling mechanism.
[NOTICE] 225/145934 (12906) : New worker #1 (12907) forked`

**Comment by fcomte** [comment]
What would be the best way to fix it automatically?

**Comment by bedis** [comment]
Well I don't understand what the problem is, so no reliable way to fix it!
