### ISSUE TITLE
`check-interval` only affects `default_local_backend`

### ISSUE THREAD

**Issue by jkbschmid** [haproxytech/kubernetes-ingress#484]
Hey there 👋 

I'm running into an issue where I specify `check-interval: 5s` in the ConfigMap provided via `--configmap`.
The ingress controller correctly parses the setting, but the 5 seconds only make it to the `default_local_backend` and not the backends that are generated for target services.

```
backend default_local_backend
  default-server check inter 5000
  ...

backend my-ns_my-svc_http
  mode tcp
  default-server check               # this is where I'd expect "inter 5000" as well
```

Is this intentional or should I use a different configuration?

Thank you for your help!

**Comment by ivanmatmati** [comment]
Hi @jkbschmid , thanks for reporting. Can you give your ingress controller version ?

**Comment by jkbschmid** [comment]
Hi @ivanmatmati , thanks for the response 🙂 I've tried both ingress controller version 1.8.3 and 1.8.5.

**Comment by jkbschmid** [comment]
I also tried using `backend-config-snippet`, but the `default-server inter 5000` I put in there was always removed (other parts of the snippet did not get removed).

**Comment by ivanmatmati** [comment]
It's working as intended and as you expected in my test. I'm looking. Do you have any configuration related to check at any level (configmap, service, ingress) ?

**Comment by jkbschmid** [comment]
Thanks, yes. I'm using the ConfigMap below. 
I completely forgot to mentioned that I was using ingress-controller v1.6.5 previously and the setting in the ConfigMap stopped working when upgrading to 1.8.3. Sorry for mentioning this only now 🙈 
```
kind: ConfigMap
data:
  backend-config-snippet: |
    option redispatch 1
    option httpchk
    http-check connect
    http-check send meth GET uri /_some_uri ver HTTP/1.1 hdr host example.com
  check: "true"
  check-interval: 5s
  frontend-config-snippet: |
    acl site_dead nbsrv(my-namespace_my-service_http) lt 5
    monitor-uri /_some_uri
    monitor fail if site_dead
    option dontlog-normal
  load-balance: leastconn
  nbthread: "1"
  scale-server-slots: "50"
  syslog-server: address:stdout, facility:daemon, format:raw,
  timeout-client: 180s
  timeout-client-fin: 5s
  timeout-connect: 20ms
  timeout-queue: 120s
  timeout-server: 180s
  timeout-server-fin: 5s
  timeout-tunnel: 180s
```

**Comment by ivanmatmati** [comment]
Hi @jkbschmid , the only way for me to reproduce your configuration is to explicitly set an empty value at ingress level.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   annotations:
     check-interval: ""
```
Can you "check" that ? Ingress value will override configmap configuration.

**Comment by jkbschmid** [comment]
Hey @ivanmatmati ,
thanks for having a look! 
I'm actually not using an `Ingress`, but a `Service` and it doesn't have any annotations for haproxy.
