### ISSUE TITLE
Impossible to change path to configuration file (External Mode Setup)

### ISSUE THREAD

**Issue by lukaleet** [haproxytech/kubernetes-ingress#494]
I couldn't find any specific information about this issue I'm facing. So  I decided to open an issue here. So I set up HAProxy Ingress Controller in External Mode following official guides. I have established connection with Calico and BIRD. Connection and protocols looks fine (see below).
![image](https://user-images.githubusercontent.com/56636763/197386813-1822c096-941e-4280-b467-66b4838c9b7a.png)
![image](https://user-images.githubusercontent.com/56636763/197387170-7f12713d-e07d-4dd1-a7f1-417e6f29637e.png)

However the service itself is mapped to wrong files from the beggining. Because service status cannot get to haproxy configuration file and socket.
Look at service status. (it behaves the same whether ExecStartPre is in .service or not. The only difference here is that it copies this config file from github to haproxy.cfg.1):
![image](https://user-images.githubusercontent.com/56636763/197386680-52681626-1491-4a61-94ff-6ad79ed1bcff.png)

Service configuration is following:
```
[Unit]
Description="HAProxy Kubernetes Ingress Controller"
Documentation=https://www.haproxy.com/
Requires=network-online.target
After=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStartPre=/bin/mkdir -p /tmp/haproxy-ingress/etc/
ExecStartPre=/usr/bin/wget https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/fs/usr/local/etc/haproxy/haproxy.cfg -P /tmp/haproxy-ingress/etc/
ExecStart=/usr/local/bin/haproxy-ingress-controller --external --configmap=default/haproxy-kubernetes-ingress --program=/usr/sbin/haproxy --disable-ipv6 --ipv4-bind-address=0.0.0.0 --http-bind-port=80 &
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGTERM
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

/tmp/haproxy-ingress/etc/haproxy.cfg has following contents. Obviously it is about pidfile and stats socket.
```
# _version=1
# HAProxy Technologies
# https://www.haproxy.com/
#
# this file is not meant to be changed directly
# it is under haproxy ingress controller management
#

global
  daemon
  master-worker
  pidfile /tmp/haproxy-ingress/run/haproxy.pid
  stats socket /tmp/haproxy-ingress/run/haproxy-runtime-api.sock level admin expose-fd listeners
  default-path config

peers localinstance
   peer local 127.0.0.1:10000

frontend https
  mode http
  bind 127.0.0.1:8080 name v4
  http-request set-var(txn.base) base
  use_backend %[var(txn.path_match),field(1,.)]

frontend http
  mode http
  bind 127.0.0.1:4443 name v4
  http-request set-var(txn.base) base
  use_backend %[var(txn.path_match),field(1,.)]

frontend healthz
  bind 127.0.0.1:1042 name v4
  mode http
  monitor-uri /healthz
  option dontlog-normal

frontend stats
   mode http
   bind *:1024
   http-request set-var(txn.base) base
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable
   stats uri /
   stats refresh 10s
```
It seems like service is always overwriting files from ExecStartPre and I don't know how to change this behavior.

How can I change this behaviour of service reading default pid and socket from/tmp/haproxy-ingress/run/ get this to work? Is it a bug or I did something wrong during conifguration? As I said in the beggining I've been following docs.

**Comment by ivanmatmati** [comment]
Hi @lukaleet , thanks for reporting. Can you give the ingress controller version you're using? Are the offending files actually present or not ? Could you also try to run an haproxy instance on the machine and then launch your service ? You can run haproxy with :
haproxy -f /tmp/haproxy-ingress/etc/haproxy.cfg
