### ISSUE TITLE
Better documentation for 'sync-period' and 'cache-resync-period'

### ISSUE THREAD

**Issue by EmielBruijntjes** [haproxytech/kubernetes-ingress#497]
## Problem

The documentation of the --sync-period and --cache-resync-period command line flags is very short, and it is unclear to me what these settings exactly do, and whether it is harmful and/or beneficial to change the default values. I am referring to the docs that I found here: https://www.haproxy.com/documentation/kubernetes/latest/configuration/controller/#--sync-period

## Why are we interested in this?

We noticed that haproxy reloads every 10 minutes, which causes a new haproxy process to be started, and the old worker to receive a signal that kindly asks it to stop running. Because we use haproxy to handle long-lasting websocket-connections, shutting down a worker often takes hours if not days to get completed. This causes our servers to end up with many different haproxy processes. Which we rather not have. I think that this would not be so much of a problem if haproxy had not restarted that often -- or only restarts when really needed (for example when ingresses are added or removed, or when there are new ssl certificates (does that require a reload? I dont know).

## Anyway...

I have the _feeling_ that the --cache-resync-period setting has something to do with these 10 minute restarts, because that value also happens to be set to 10 minutes. But the documentation is unclear what this setting does (for example: what does it have to do with a cache, why does a cache have to be synced, and why every 10 minutes (instead of, for example, every 5 seconds or every hour). And if you change the setting to something higher or lower, does that make things better or worse? And why does haproxy have to be reloaded or synced in the first place, even when nothing changes? Or is it necessary to reload it every 10 minutes? It would be helpful if this documentation was more explaining.

The documentation also mentions a 'sync-period' (set to five seconds by default) -- it is also unclear what the difference between this setting and the cache-sync-period is, and (also) what exactly is synced? Is syncing necessary? Is periodic syncing the only way how haproxy-operator keeps in sync with kubernetes or does it (also) monitor the kubernetes api for updates to ingresses, services, secrets, etc and does it use those events to update its state and is the 5 second an 10 minute synchronization only a 'just-in-case' mechanism? Would be nice to have that explained.

Thanks.

**Comment by ivanmatmati** [comment]
Hi @EmielBruijntjes , in a nutshell cache resync period is the period after which a replay of all events contained in informers cache will be run. This is an insurance for controllers.  The tuning of the pediod is an average value that we put by default but can be changed to suit your needs. I think you can even disable it with a value of 0s. This tuning is up to you, we don't have recommandation, this is a cluster specific matter. Concerning the reload of haproxy I think this is something we need to discuss internally to decide if it's still the best strategy.
The sync period is specific to the controller and totally mandatory. It's the time during which the controller will gather all changes before reflecting them in a transaction. So you can think of it as the minimum interval between two transactions. The idea is to avoid reloading upon every single change and instead reduce this costly process to the lowest possible frequency.
