### ISSUE TITLE
accept-proxy on tcp/ssl frontend

### ISSUE THREAD

**Issue by strowi** [haproxytech/kubernetes-ingress#498]
Hi,

i have been searching the issues but only found a couple of more or less stale issues.
Currently we are running a haproxy-ingress on k8s behind a tcp-loadbalancer ( on hetzner-cloud) terminating ssl.
For http/s-traffic this works as expected.

I also have tcp-ports exposed via `--configmap-tcp-services=..`:

```
apiVersion: v1
data:
  "8883": app/emqx:1883:ssl
...
```

Now i want to use proxy-protocol on that tcp frontend. 
I manually added the "accept-proxy" within the haproxy-ingress pod and after a few seconds traffic goes through:

```
frontend tcp-8883
  mode tcp
  bind 0.0.0.0:8883 name v4 crt /etc/haproxy/certs/frontend ssl accept-proxy
  bind :::8883 name v6 crt /etc/haproxy/certs/frontend ssl v4v6 accept-proxy
  option tcplog
  default_backend app-emqx-mqtt
```

But how can i get the `accept-proxy` in there the right way? Or am i missing another way?

regards,
strowi

**Comment by ivanmatmati** [comment]
Hi @strowi , unfortunately the TCP support is basic and does not contain accept-proxy.

**Comment by strowi** [comment]
@ivanmatmati too bad.. i will have to check other ingress solutions then. Thx for the info!
