### ISSUE TITLE
Can I use this controller for MQTT?

### ISSUE THREAD

**Issue by lcofre** [haproxytech/kubernetes-ingress#5]
First of all, amazing work done for haproxy 2.0

I was wondering if I can use this controller for MQTT ingress

Currently I have a custom haproxy image to provide TLS termination with a configuration similar to this:
```
listen mqtt
  bind *:1883
  bind *:8883 ssl crt /certs/server.pem ca-file /certs/client.crt verify required
  mode tcp
  option clitcpka
  timeout client 3h
  timeout server 3h
  server mqtt_server ${MQTT_SERVER}:${MQTT_PORT}
```
I point to the mqtt cluster service with the environment variables MQTT_SERVER and MQTT_PORT.

Thanks in advance for your help.

**Comment by oktalz** [comment]
Hi, 
something like this is not currently possible, but certainly can be done.

I cannot give you estimation, but I really do not see why something like this shouldn't be possible soon.
Feel free to write complete (with anonymous data) config you use if the one you wrote here is not complete.

**Comment by lcofre** [comment]
That's great, thanks very much for your feedback.

This is my complete configuration
```
global
  maxconn 20000

defaults
  timeout connect 20s
  timeout client 3000s
  timeout server 3000s

listen mqtt
  bind *:1883
  bind *:8883 ssl crt /certs/server.pem ca-file /certs/client.crt verify required ciphers ECDHE-ECDSA-AES128-CCM8
  bind *:8888 ssl crt /certs/server.pem ciphers ECDHE-ECDSA-AES128-CCM8
  #I use the same container in two different deployments, one exposing 8883 and the other 8888
  mode tcp
  option clitcpka
  timeout client 3h
  timeout server 3h

  server mqtt_server ${MQTT_SERVER}:${MQTT_PORT}


listen dashboard
  bind *:80
  server dashboard ${MQTT_SERVER}:${MQTT_DASHBOARD}


listen stats
  bind :9000
  mode http
  stats enable
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /stats
  stats auth admin:pass
```

**Comment by Lavhe** [comment]
Hi guys

Any progress in this?

**Comment by seguidor777** [comment]
Please keep us updated

**Comment by Mo3m3n** [comment]
Hi sorry this went out of sight, but It is possible to use controller for MQTT for a long time now since [tcp-services](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--configmap-tcp-services) were added.
A configuration example can be found here https://github.com/haproxytech/kubernetes-ingress/issues/283#issue-824227818
