### ISSUE TITLE
Rename "whitelist" and remove "whitelist-with-rate-limit" annotation

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#50]
The name of this annotation is confusing, since it applies to the "rate limit" function only.
Would be good to rename it to `rate-limit-whitelist`.
In the mean time, I think the annotation `whitelist-with-rate-limit` is redundant and that we could apply the whitelist to the rate-limit only when `rate-limit-whitelist` is set.

**Comment by Mo3m3n** [comment]
This was fixed at some point in 1.4
[whitelist](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#access-control) annotation will simply allow a set of IP/CIDR and block the rest at the L4 layer. There is no rate-limit involved.
