### ISSUE TITLE
can we edit haproxy.cfg or configure while creating the ingress controller

### ISSUE THREAD

**Issue by PrakashRajanSakthivel** [haproxytech/kubernetes-ingress#501]
I am trying to add a failover mechanism to HAProxy. I have deployed HAProxy through HELM and configured my backend. post controller deployment when I navigate to etc/haproxy/haproxy.cfg I can see the details. I want to add a backup server something like this 

backend bk_app_main
 server s2 10.0.0.102:80 check
 server s4 10.0.0.104:80 check backup

I am not sure if I can simply edit the cfg file or I have to override the config with configmap. since all the examples I can see shows to navigate to the path etc/haproxy/haproxy.cfg on the instance where its created and the one I have is installed in kubernetes and specifically its mentioned not to edit.

**Comment by ivanmatmati** [comment]
Hi @PrakashRajanSakthivel , you can add what you want in backend definition through [backend-config-snippet](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#backend-config-snippet).Note that you are entirely responsible for your insertion. We don't validate anything from config snippet and you must manage the ips addresses.

**Comment by PrakashRajanSakthivel** [comment]
Thanks, should I update the service or the Ingress ? Here is what I did

helm install kubernetes-ingress haproxytech/kubernetes-ingress --create-namespace --namespace haproxy-controller --set controller.service.type=LoadBalancer

kubectl apply -f .\defaults\app.yaml --namespace haproxy-controller

kubectl apply -f .\defaults\appservice.yaml --namespace haproxy-controller

kubectl apply -f .\defaults\ingress.yaml --namespace haproxy-controller

in the ingress I have updated the backend config to block all the traffic except for one but still I am able to access.

I have added the gist here https://gist.github.com/PrakashRajanSakthivel/fbf7512a96b616e125f58894251eb8c9
