### ISSUE TITLE
Understand how path-rewrite work 

### ISSUE THREAD

**Issue by carlosjpr-collab** [haproxytech/kubernetes-ingress#503]
I need to understand how that path-rewrite option work. 
Can someone please explqiue what \1 or \2 mean here?. 
why there is () around .* ?.
![image](https://user-images.githubusercontent.com/38086105/202481151-46e5683c-ee74-4eee-aed7-b22e483f5241.png)

**Comment by ivanmatmati** [comment]
Hi @carlosjpr-collab , it's based on regex. The line contains two expressions separated by space characters. The first one is the regex which can contain a capturing group and that will be applied to the incoming URL, and the second one is the rewritten URL you'll get with reinsertion of capturing groups if any. The capturing group, enclosed by parentheses, can be referred to by its numbered position. First group in expression gets number one, etc.

**Comment by carlosjpr-collab** [comment]
Thank, @ivanmatmati 
So if I need to change this request 
xx.com/st/g/f 
to
xx.com/u/g/f
I will do:
pathrewrite: /st/(.*) /u/\1
Is this write ?
