### ISSUE TITLE
Getting some warnings related to frontend timeouts 

### ISSUE THREAD

**Issue by nb044** [haproxytech/kubernetes-ingress#507]
I can see in the config map that timeout are set to nonzero values, even after that I am getting following warnings. 

Helm chart version: 1.24.0
config map details: 
data:
  timeout-client: 5s
  timeout-connect: 6s
  timeout-http-request: 10s
  timeout-server: 10s

----------------------
Logs from Kubernetes ingress pod. 

[WARNING]  (212) : config : missing timeouts for frontend 'https'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (212) : config : missing timeouts for frontend 'http'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (212) : config : missing timeouts for frontend 'healthz'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (212) : config : missing timeouts for frontend 'stats'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (212) : config : Removing incomplete section 'peers localinstance' (no peer named '**********' ) 

How can I get rid of these warnings? How can I set the frontend http timeout? I was not able to locate the placeholder for these values in the values.yaml file.

**Comment by ivanmatmati** [comment]
Hi @nb044 , Your question is related to Helm Chart project which is located [there](https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress). Ask preferably your question there. Anyway by looking at yaml files inside project, it seems you need to do something like:
