### ISSUE TITLE
Support caching CORS

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#52]
HAProxy has a built-in "maintenance" free HTTP caching that support caching for OPTIONS request since this commit: https://github.com/haproxy/haproxy/commit/1263540fe824c74bc3c668fec3476b880d65b27c.

When load-balancing APIs, a lot of OPTIONS requests related to CORS are issued to the application server.
The idea here is to configure HAProxy to cache these responses to offload processing on the server side and improve performance of the entire application.

Note that as of today, HAProxy cache does not yet support the Vary header, so this would be useful only when the server send `access-control-allow-origin: *`.

The HAProxy configuration should be stored in the relevant backend and would look like:
```
backend b_myapp
  http-request cache-use cors if METH_OPTIONS
  http-response cache-store cors if METH_OPTIONS

cache cors
  total-max-size 64
  max-object-size 1024
  max-age 60
```

Note that the server must send a Cache-Control header which allows caching (IE max-age=60,private) and no Vary header of course.

I think, for starting we need the following annotations:
- `cors-cache-enable`: boolean, default false

I think a single cache bucket (called "cors" in the example above) is sufficient with reasonable default values. Maybe we could allow tuning the cors cache bucket parameters through annotation in the Controller's configmap:
- `cachebucket-cors-total-max-size`: max size in bytes, default 64
- `cachebucket-cors-max-object-size`: max object size in bytes, default 1024
- `cachebucket-cors-max-age`: how long HAProxy will keep an object in the cache in seconds, default 60

/cc @vgallissot

**Comment by bedis** [comment]
Core caching will not be integrated into HAProxy the way it is described above and this patch will be removed.
We're working on an other way to implement such feature and I'll update this issue accordingly once I have more information.

**Comment by bedis** [comment]
Here is the new HAProxy CORS issue: https://github.com/haproxy/haproxy/issues/251, so we have to wait for this one to be fixed before we can implement it here.

**Comment by Mo3m3n** [comment]
[CORS](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#cors) are supported from 1.5
