### ISSUE TITLE
Unable to use custom CRD Backend with http-check

### ISSUE THREAD

**Issue by sudrishi0512** [haproxytech/kubernetes-ingress#523]
Hi I want to customize http health check and add headers while sending request for health check.

I tried using custom CRD backend using https://www.haproxy.com/documentation/kubernetes/latest/community/configuration-reference/custom-resources/backend/.

I am confused with the usage of required value "index" integer.
    http-check:
      type: expect
      match: rstatus
      pattern: (2|3)[0-9][0-9]
      index: 1

I am able to apply the config but ingress controller is having error logs with message as below:

2023/02/21 13:45:02 ERROR   ingress/ingress.go:251 Ingress 'prod/test-svc': 14: validation failure list:
validation failure list:
index in body is required

Also, cant find a better documentation of it, in case i want to apply multiple http checks how can i do it, because object does not seems to be of array type.

**Comment by ivanmatmati** [comment]
Hi @sudrishi0512 , Thanks for reporting, I'll check with the team why this field is mandatory.

**Comment by sudrishi0512** [comment]
Hi @ivanmatmati any ETA for the same, can you provide some examples for using http-checks meanwhile?

**Comment by seymurOps** [comment]
Hi. Any updates? Got same issue.
    http-check:
      type: "expect"
      index: 1
      match: "string"
      pattern: "free"
      error_status: "L7RSP"
      ok_status: "L7OK"
