### ISSUE TITLE
multiple 80 and 443 backned

### ISSUE THREAD

**Issue by crawe1** [haproxytech/kubernetes-ingress#527]
Hi,
It is possible to add twice backend on this same domain and this same path but different ports 80 and 443. I see only one last backend used in configs.

ingress onfig:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: apache
  annotations:
    ingress.kubernetes.io/use-proxy-protocol: "true"
    ingress.kubernetes.io/proxy-protocol: "v2"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts: 
    - domain.pl
    - www.domain.pl
    - "*.domain.pl"
    secretName: cert.domain.pl
  rules:
  - host: "domain.pl"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-domain
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-domain-ssl
            port:
              number: 443
              
 from kubernetes cluster 
![image](https://user-images.githubusercontent.com/61950059/223093829-254c6fad-022a-4aab-a7c6-10aa92c70100.png)

from stats 
![image](https://user-images.githubusercontent.com/61950059/223094221-753c863d-b8b6-4f29-a625-2965457c1f46.png)

I can't add this twice rules on haproxy every time is visible in haproxy last backend of manifest config this same domain.

**Comment by ivanmatmati** [comment]
Hi @crawe1 , I'll check that.

**Comment by ivanmatmati** [comment]
Hi @crawe1 , Indeed at the moment you have to separate the two definitions in two different ingresses to make this works. I'll check the code to see if there's a specific reason for that. In the meantime you can use the above solution. Thanks for reporting.

**Comment by crawe1** [comment]
@ivanmatmati 
thank you for your response !
