### ISSUE TITLE
haproxy 1.9.6 crash due to default-local-service

### ISSUE THREAD

**Issue by CnxAdmin** [haproxytech/kubernetes-ingress#535]
Hello,

We have tried upgrading haproxy to latest availabe version and we are facing a very strange issue, the process crashes, please see below:

`global.go:244 default service: service 'haproxy-internal/default-local-service' does not exist`

We don't have such service in any of our k8s namespaces, and strangely this issue occurs. I have to mention that we haven't changed anything on the controller, and we are using the official helm haproxytech charts.

**Comment by ivanmatmati** [comment]
Hi @CnxAdmin , can you confirm that you've got a crash ? I  can see the message but then an update happens and all is correct.

**Comment by ivanmatmati** [comment]
Hi @CnxAdmin , As there's a six seconds interval between the error message and the stop, I guess they're not strongly related. Anyway I'll issue a change to get rid of this disturbing message. Can you rerun with log level set to debug ? You can change it in the arguments of controller (i.e. Deployment). There's a `--log` option.

**Comment by ivanmatmati** [comment]
Can you also check the events in your cluster ? There could be an external reason which simply kills the controller.
