### ISSUE TITLE
Annotation "server-ca" does not work (invalid configuration, ingress controller stuck until removed)

### ISSUE THREAD

**Issue by remram44** [haproxytech/kubernetes-ingress#542]
I am using `haproxy.org/server-ssl=true` and `haproxy.org/server-ca=ns1/tls-ca`. I am NOT using a client certificate; no `server-crt` etc.

When I do this, the configuration is invalid. The ingress does not work, the controller spits errors, and no change to any other ingress or service cluster-wide works until I roll back the change to this ingress (cluster-wide denial of service in a multi-tenant cluster)

```
2023/05/30 20:28:48 ERROR   controller.go:144 unable to Sync HAProxy configuration !!
2023/05/30 20:28:48 ERROR   controller.go:145 14: err transactionId=44cd4683-f66e-47f4-8820-db44a308db89
msg="config [/etc/haproxy/haproxy.cfg.44cd4683-f66e-47f4-8820-db44a308db89:140] 'server ns1_myingress_https/SRV_1' verify is enabled by default but no CA file specified. If you're running on a LAN where you're certain to trust the server's certificate, please set an explicit 'verify none' statement on the 'server' line, or use 'ssl-server-verify none' in the global section to disable server-side verifications by default."
msg="config Fatal errors found in configuration."
```

This is essentially the same issue as #409, there is a workaround there with `backend-config-snippet`, but obviously this is not ideal. I suspect that you tested `server-ca` only with mTLS which is not my situation.

Using 1.10.3

**Comment by ivanmatmati** [comment]
Hi @remram44 , thanks for reporting. I was able to reproduce. You'll be informed of the progress of the fix.

**Comment by ivanmatmati** [comment]
The issue is that a change in the model prevents the ca file to be reflected in the configuration. You can expect a new build by the beginning of the week.

**Comment by ivanmatmati** [comment]
Hi @remram44 , I think you can try the nightly build to see if it solves your issue. To use the nightly just replace the version in your docker image with nightly. This fix will be included in the next official release.

**Comment by remram44** [comment]
Same issue with `haproxytech/kubernetes-ingress:nightly@sha256:0b467644ae9a66d7a5bf9f295e8343e741913646dd355595a765b759e0ddd31a`

**Comment by ivanmatmati** [comment]
Ok, I'll check with the team when it's available. Thanks.

**Comment by martinschmatz** [comment]
Exact same situation here. 

Essentially prevents re-encrypt mode. And causes trouble due to the above mentioned 'cluster wide DoS'.

**Comment by martinschmatz** [comment]
@ivanmatmati Is there any update on when a fix can be available? 

Btw, I'm building from sources using the `Dockerfile` from [here](https://github.com/haproxytech/kubernetes-ingress/blob/master/build/Dockerfile)

**Comment by ivanmatmati** [comment]
Hi, the fix is available in latest version 1.10. Please test it.

**Comment by ivanmatmati** [comment]
Hi, the fix is available in latest version 1.10. Please test it.

**Comment by remram44** [comment]
Do you mean 1.10.4?

**Comment by ivanmatmati** [comment]
Latest is indeed 1.10.4.

**Comment by remram44** [comment]
1.10.4 seems to work, I will deploy. Thanks!

**Comment by martinschmatz** [comment]
I can confirm that 1.10.4 also works for me. 

To be more specific, I've built from sources using commit `402c43c`, which is slightly ahead of 1.10.4.

Many thanks & happy re-encrypt!
