### ISSUE TITLE
Consider making timeout-server available on ingress or service

### ISSUE THREAD

**Issue by remram44** [haproxytech/kubernetes-ingress#543]
See also #347

The only thing left on my whole cluster that has to fallback to backend-config-snippet is `timeout server`. Odly enough, `haproxy.org/timeout-server` exists, but can only be set in the ConfigMap.

The problem with `haproxy.org/backend-config-snippet` is that it is very powerful, and I would like to disable it cluster-wide via a Kyverno policy.

Could we please have timeout-server on Ingress, Service, or both?

**Comment by hdurand0710** [comment]
Hi @remram44 ,

This feature has been included in this [commit](https://github.com/haproxytech/kubernetes-ingress/commit/21ec900476e0b7f34ba7839481f2968b57443fe8).

It will be available in a next release.
Please also note that you will also be able to disable the various config snippets by setting the controller argument `--disable-config-snippets` ([doc](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--disable-config-snippets)).
