### ISSUE TITLE
Resource request limits max cpu core usage

### ISSUE THREAD

**Issue by PKizzle** [haproxytech/kubernetes-ingress#545]
When specifying a CPU resource request of 1 or less the kubernetes-ingress pod will never use more than one CPU core even though there is no CPU resource limit specified. Omitting the resource configuration leads to the expected behavior of taking advantage of all available CPU resources under load.

OS: Raspbian OS 6.1.21-v8+ aarch64 GNU/Linux
kubernetes-ingress version: 1.10.3
k3s version: 1.27.2

**Comment by ivanmatmati** [comment]
Hi @PKizzle , can you test that it's not relative to your installation/OS ? Did you test with other deployments and products ?

**Comment by PKizzle** [comment]
I only have access to my Raspberry Pi cluster (3x Raspberry Pi 4 model B 8GB) at the moment, which are all running the same OS.

**Comment by dkorunic** [comment]
@PKizzle Please if possible provide log lines from the pod that contain strings `maxprocs` and `GOMAXPROCS`.

**Comment by PKizzle** [comment]
I cannot find these in the log. Which log level is required? Or can I somehow get those from the pod shell?

**Comment by dkorunic** [comment]
@PKizzle This would indicate something in your environment is setting up hard CPU quota, namely `limits.cpu` since IC source reads and parses CPU limits from cgroups v1/v2 configuration. In case that only `requests.cpu` has been set, GOMAXPROCS would be left to default (number of logical processors) and GOMAXPROCS message would indicate this being left as is. This message above proves that hard CPU quota has been set for the pod/container.

**Comment by PKizzle** [comment]
Yes, I had a cpu limit set in my configuration, but I only added it for testing purposes.
I still encounter the same strange bevavior as shown below.
In both examples I receive the log message `maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined`.

This is the CPU usage with a CPU and memory request but no limits:
![CleanShot 2023-06-13 at 02 19 34](https://github.com/haproxytech/kubernetes-ingress/assets/39984529/8e614dbc-ff87-477c-9ba8-6b3bc79f8c98)
This is the CPU usage without specifying any resources:
![CleanShot 2023-06-13 at 02 11 26](https://github.com/haproxytech/kubernetes-ingress/assets/39984529/d16ba751-ffa5-4d42-8afe-edff130ddd0b)

**Comment by dkorunic** [comment]
I must observe that this is not a proper way to determine if thread/task scheduler is limiting CPU usage. You are merely observing the current (htop just shows actual information) CPU usage for a single worker in this case which might be receiving more load depending on the nature of your benchmark and lifetime of your HTTP requests. As you can observe in both cases the number of threads is the same and all CPU cores are receiving some tasks depending on Raspbian CPU task scheduler. They might be unbalanced, but again it's depending on the way you are generating and injecting your load *and* CPU task scheduler -- neither of those relates to Ingress Controller. Everything here looks fine.

**Comment by dkorunic** [comment]
To test if many cores are being used, your test should generate sufficient traffic to saturate several cores at once, generated from external load generator. I would suggest using [vegeta](https://github.com/tsenart/vegeta), [wrk2](https://github.com/giltene/wrk2) etc. running from an outside of K8s cluster towards your deployed app through Ingress Controller. Downloading a single file through HAProxy is exactly the wrong type of load-test as expected which can't really show workers utilising many cores and handling many requests in parallel.
