### ISSUE TITLE
API v1alpha1 deprecated but no newer version available

### ISSUE THREAD

**Issue by PKizzle** [haproxytech/kubernetes-ingress#554]
When starting kubernetes-ingress I receive the error message:
`Global CR defined in API core.haproxy.org/v1alpha1 is DEPRECATED, please upgrade`

However, the latest version of the official helm chart still ships with API version v1alpha1.

**Comment by ivanmatmati** [comment]
Hi @PKizzle , Can you report this issue in the [Helm Chart repository](https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress) ?
