### ISSUE TITLE
HAProxy periodic reload without configuration change

### ISSUE THREAD

**Issue by avachette** [haproxytech/kubernetes-ingress#559]
Hi,

I would like to know if it's a known behavior that HAProxy ingress gateway are reloaded many times without configuration change.

We are using HAProxy ingress version 1.10.5.

Here is an excerpt of the behavior:

```
avachette@kube-01 ~ ❱ sudo kubectl exec -it haproxy-ingress-kubernetes-ingress-8bf84c4cf-5xmrv -n haproxy-ingress -- sh -c "cat /etc/haproxy/haproxy.cfg" > haproxy.1
avachette@kube-01 ~ ❱ sudo kubectl exec -it haproxy-ingress-kubernetes-ingress-8bf84c4cf-5xmrv -n haproxy-ingress -- sh -c "cat /etc/haproxy/haproxy.cfg" > haproxy.2
```

The diff is done after two reload because sometimes reload can be very quick:
```
avachette@kube-01 ~ ❱ diff haproxy.1 haproxy.2
1c1
< # _version=27
---
> # _version=29
```

I don't especially see a noisy ressources which can lead to this kind of issue.

Kubernetes version is 1.24.14

Help is appreciated.

I can share more information if needed.

Regards,

**Comment by ivanmatmati** [comment]
Hi @avachette , If you set the log to debug level you should see what is causing the reload. First, set the log parameter to debug in the `args` section of your controller in the yaml file of your deployment. It should be like this:
```
--configmap=xxx/xxxxx
--log=debug
```
Then a message with "... reload required" should appear before any reload.

**Comment by avachette** [comment]
Hi @ivanmatmati,

Thank you for your quick answer.

We needed to test things with debug and then trace output.

To check that the regression was not introduced on 1.10.x release we downgraded the version to 1.9 also.

We are also aware that following action will reload HAProxy configuration:
- Add/Change/Delete a frontend
- Add/Change/Delete a backend
- Change default backend
- Scale up toward the default limit of (42 by default) on a specific backend

Here is the trace output for the vaquinha service:
2023/08/02 13:41:55 TRACE   store/events.go:98 Treating endpoints event {SliceName:vaquinha-h5gxq Namespace:ops Service:vaquinha Ports:map[http:0xc000681440] Status:MODIFIED}
2023/08/02 13:41:55 TRACE   store/events.go:102 service vaquinha : endpoints list map[http:{Port:8080 Addresses:map[10.0.12.198:{} 10.0.3.135:{}]}]
2023/08/02 13:41:55 TRACE   store/events.go:107 service vaquinha : number of already existing backend(s) in this transaction for this endpoint: 1
2023/08/02 13:41:55 TRACE   store/events.go:109 service vaquinha : port name http, backend {Name:ops_vaquinha_http HAProxySrvs:[{Name:SRV_1 Address:10.0.3.135 Modified:false Port:0} {Name:SRV_2 Address: Modified:false Port:0} {Name:SRV_3 Address: Modified:false Port:0} {Name:SRV_4 Address: Modified:false Port:0} {Name:SRV_5 Address: Modified:false Port:0} {Name:SRV_6 Address: Modified:false Port:0} {Name:SRV_7 Address: Modified:false Port:0} {Name:SRV_8 Address: Modified:false Port:0} {Name:SRV_9 Address: Modified:false Port:0} {Name:SRV_10 Address: Modified:false Port:0} {Name:SRV_11 Address: Modified:false Port:0} {Name:SRV_12 Address: Modified:false Port:0} {Name:SRV_13 Address: Modified:false Port:0} {Name:SRV_14 Address: Modified:false Port:0} {Name:SRV_15 Address: Modified:false Port:0} {Name:SRV_16 Address: Modified:false Port:0} {Name:SRV_17 Address: Modified:false Port:0} {Name:SRV_18 Address: Modified:false Port:0} {Name:SRV_19 Address: Modified:false Port:0} {Name:SRV_20 Address: Modified:false Port:0} {Name:SRV_21 Address: Modified:false Port:0} {Name:SRV_22 Address: Modified:false Port:0} {Name:SRV_23 Address: Modified:false Port:0} {Name:SRV_24 Address: Modified:false Port:0} {Name:SRV_25 Address: Modified:false Port:0} {Name:SRV_26 Address: Modified:false Port:0} {Name:SRV_27 Address: Modified:false Port:0} {Name:SRV_28 Address: Modified:false Port:0} {Name:SRV_29 Address: Modified:false Port:0} {Name:SRV_30 Address: Modified:false Port:0} {Name:SRV_31 Address: Modified:false Port:0} {Name:SRV_32 Address: Modified:false Port:0} {Name:SRV_33 Address: Modified:false Port:0} {Name:SRV_34 Address: Modified:false Port:0} {Name:SRV_35 Address: Modified:false Port:0} {Name:SRV_36 Address: Modified:false Port:0} {Name:SRV_37 Address: Modified:false Port:0} {Name:SRV_38 Address: Modified:false Port:0} {Name:SRV_39 Address: Modified:false Port:0} {Name:SRV_40 Address: Modified:false Port:0} {Name:SRV_41 Address: Modified:false Port:0} {Name:SRV_42 Address: Modified:false Port:0}] Endpoints:{Port:8080 Addresses:map[]} DynUpdateFailed:false}
2023/08/02 13:41:55 TRACE   api/runtime.go:86 updating backend  ops_vaquinha_http for haproxy servers update (address and state) through socket
2023/08/02 13:41:55 TRACE   api/runtime.go:89 backend ops_vaquinha_http: list of servers [{Name:SRV_1 Address:10.0.3.135 Modified:false Port:0} {Name:SRV_2 Address: Modified:false Port:0} {Name:SRV_3 Address: Modified:false Port:0} {Name:SRV_4 Address: Modified:false Port:0} {Name:SRV_5 Address: Modified:false Port:0} {Name:SRV_6 Address: Modified:false Port:0} {Name:SRV_7 Address: Modified:false Port:0} {Name:SRV_8 Address: Modified:false Port:0} {Name:SRV_9 Address: Modified:false Port:0} {Name:SRV_10 Address: Modified:false Port:0} {Name:SRV_11 Address: Modified:false Port:0} {Name:SRV_12 Address: Modified:false Port:0} {Name:SRV_13 Address: Modified:false Port:0} {Name:SRV_14 Address: Modified:false Port:0} {Name:SRV_15 Address: Modified:false Port:0} {Name:SRV_16 Address: Modified:false Port:0} {Name:SRV_17 Address: Modified:false Port:0} {Name:SRV_18 Address: Modified:false Port:0} {Name:SRV_19 Address: Modified:false Port:0} {Name:SRV_20 Address: Modified:false Port:0} {Name:SRV_21 Address: Modified:false Port:0} {Name:SRV_22 Address: Modified:false Port:0} {Name:SRV_23 Address: Modified:false Port:0} {Name:SRV_24 Address: Modified:false Port:0} {Name:SRV_25 Address: Modified:false Port:0} {Name:SRV_26 Address: Modified:false Port:0} {Name:SRV_27 Address: Modified:false Port:0} {Name:SRV_28 Address: Modified:false Port:0} {Name:SRV_29 Address: Modified:false Port:0} {Name:SRV_30 Address: Modified:false Port:0} {Name:SRV_31 Address: Modified:false Port:0} {Name:SRV_32 Address: Modified:false Port:0} {Name:SRV_33 Address: Modified:false Port:0} {Name:SRV_34 Address: Modified:false Port:0} {Name:SRV_35 Address: Modified:false Port:0} {Name:SRV_36 Address: Modified:false Port:0} {Name:SRV_37 Address: Modified:false Port:0} {Name:SRV_38 Address: Modified:false Port:0} {Name:SRV_39 Address: Modified:false Port:0} {Name:SRV_40 Address: Modified:false Port:0} {Name:SRV_41 Address: Modified:false Port:0} {Name:SRV_42 Address: Modified:false Port:0}]
2023/08/02 13:41:55 TRACE   api/runtime.go:90 backend ops_vaquinha_http: list of endpoints addresses map[10.0.12.198:{} 10.0.3.135:{}]
2023/08/02 13:41:55 TRACE   api/runtime.go:117 backend ops_vaquinha_http: list of servers after treatment  [{Name:SRV_1 Address:10.0.3.135 Modified:false Port:0} {Name:SRV_2 Address:10.0.12.198 Modified:true Port:0} {Name:SRV_3 Address: Modified:true Port:0} {Name:SRV_4 Address: Modified:true Port:0} {Name:SRV_5 Address: Modified:true Port:0} {Name:SRV_6 Address: Modified:true Port:0} {Name:SRV_7 Address: Modified:true Port:0} {Name:SRV_8 Address: Modified:true Port:0} {Name:SRV_9 Address: Modified:true Port:0} {Name:SRV_10 Address: Modified:true Port:0} {Name:SRV_11 Address: Modified:true Port:0} {Name:SRV_12 Address: Modified:true Port:0} {Name:SRV_13 Address: Modified:true Port:0} {Name:SRV_14 Address: Modified:true Port:0} {Name:SRV_15 Address: Modified:true Port:0} {Name:SRV_16 Address: Modified:true Port:0} {Name:SRV_17 Address: Modified:true Port:0} {Name:SRV_18 Address: Modified:true Port:0} {Name:SRV_19 Address: Modified:true Port:0} {Name:SRV_20 Address: Modified:true Port:0} {Name:SRV_21 Address: Modified:true Port:0} {Name:SRV_22 Address: Modified:true Port:0} {Name:SRV_23 Address: Modified:true Port:0} {Name:SRV_24 Address: Modified:true Port:0} {Name:SRV_25 Address: Modified:true Port:0} {Name:SRV_26 Address: Modified:true Port:0} {Name:SRV_27 Address: Modified:true Port:0} {Name:SRV_28 Address: Modified:true Port:0} {Name:SRV_29 Address: Modified:true Port:0} {Name:SRV_30 Address: Modified:true Port:0} {Name:SRV_31 Address: Modified:true Port:0} {Name:SRV_32 Address: Modified:true Port:0} {Name:SRV_33 Address: Modified:true Port:0} {Name:SRV_34 Address: Modified:true Port:0} {Name:SRV_35 Address: Modified:true Port:0} {Name:SRV_36 Address: Modified:true Port:0} {Name:SRV_37 Address: Modified:true Port:0} {Name:SRV_38 Address: Modified:true Port:0} {Name:SRV_39 Address: Modified:true Port:0} {Name:SRV_40 Address: Modified:true Port:0} {Name:SRV_41 Address: Modified:true Port:0} {Name:SRV_42 Address: Modified:true Port:0}]
2023/08/02 13:41:55 TRACE   api/runtime.go:118 backend ops_vaquinha_http: list of endpoints addresses after treatment  map[]
2023/08/02 13:41:55 TRACE   api/runtime.go:131 backend ops_vaquinha_http: server 'SRV_2' changed status to ready
[WARNING]  (1320) : Server ops_vaquinha_http/SRV_2 is UP/READY (leaving forced maintenance).
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_3' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_4' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_5' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_6' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_7' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_8' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_9' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_10' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_11' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_12' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_13' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_14' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_15' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_16' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_17' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_18' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_19' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_20' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_21' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_22' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_23' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_24' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_25' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_26' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_27' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_28' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_29' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_30' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_31' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_32' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_33' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_34' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_35' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_36' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_37' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_38' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_39' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_40' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_41' changed status to maint
2023/08/02 13:41:55 TRACE   api/runtime.go:127 backend ops_vaquinha_http: server 'SRV_42' changed status to maint
2023/08/02 13:41:58 TRACE   controller.go:94 HAProxy config sync started

Backend modification are directly interacting with the UNIX socket and should be enforced by the `--cache-resync-period)` directive based on our comprehension but not just after the UNIX socket operation.

Or maybe I'm missing a part of te puzzle here?

Regards,

**Comment by ivanmatmati** [comment]
Hi @avachette , I'll check that part. Do you have any evidence about that in logs ?

**Comment by avachette** [comment]
Hi @ivanmatmati, nope because the function doesn't log anything at the moment.

I can do a patch if you want.

The culprit seems to be there:

- https://github.com/haproxytech/kubernetes-ingress/blob/f6685ce4719d9fbaffc61ec7ec37f2e267aab98a/pkg/handler/pprof.go#L59

Regards,

**Comment by ivanmatmati** [comment]
Hi @avachette , thanks for your digging. Actually this line is necessary, this is not the issue. The issue is that it's not called properly. I'll release a fix for that.

**Comment by avachette** [comment]
Hi @ivanmatmati, thanks for your help/detailed answers. We will wait your fix then.

**Comment by ivanmatmati** [comment]
You can already test it in advance with the nightly build. Just change the version of the image (latest, etc.) to nightly.

**Comment by avachette** [comment]
I will give it a try this evening then.
