### ISSUE TITLE
[Question] arm64 images

### ISSUE THREAD

**Issue by pando85** [haproxytech/kubernetes-ingress#56]
Hey there,

Are you going to support arm64 images?

**Comment by aiharos** [comment]
Hi,

We are not focusing on arm64 at this time as this is not our primary targeted Kubernetes platform. We will keep tracking the interest in arm64 and are open to building images in the future.

Best regards,
Andjelko

**Comment by pando85** [comment]
Thanks, I'm very interest in your work. I will follow your progress.

**Comment by zozo6015** [comment]
I am also interested on having this running on arm64 based cpu's moreover that arm64 seam to be more and more used by hardware manufactures.

**Comment by dkorunic** [comment]
@zozo6015 @pando85 We plan to migrate to multi-arch repo in the very near future. I'll keep the issue open until then.
