### ISSUE TITLE
`syslog-server` does not work when `cr-global` is set

### ISSUE THREAD

**Issue by renchap** [haproxytech/kubernetes-ingress#561]
When you set a global config using `cr-global` in the config map, the `syslog-server` annotation is ignored and the default is used.

After looking at the code, I saw that the `Global` resource accepts a `log_targets` key in addition to `config`, and this key can be used and work fine.

The documentation does not mention this at all, so this needs to be fixed.

You may also want to merge the log targets from `syslog-server` into the targets defined in `Global` to support this use-case, I think it makes sense to do so?

**Comment by ivanmatmati** [comment]
Hi @renchap , I'll look at that one. Thanks for reporting.

**Comment by renchap** [comment]
Controller version: `1.10.6`
Global CRD version: `core.haproxy.org/v1alpha2`

**Comment by fabianonunes** [comment]
Hi,

This issue is mentioned on [CRD documentation](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resources.md):

> Custom resources are meant to **replace annotations** when possible. So they will have precedance when used. Example: if the backend resource is used no backend annotation will be processed which means a backend cannot be configured by mixing both the backend resource and backend annotations.
