### ISSUE TITLE
[Help Needed]::HAProxy Ingress controller rete-limit

### ISSUE THREAD

**Issue by UPADHYA28** [haproxytech/kubernetes-ingress#577]
Hi Team,

I was exploring the capabilities of HAProxy ingress controller. 

I wanted to achieve (for now) limit the number of request to 1 in 1sec.. So i made following configuration `haproxy-kubernetes-ingress` configmap

<pre><code>
> apiVersion: v1
> data:
>   frontend-config-snippet: |
>     stick-table  type ipv4  size 100k  expire 30s  store http_req_rate(1s)
>     http-request track-sc0 src
>     http-request deny deny_status 500 if { sc_http_req_rate(0) gt 1 }
> kind: ConfigMap
> metadata:
>   annotations:
>     meta.helm.sh/release-name: haproxy-kubernetes-ingress
>     meta.helm.sh/release-namespace: haproxy-controller
>   creationTimestamp: "2023-09-13T08:54:25Z"
>   labels:
>     app.kubernetes.io/instance: haproxy-kubernetes-ingress
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: kubernetes-ingress
>     app.kubernetes.io/version: 1.7.6
>     helm.sh/chart: kubernetes-ingress-1.20.0
>   name: haproxy-kubernetes-ingress
>   namespace: haproxy-controller
>   resourceVersion: "1301337"
> 
</code></pre>

`But this doesn't work as expected. Even if i make more than 1 req in 1sec window it allows the request to reach backend.

Can anyone help me to correct my direction to achieve the desired result?

I understand there are annotations to achieve rate-limit. But as mentioned earlier as of now i want to achieve this and later instead of ipv4 address as the key, i would be wanting to replace it with some custom key which can be found in request header.

**Comment by ivanmatmati** [comment]
Hi @UPADHYA28, How many instances of the ingress controller are you running ? Be aware that a cluster-wide tracking needs an enterprise feature called stick table aggregator. Otherwise all the tables are local to their instances and are not aware of the others.

**Comment by ivanmatmati** [comment]
Closing the issue because of inactivity. Feel free to reopen if you need.
