### ISSUE TITLE
documenentation says tht allow-list is avaiblable since 1.10, but it's does not exists in 1.10

### ISSUE THREAD

**Issue by jouve** [haproxytech/kubernetes-ingress#580]
[allow-list](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/ingress/#allow-list) annotation does nothing.

If I switch back to whitelist , it works again.

the ingress controller is deployed with the helm chart & I reproduce the issue with HAProxy Ingress Controller v1.10.8 & v1.10.9

**Comment by jouve** [comment]
[branch 1.10](https://github.com/haproxytech/kubernetes-ingress/blob/v1.10/pkg/annotations/ingress/accessControl.go) does not yet use allow-list vs [master](https://github.com/haproxytech/kubernetes-ingress/blob/master/pkg/annotations/ingress/accessControl.go) that does

**Comment by oktalz** [comment]
hi, @jouve yes, there is mistake in docs there, docs are a bit in future for this particular feature. 
we need to correct it either by fixing the docs or backporting the change to 1.10

in the meantime you can use `whitelist` instead (we will deprecate it, but it will remain active for multiple versions).

**Comment by magla-cortado** [comment]
Hi, the documentation still mentions "Available since version 1.10" which is not correct :(

**Comment by oktalz** [comment]
we will correct that soon
