### ISSUE TITLE
option to set security context for deployment in helm-chart

### ISSUE THREAD

**Issue by krishau99** [haproxytech/kubernetes-ingress#581]
I want to run the kubernetes-ingress in PSA restricted mode, and as far as I can see there is nothing preventing this, except "allowPrivilegeEscalation" is set to true by default in the deployment.

I can't find any way to set this in the current chart, is it possible to add functionality so that this can be defined as a value in the helm chart?

**Comment by ivanmatmati** [comment]
Hi @krishau99 , please report this question in the ad hoc [repository](https://github.com/haproxytech/helm-charts) for the Helm Chart.
