### ISSUE TITLE
Controller doesn't propagate LB's external IP changes to Ingress address

### ISSUE THREAD

**Issue by vholer** [haproxytech/kubernetes-ingress#582]
Follow up of #526, happens to me still on quite recent controller version 1.10.8.

In our case, we are running an on-commit tests which spawn a single-purpose local Kubernetes clusters (minikube) where Terraform configures everything from scratch. We experience random failures when HAProxy Controller doesn't propagate address from LB Service to Ingress objects it's managing.

See the relevant objects:

```
$ kubectl get services -n haproxy-controller-app
NAME                             TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                     AGE
kubernetes-ingress-app           LoadBalancer   10.98.215.10   10.98.215.10   80:32501/TCP,443:31893/TCP,6060:30410/TCP   125m
kubernetes-ingress-app-metrics   ClusterIP      10.103.84.75   <none>         1024/TCP                                    125m

$ kubectl get ingresses
NAME      CLASS     HOSTS                   ADDRESS   PORTS     AGE
ingress   haproxy   ***obfuscated***                   80, 443   89m
                                            ^^^^^^^^
```

When I switch the `ingress` object above to different IngressClass/controller, it assigns its external IP correctly. If I switch this object back to this broken IngressClass/controller, it drops the IP addresses:

```
2023/10/17 13:03:50 Publish service: haproxy-controller-app/kubernetes-ingress-app
2023/10/17 13:54:11 DEBUG   status/updatestatus.go:67 new ingress status ip address of 'frbit-e2e-appenv-e6167aa0-6401/ingress' will be []
```

I.e., it manages the attribute correctly, but the controller itself doesn't know about its external IP for the publish service! That leads me to a guess that on HAProxy controller start, the publish service didn't have the external IP yet and **after it was assigned, HAProxy controller hasn't noticed that**. It still considers there is none.

This leads me to the code responsible of processing events on PublishService:

https://github.com/haproxytech/kubernetes-ingress/blob/857d0f820b05261491a09057e6fef0549abd3f3e/pkg/store/events.go#L321-L322

and in this function, **`updateRequired` is never set to `true`**. Which I do believe is wrong.

Steps to reproduce:
- start minikube
- don't open tunnel now (`minikube tunnel`), so that LBs don't get external IPs
- install HAProxy Ingress Controller
- double check LB Service for HAProxy doesn't have external IP
- run `minikube tunnel` to open tunnel from host to minikube
- check LB Service for HAProxy now has external IP
- create Ingress with IngressClass of the HAProxy Ingress Controller above
- check the Ingress doesn't have address configured

Helm Chart Version: 1.33.1
Controller Version: 1.10.8

**Comment by ivanmatmati** [comment]
Hi @vholer , thanks for reporting this issue. We'll try to reproduce it and keep you informed.

**Comment by hdurand0710** [comment]
Hi @vholer, 
This commit f329042723e44110f52da9331510f88f9b20c5f7 (and for the branch 1.10 f329042723e44110f52da9331510f88f9b20c5f7, along with 67909dce1b404f479b54ab16c1f794d64f70d35d) should solve your issue.
They will be available in the next releases.

Best regards

**Comment by kutsav** [comment]
Any update when this will be available?
