### ISSUE TITLE
Annotation haproxy.org/route-acl disrupts path resolution when we have many paths for a domain

### ISSUE THREAD

**Issue by Nainterceptor** [haproxytech/kubernetes-ingress#588]
Dear Team,

I am writing to bring to your attention an issue encountered while deploying Grafana alongside Cert-manager with a Let's Encrypt cluster issuer in a Kubernetes cluster. Specifically, the challenge with HTTP01 resolution occurs when attempting to exclude the metrics path from being exposed by the Ingress using the `haproxy.org/route-acl` annotation (`haproxy.org/route-acl: path_reg -i ^/(?!metrics$).*`).

Upon applying this annotation to a service, it appears that the path resolution priority as elucidated in the Kubernetes documentation under "[Multiple Matches](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches)" is disrupted, especially when the Ingress has multiple routes for the same domain.

The Kubernetes documentation specifies a clear priority of path resolution where the longest path has priority in resolution. However, with the `haproxy.org/route-acl` annotation applied, this priority seems to be altered, leading to a failure in the HTTP01 challenge resolution.

This anomaly is causing a significant hurdle in our deployment workflow and I believe it might be a bug or an unintended consequence of the annotation's behavior. I would greatly appreciate your insights or suggestions on how to work around this issue.

Best regards,

**Comment by hdurand0710** [comment]
@Nainterceptor , 
Thanks for reporting this issue. We are working on it and come back to you as soon as possible.

**Comment by hdurand0710** [comment]
The documentation has been updated (6ddc870ecaa20321e30e3c12b5207cc2770e7936) to clarify the behavior.

Best regards
