### ISSUE TITLE
Tcp log format release

### ISSUE THREAD

**Issue by aimbot31** [haproxytech/kubernetes-ingress#591]
Hello,

just wanted to know when this feature (https://github.com/haproxytech/kubernetes-ingress/commit/10faae71250eafb5e679bf8d5ad56ae70bec15fc) will be included inside next release ?

Related to #591

**Comment by ivanmatmati** [comment]
Hi @aimbot31 , the next release is scheduled for february 2024. In the meantime you can test/use the feature by setting the version of your docker image to `nightly`. This version comprises the latest code built each 24 hrs.
