### ISSUE TITLE
Global option `tune_ssl_default_dh_param` has no effect

### ISSUE THREAD

**Issue by npdgm** [haproxytech/kubernetes-ingress#597]
Setting option `tune_ssl_default_dh_param` in a Global object should alter the value of the default `tune.ssl.default-dh-param 2048`.
It seems this option has no effect on the configuration file which always sticks to 2048.

**Comment by ivanmatmati** [comment]
Hi @npdgm , please replace 
```
    tune_ssl_default_dh_param: xxx
```
with 
```
    tune_options:
      ssl_default_dh_param: xxx
```
Anyway there could be bug or a duplicate so we'll check.

**Comment by ivanmatmati** [comment]
Hi @npdgm , the bug has been fixed and will be released in the next version. You can test it in the nightly build by replacing the version/latest in your deployment file with nightly
