### ISSUE TITLE
default-local-service_http error setting check: true on cr-backend

### ISSUE THREAD

**Issue by Roxyrob** [haproxytech/kubernetes-ingress#600]
My Ingress works fine but inside **haproxy log** I see these **errors** I think becoming  by "**ssl**" and "**check**" enabled with **cr-backend**:
<pre>
[WARNING]  (9031) : Server ingress-haproxy-internal_default-local-service_http/SRV_1 is DOWN,
                    reason: Layer6 timeout, check duration: 2000ms.
                    0 active and 0 backup servers left.
                    0 sessions active, 0 requeued, 0 remaining in queue.

[ALERT]    (9031) : backend 'ingress-haproxy-internal_default-local-service_http' has no server available!

Server ingress-haproxy-internal_default-local-service_http/SRV_1 is DOWN,
reason: Layer6 timeout, check duration: 2000ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
backend ingress-haproxy-internal_default-local-service_http has no server available!

error when serving connection "127.0.0.1:6061"<->"127.0.0.1:47218":
error when reading request headers: cannot find http request method in "\x16\x03\x01\x02\x00\x01\x00\x..."
</pre>

I enabled "**ssl**" and "**check**" using **cr-backend** CRD and defined Ingress as below:
<pre>
---
apiVersion: "core.haproxy.org/v1alpha2"
kind: Backend
metadata:
  name: haproxy-cr-backends
  namespace: ingress-haproxy-internal
spec:
  config:
    balance:
      algorithm: "leastconn"
    mode: "http"
    abortonclose: "disabled"
    default_server:
      ssl: "enabled"
      verify: "none"
      check: "enabled"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-haproxy-internal
  namespace: default
spec:
  ingressClassName: haproxy-internal
  tls:
    - hosts:
        - argocd.example.com
  rules:
    - host: argocd.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-argocd-ui
                port:
                  name: svc-port
</pre>

Using cr-backend "ssl" and "check" configurations will be applied on each backends.
As documentation says using Ingress or Service annotations it is possible to set **specific cr-backend** for Ingress/Service, but how I can avoid these errors becoming from **default-local-service_http service** managed by the HAProxy ingress controller ?

**PS**: to simplifying backends configuration independency for Ingress Controller , do you have plan to support backend **server** configurations based on **ingress paths** ?

**Comment by Roxyrob** [comment]
I found a solution defining **backends configuration with annotation**: ["Available annotations"](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md) for specific Service (or entire Ingress) needing ssl connection to backend ("default-local-service_http service" would not be modified in both cases):

e.g. 
<pre>
kind: Service
apiVersion: v1
metadata:
  name: ingress-argocd-ui
  annotations:
    haproxy.org/check: "true"
    haproxy.org/server-ssl: "true"
...
</pre>

And following documentation about CRD: [Custom Resources](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resources.md) that says: "... if the backend resource is used no backend annotation will be processed which means a backend cannot be configured by mixing both the backend resource and backend annotations.", I also deleted defined **cr-backend** and removed annotation "cr-backend:" from haproxy configuration ConfigMap that was **masking out** all "annotations based configurations".

Probably something can be written on annotation page about CRD completely hiding Annotations, to simplify doc.
Annotations for my specific case seem to provide less configuration granularity than cr-backend.
For example "**server-ssl: true**" set all together:
<pre>
default-server check ssl alpn h2,http/1.1 verify none
</pre>

Apparently not allowing to set "**check**", "**ssl**" and "**verify**" separately. Being CRD and Annotations mutually exclusive, it be probably better to allow equal configuration options between these two configuration methods.

**Comment by ivanmatmati** [comment]
Hi @Roxyrob , did you try the CR backend at ingress level ?

**Comment by oktalz** [comment]
hi @Roxyrob 
> Probably something can be written on annotation page about CRD completely hiding Annotations, to simplify doc.

this seems like a good improvement we could add to the docs.

**Comment by Roxyrob** [comment]
> Hi @Roxyrob , did you try the CR backend at ingress level ?

 From documentation It seems that on haproxy configuration ConfigMap cr-backend can use only one Backend resource (ingress controller wide).

Can you point me to an example to use "CR backend at ingress level" ?

**Comment by ivanmatmati** [comment]
Hi @Roxyrob , you can find mention of it [there](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resources.md#backend). The difference is simple you simply apply the same annotation to the ingress instead of the configmap.
