### ISSUE TITLE
Default certificate does not exist

### ISSUE THREAD

**Issue by Roxyrob** [haproxytech/kubernetes-ingress#601]
On haproxy ingress controller v1.10.10 I get this error in logs:

<pre>
ERROR global.go:272 default certificate: annotation 'ssl-certificate': secret 
'namespace/namespace-default-cert' does not exist
</pre>

namespace is custom namespace (not default).

I cannot use this ingress controller in https.
If I manually create requested certificate that controller will remove it.

Sometimes ingress controller seems to deploy and auto create default certificates, with the same ingress configuration.

I know I can create custom one, but I need to know how haproxy ingress controller check and choose to create or not its default certificate to support tls without custom one ?

**Comment by ivanmatmati** [comment]
Ok, the controller doesn't manage the lifecycle of default certificates. It's handled by Helm charts. I suggest that you ask in their [repository](https://github.com/haproxytech/helm-charts), you'll get an answer.

**Comment by Roxyrob** [comment]
Until this issue is identified and resolved I found a WORKAROUND that seems stable enough.<br/>

Following this link: [Haproxy document SSL / TLS](https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/terminate-ssl/)

   1. Manually create a certificate
<pre>
openssl req -x509 -newkey rsa:2048 -keyout example.key -out example.crt -days 365 -nodes -subj "/C=US/ST=Ohio/L=Columbus/O=MyCompany/CN=example.com"
</pre>
   
   3. Manually create a secret
<pre>
kubectl create secret tls haproxytempcert --cert="example.crt" --key="example.key"
</pre>

   4. Temporary Change haproxy ingress ConfigMap
<pre>
     kubectl edit configmap -n {namespace} {configmap_name}

       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: ...
         namespace: ...
       data:
	 ...
         ssl-certificate: "default/haproxytempcert"    <b><===  (Add) </b>
    </pre>

Doing this seems "to wakeup" ingress controller that create default cert using haproxytempcert.
Default certificate now exists  and contains my Self Signed certificate.
Now I can:

   4. Delete "ssl-certificate" from ConfigMap
<pre>
     kubectl edit configmap -n {namespace} {configmap_name}

       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: ...
         namespace: ...
       data:
         ...
    </pre>

  5. Delete secret
<pre>
kubectl delete secret haproxytempcert
</pre>

Default certificate survive and now contains default haproxy Self-Signed certificate.
What one expect from start.

**Comment by Roxyrob** [comment]
Hi @ivanmatmati,
I'll ask in helm chart repo also if the deployment process is the same for times when default certificate is created and times is not.

Thank you

**Comment by dkorunic** [comment]
Noop, Helm Chart seems correct and this is not related to Ingress Controller either.
