### ISSUE TITLE
[Stats Question] Possible to configure as backend instead of frontend?

### ISSUE THREAD

**Issue by mecampbellsoup** [haproxytech/kubernetes-ingress#614]
We would like to call `stats enable` and the other stats-related configuration inside of an HAProxy _backend_.

It seems like the IC always generates a frontend configuration however:

```haproxy
frontend stats
  mode http
  bind *:1024 name stats
  bind :::1024 name v6
  stats enable
  stats uri /
  stats refresh 10s
  http-request set-var(txn.base) base
  http-request use-service prometheus-exporter if { path /metrics }
```
Is there a reason it's always injected as a frontend configuration?

In our case, we use HAProxy IC as an API Gateway within our shared k8s cluster, and so we'd like to use the same authorization patterns that we use for other downstream (upstream?) applications that sit behind the gateway, namely `lua.cached-auth` (our custom Lua auth script/program).

**Comment by mecampbellsoup** [comment]
@Mo3m3n additionally would it be possible to _disable_ the default `frontend stats`? Then I could just use my own backend as normal (via an `Ingress`).

**Comment by ivanmatmati** [comment]
Hi @mecampbellsoup , the stats frontend can't be disabled. If you want to create your backend, you can. By default our script create a service to point to the controller. Your ingress only has to point to it.

**Comment by ivanmatmati** [comment]
You have several options. Among them, you can secure the ingress with [authentication](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#auth-type) or with [allow](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#whitelist) and deny lists of IPs or CIDRs.

**Comment by mecampbellsoup** [comment]
> You have several options. Among them, you can secure the ingress with [authentication](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md?rgh-link-date=2024-02-21T08%3A35%3A57Z#auth-type) or with [allow](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md?rgh-link-date=2024-02-21T08%3A35%3A57Z#whitelist) and deny lists of IPs or CIDRs.

Cool, haven't used allow/deny lists yet! Thanks for the tip.

Is it possible to generate those dynamically to express something like "only people (IPs) with access to our private internal network can access the stats backend"?

**Comment by fo511** [comment]
Hello. I'd like to get some advice if possible.
We have the same situation when ingress controller has public IP.
So stats frontend is always listening outside on port 1024 and I don't see any option not to publish it outside or changing bind ip or add authentication to it.
So how to correctly secure this endpoint?

**Comment by mecampbellsoup** [comment]
> Hello. I'd like to get some advice if possible. We have the same situation when ingress controller has public IP. So stats frontend is always listening outside on port 1024 and I don't see any option not to publish it outside or changing bind ip or add authentication to it. So how to correctly secure this endpoint?

Are you using the Helm chart? If so, your best bet would be to use a separate k8s service that is not public. See: https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/controller-service-metrics.yaml#L17-L30

**Comment by fo511** [comment]
@mecampbellsoup thank you. that is exactly what I need.
