### ISSUE TITLE
HAProxy Cache

### ISSUE THREAD

**Issue by blop** [haproxytech/kubernetes-ingress#615]
Hello,

Is there any intent to support using the caching feature of HAProxy through the kubernetes-ingress ?
https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#6
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/network-performance/caching/

Maybe there is some workaround currently using snippets ?

Thanks!

**Comment by metroidprototype** [comment]
Right now you can do this with an aux config file in your controller config combined with a `backend-config-snippet` on your service/ingress. The example [here](https://www.haproxy.com/documentation/kubernetes-ingress/ingress-tutorials/auxiliary-config-file/#primary-and-auxiliary-configuration-files) has specific steps to setup a cache and then make use of it.

**Comment by blop** [comment]
Alright, thank you for the example :)
