### ISSUE TITLE
certificate x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by agonzalezm** [haproxytech/kubernetes-ingress#618]
We are trying to deploy haproxy ingress in AKS private cluster but get this error, any idea what is problem? we can pull other containers from microsoft mcr:

![image](https://github.com/haproxytech/kubernetes-ingress/assets/2251991/9013fe1d-25b2-4af8-a196-9a9b6e903a98)

is there any param to helm to install with insecure certs? i dont know why this is giving this error but in other public aks cluster is installing ok.

**Comment by ivanmatmati** [comment]
Hi @agonzalezm , please report your issue in the ad hoc [repository](https://github.com/haproxytech/helm-charts) for Helm charts. Thanks for reporting.
