### ISSUE TITLE
DOC: Remove link to 'external mode' blog post

### ISSUE THREAD

**Issue by NickMRamirez** [haproxytech/kubernetes-ingress#623]
On https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/doc.yaml#L313 

there is a link to the blog:

```
[announcement blog post](https://www.haproxy.com/blog/announcing-haproxy-kubernetes-ingress-controller-1-5/#external-ingress-controller)
```

I think we should remove this link, because:

* Version 1.5 is an older release
* The user can find info about external mode from the official docs
* When we convert this YAML to HTML on haproxy.com/documentation, we strip out all links from doc.yaml (because some links in the doc.yaml are relative links that point to markdown files on GitHub, and those are broken links for us, so we just strip out all links). So this link is also stripped out.

**Comment by oktalz** [comment]
agreed
