### ISSUE TITLE
FR: slowstart in annotations

### ISSUE THREAD

**Issue by ShadowJonathan** [haproxytech/kubernetes-ingress#625]
We might be interested in adding slow startup to each go our backends, given some performance hints, however, we can't find any mention on how to add this to backends, via ingress annotations, even though there is some mention of it in the codebase.

Could this be added, so that slow start can be defined for each (new and recovering) pod?

**Comment by ivanmatmati** [comment]
Hi @ShadowJonathan , what is exactly the piece of code you refer to ?

**Comment by ShadowJonathan** [comment]
https://docs.haproxy.org/2.9/configuration.html#5.2-slowstart

**Comment by ivanmatmati** [comment]
Ok, code from HAProxy is different from the Ingress Controller. Something important to note is `It only applies when a server has been previously seen as failed`. So it shouldn't apply to new pods which brings new server address.
