### ISSUE TITLE
constant prometheus reloading

### ISSUE THREAD

**Issue by darkobas2** [haproxytech/kubernetes-ingress#634]
Hi

I have started getting reloading issue for some reason I cant seem to figure out.

I am on latest chart and it logs this about every 10 minutes and then reloads.
```
2024/03/21 16:08:49 WARNING k8s/crs-deprecated-v2.go:141  Backend CR defined in API core.haproxy.org/v1alpha2 is DEPRECATED, please upgrade
2024/03/21 16:08:49 DEBUG   k8s/crs-deprecated-v2.go:147  default MODIFIED: ingress-am
2024/03/21 16:08:50 INFO    instance/configuration.go:21 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] reload required : creation/modification of prometheus endpoint
2024/03/21 16:08:50 DEBUG   controller.go:142 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] ingress 'default/loki' ignored: no matching
2024/03/21 16:08:50 DEBUG   status/updatestatus.go:67 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] new ingress status ip address of 'default/prometheus' will be [10.233.43.63]
2024/03/21 16:08:50 DEBUG   controller.go:161 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] quic redirect rule to be created
2024/03/21 16:08:50 DEBUG   controller.go:161 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] quic set header rule to be created
2024/03/21 16:08:50 INFO    monitor.go:38 [transactionID=4fe8404a-a8e5-4ff0-bd09-5f872516567d] HAProxy reloaded
```

but nothing seems to really be changing on the cluster that would cause reloads... 

any hints ?

**Comment by ivanmatmati** [comment]
Hi @darkobas2 , Are you using a specific namespace different from `haproxy-controller` ?

**Comment by darkobas2** [comment]
> Hi @darkobas2 , Are you using a specific namespace different from `haproxy-controller` ?

Hi, indeed i am. I am deploying it to default ns

**Comment by darkobas2** [comment]
ok the issue seems to be resolved after i removed old CRS (backends.core.haproxy.org etc.)

**Comment by ivanmatmati** [comment]
Ok, there's a pending PR for this bug. In the meantime if you can you can do two things to solve the issue. First, you can disable prometheus with this boolean set to false in your values.yaml : controller.service.enablePorts.prometheus. Or if you need it you can redeploy your controller in the haproxy-controller namespace.

**Comment by tman5** [comment]
@ivanmatmati I'm having this issue to with helm chart 1.38.4. Tried disabling prometheus like you mention and it just keeps reloading

**Comment by aaronbbrown** [comment]
We're also experiencing this issue (helm chart 1.42). Happy to help debug.
