### ISSUE TITLE
default backend not working when --ingress.class defined

### ISSUE THREAD

**Issue by illping** [haproxytech/kubernetes-ingress#635]
I just pulled down v1.10.11 and when I add --ingress.class to the startup parms the default backend stops working for frontend http/https.  When looking the the haproxy.cfg inside the pod, the default_backend parm is getting set to a random service defined in the cluster and not using haproxy-controller_default-local-service_http as expected.  Is the configuration parm needed?  It works as expected when the ingress.class is not set

**Comment by ivanmatmati** [comment]
What is the configuration of your ingress controller ? What are the args in the yaml ?
