### ISSUE TITLE
docs: `haproxy.org/server-ssl` tip is misleading

### ISSUE THREAD

**Issue by Karitham** [haproxytech/kubernetes-ingress#637]
Hi, I was recently setting up a service that terminated tls by itself. I was having trouble and fucked around with this setting.

The tip says `Enable HTTP/2 support for backend severs.`, which is surely not what this entries does.

https://github.com/haproxytech/kubernetes-ingress/blob/f8e12cd8027bd0576d97b3884af1e3188a6765a6/documentation/doc.yaml#L1514

I still do not understand what it does so I can't fix it.

**Comment by ivanmatmati** [comment]
Hi @Karitham , Can you exactly explain what is misleading ?The tip says that it enables HTT2 support for backend servers which it does. If I take two examples without and with the annotation set, you've got:
```
backend XXXX
  mode http
  balance roundrobin
  option forwardfor
  no option abortonclose
  timeout server 50000
  default-server check
  server SRV_1 10.244.0.8:80 enabled
  server SRV_2 127.0.0.1:80 disabled
  server SRV_3 127.0.0.1:80 disabled
  server SRV_4 127.0.0.1:80 disabled
```
and 
```
backend XXXX
  mode http
  balance roundrobin
  option forwardfor
  no option abortonclose
  timeout server 50000
  default-server check ssl alpn h2,http/1.1 verify none
  server SRV_1 10.244.0.8:80 enabled
  server SRV_2 127.0.0.1:80 disabled
  server SRV_3 127.0.0.1:80 disabled
  server SRV_4 127.0.0.1:80 disabled
```
