### ISSUE TITLE
Use existing NLB for HAProxy ingress 

### ISSUE THREAD

**Issue by achus-srishti** [haproxytech/kubernetes-ingress#640]
I already have a nlb as part of infrastructure. So is there a way to make haproxy controller service to use that nlb instead of creating another one.

An advantage with this is in case I need to reinstall haproxy controller due to some reason, nlb url will remain same and hence wont affect my other services reaching out to this eks.

**Comment by oktalz** [comment]
hi @achus-srishti it seems this question is out of scope of this project unfortunately
