### ISSUE TITLE
http -> https default redirect not working by default

### ISSUE THREAD

**Issue by pasztorl** [haproxytech/kubernetes-ingress#642]
I'm using the latest kubernetes-ingress.
If a http request arrives at :80 to a valid ingress host it redirects to the ingress host:8443.
The 8443 comes from the containerport where the kubernetes-ingress listening. It sould redirect to https://ingresshost without any :port.

At the docs I see that there is a ssl-redirect-port option. It works but i got https://ingresshost:443 if I set this option to 443.
There is a config option for the redirect without port (since the default is 443 at the browsers)?

**Comment by ivanmatmati** [comment]
Hi @pasztorl , We provide the ssl-redirect to redirect to ssl and ssl-redirect-port in case you need to redefine the port because of a different port like you explained. We redirect by default to the container port because it would be strange that with a direct access to haproxy from the cluster you would have to redefine the port because we would redirect to a non existing port. While if you have haproxy behind any middleware with a different port, it makes sense to adjust the redirection port in this case.

**Comment by pasztorl** [comment]
Hi @ivanmatmati , I understand it, and i think this option is important, but there is a way not to add :443 if the port is default https? I also forward the logs to a logdb and this case I have entries to example.com and example.com:443 from the redirects. Of course I can rewrite the log entry and delete the :443 but it would be better that the location sent out not contains the :443. There is a chance to configure that via haproxy?

**Comment by ocdi** [comment]
This seems plain wrong to me. I shelled into the container and looked at the config, and I can see this line.

```
/etc/haproxy $ cat haproxy.cfg|grep 8443
  http-request redirect location https://%[hdr(host),field(1,:)]:8443%[capture.req.uri] code 302 if { var(txn.path_match) -m dom 92afcf7456e1a884dd198b1f8bfb6f63 }
```

I recently upgraded and are getting customer reports of this issue. This is standard web traffic, the redirect is going over the wire, outside the cluster. The controller has a load balancer service that is running on port 443, that internally goes to the 8443 port.

**Comment by ocdi** [comment]
I was able to solve this by applying the port override to the helm chart.
```yaml
name: controller.config.ssl-redirect-port
value: '443'
```

**Comment by pasztorl** [comment]
@ocdi yes, that is a solution, but.. the problem is that the sent out request use: https://xxx:443 and because of this the redirect location and the access log contains the :443 string. What I want to achieve that if a request goes to ingress to http://xxx the ingress send out the location with https and without port number like this: https://xxx

**Comment by Frankkkkk** [comment]
On top of that, having "sane" defaults like the https port to 443 instead of 8443 would make it easier for everyone IMHO

**Comment by ivanmatmati** [comment]
Hi @Frankkkkk , For security's sake, the ingress controller pod is rootless. The consequence is that the user attributed to the controller can't open ports below 1024. That's the reason for this port change.

**Comment by Frankkkkk** [comment]
I agree, but the SVC forwards 443 to 8443, so you can redirect to Https/443 while keeping a rootless pod

**Comment by Frankkkkk** [comment]
Though it's true that the "sane" default should be on the helm chart instead

**Comment by pasztorl** [comment]
any news on this?

**Comment by mecampbellsoup** [comment]
> I agree, but the SVC forwards 443 to 8443, so you can redirect to Https/443 while keeping a rootless pod
> […](#)
> On 22 May 2024 09:25:37 CEST, ivanmatmati ***@***.***> wrote: Hi @Frankkkkk , For security's sake, the ingress controller pod is rootless. The consequence is that the user attributed to the controller can't open ports below 1024. That's the reason for this port change. -- Reply to this email directly or view it on GitHub: [#642 (comment)](https://github.com/haproxytech/kubernetes-ingress/issues/642#issuecomment-2124057262) You are receiving this because you were mentioned. Message ID: ***@***.***>

i.e. [this approach](https://github.com/kraudcloud/foundations/pull/11/files), right?

**Comment by oekarlsson** [comment]
Changing the value for ssl-redirect-port to 443 works, but I would have preferred a possible value of "none" to just redirect to https without any port.

**Comment by oekarlsson** [comment]
I found a workaround to make the ingress controller redirect to https without adding a port. I simply set ssl-redirect to false and added a frontend config snippet with the http to https redirect I found on haproxy.com. Now it works as I want to. The redirect only changes the scheme. From my helm values file:
```
  controller:
    config:
      ssl-redirect: "false"
      frontend-config-snippet: |
        http-request redirect scheme https unless { ssl_fc }

```

**Comment by HaveFun83** [comment]
@oktalz sorry for the redirect mention, but maybe you can reopen this?
