### ISSUE TITLE
Deployment yaml still point to privileged port after s6 upgrade

### ISSUE THREAD

**Issue by dosmanak** [haproxytech/kubernetes-ingress#643]
After upgrade on to v1.11.2 we noticed the haproxy is not reachable from outside. So we found there has been upgrade of s6 which moved to nonroot container which need non-privileged ports.
The [commit](https://github.com/haproxytech/kubernetes-ingress/commit/e54beaee2260b0531d0749a46e8ab2455a009f7b) ommits the change in deploy manifest.

Also the default setting of `ssl-redirect-port` ceases to be very handful since it now defaults to non-privileged port which is rare on load balancers.

I suggest to change only [targetPort](https://github.com/haproxytech/kubernetes-ingress/blob/e54beaee2260b0531d0749a46e8ab2455a009f7b/deploy/haproxy-ingress-daemonset.yaml#L212) of http and https backends in haproxy service to maintain it as much backwards compatible as possible.

**Comment by ivanmatmati** [comment]
Hi @dosmanak , thanks for reporting, we'll check that.

**Comment by dosmanak** [comment]
The PR has been merged.
