### ISSUE TITLE
Try to understand the mode for tcpcr in 3.0.0 

### ISSUE THREAD

**Issue by cxfcxf** [haproxytech/kubernetes-ingress#658]
https://github.com/haproxytech/kubernetes-ingress/blob/master/pkg/handler/tcp-cr.go#L139
in this code, it forces the frontend to have `mode tcp`

but in the TCP CR doc [here](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/tcps-crd/#mode-version-v3-0)

it is said to allow mode http or tcp in CRD. i am confused here, is that http for something else or its just not implanted?

**Comment by hdurand0710** [comment]
@cxfcxf ,
You are right. We will update the documentation accordingly.
You can use all fields of a client native Backend model, expect the `mode` that is forced to `tcp`. 
The documentation [here]( https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/tcps-crd/#mode-version-v3-0) was auto generated from the Backend model, we should explain that `mode` is not used and if used would we forced to `tcp`.

**Comment by cxfcxf** [comment]
thanks, i m also wondering if there is a plan to support more bind params in http/https handler?

we try to split thread for http and https works, but it seems its not supported.

**Comment by cxfcxf** [comment]
so i sent a PR for the supporting thread pin on http https and healthz which can be helpful for people runnign it as external mode

https://github.com/haproxytech/kubernetes-ingress/pull/661

**Comment by oktalz** [comment]
> thanks, i m also wondering if there is a plan to support more bind params in http/https handler?

yes, ideally we end up with a frontend CRD completely, its in plans
