### ISSUE TITLE
use maps for HTTP routing

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#66]
Hey there,

Currently, the ingress controller creates one use_backend rule + relevant ACLs to route the traffic from HTTP and HTTPs frontends to relevant backends.
This is rock solid, works well but may not perform fast at scale (several hundreds of backends ....).

The idea is to use "maps".
A map in HAProxy is some kind of k/v store: you match a key in a map and you get the value associated to it.
This can apply as simple as this in HAProxy:
```
# host/path    backendName
www.foo.com/app1     namespace-foo-app1
www.foo.com/app2     namespace-foo-app2
www.bar.com/app1     namespace-bar-app1

# host    backendName
app1.foo.com            namespace-foo-app1

# url    backendName
/app2                         namespace-foo-app2
```

Then, in HAProxy, you can do:
```
http-request set-var(req.backend) base,map(mymap)
http-request set-var(req.backend) host,map(mymap) if { var(req.backend),length -eq 0 }
http-request set-var(req.backend) path,map(mymap) if { var(req.backend),length -eq 0 }
http-request set-var(req.backend) str(default_backend) if { var(req.backend),length -eq 0 }
use_backend %[var(req.backend)]
```

Note that the maps can be updated via runtime API so some addition/deletion of routes to existing backends can be done without reloading HAProxy.

Thanks to this trick, we'll have 3 lookups in a tree instead of hundreds or more!

Note the configuration example above can be improved and is opened to comments!

**Comment by prometherion** [comment]
I'd like to work on this: is still opened?

**Comment by Mo3m3n** [comment]
Maps are used for routing starting from 1.5
