### ISSUE TITLE
Not able to setup retry-on functionality globally, I tried multiple values.yaml ! Please correct me if i am wrong ! 

### ISSUE THREAD

**Issue by abhi-gaur** [haproxytech/kubernetes-ingress#663]
#-------------first-Values.yaml-----------------------#

controller:
  ingressClassResource:
    enabled: true
  stats:
    enabled: true
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
    metrics:
      relabelings:
        - replacement: cl1
          targetLabel: cluster
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: hostname
    ctrlMetrics:
      relabelings:
        - replacement: cl1
          targetLabel: cluster
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: hostname
  config:
    timeout-check: 5s
    timeout-client: 50s
    timeout-client-fin: 5s
    timeout-connect: 5s
    timeout-http-request: 5s
    timeout-http-keep-alive: 5s
    timeout-queue: 50s
    timeout-server: 50s
    timeout-server-fin: 5s
    timeout-tunnel: 30m

#-------------------second values.yaml ----------------#
controller:
  ingressClassResource:
    enabled: true
  stats:
    enabled: true
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
    metrics:
      relabelings:
        - replacement: cl1
          targetLabel: cluster
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: hostname
  config:
    retry-on: '503'
    timeout-retries: 50000  # Notice the hyphen here instead of a space

#-------------------third values.yaml --------------------#
controller:
  ingressClassResource:
    enabled: true
  stats:
    enabled: true
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
    metrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
    ctrlMetrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
  config:
    defaults: |
      retries 10  # Increase retries to ensure retry for at least 50 seconds
      option redispatch
      timeout connect 5s  # Timeout for establishing a connection
      timeout queue 60s  # Maximum time to wait in the queue
      timeout server 60s  # Maximum time for a server to respond
    backend: |
      default-server inter 1s fall 3 rise 2
      http-request set-header X-Forwarded-Proto https if { ssl_fc }
    frontend: |
      http-request redirect scheme https if !{ ssl_fc }
    retry-on: |
      5xx 502 503 504 conn-failure empty-response response-timeout

**Comment by ivanmatmati** [comment]
Hi @abhi-gaur , Please repost your issue to the ad hoc repository https://github.com/haproxytech/helm-charts.

**Comment by abhi-gaur** [comment]
Thank you for your response
