### ISSUE TITLE
Use maps for HTTP redirects to HTTPs

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#67]
Hey there,

Currently, the ingress controller creates one http-request redirect rule + relevant ACLs to redirect the traffic from HTTP to HTTPs.
This is rock solid, works well but may not perform fast at scale (several hundreds of redirects ....).

The idea is to use "maps".
A map in HAProxy is some kind of k/v store: you match a key in a map and you get the value associated to it.
This can apply as simple as this in HAProxy:
```
# host/path    backendName
www.foo.com/app1     namespace-foo-app1
www.foo.com/app2     namespace-foo-app2
www.bar.com/app1     namespace-bar-app1

# host    backendName
app1.foo.com            namespace-foo-app1

# url    backendName
/app2                         namespace-foo-app2
```

Then, in HAProxy HTTP frontend only, you can do:
```
http-request set-var(req.redirect) base,map(mymap)
http-request set-var(req.redirect) host,map(mymap) if { var(req.redirect),length -eq 0 }
http-request set-var(req.redirect) path,map(mymap) if { var(req.redirect),length -eq 0 }
http-request redirect scheme https if { var(req.redirect),length -eq 0 }
```

Note that the maps can be updated via runtime API so some addition/deletion of redirects to can be done without reloading HAProxy.

Thanks to this trick, we'll have 3 lookups in a tree instead of hundreds or more!

Note the configuration example above can be improved and is opened to comments!

Part of this work can be is linked to issue #66

**Comment by Mo3m3n** [comment]
Starting from `haproxytech/kubernetes-ingress:1.4.0` maps are used to apply annotations by ingress
