### ISSUE TITLE
feat request: Allow frontend selection annotation for Ingress resource

### ISSUE THREAD

**Issue by mike-code** [haproxytech/kubernetes-ingress#671]
I couldn't find it in the docs, but I assume that k8s `Ingress` resource is always mapped to haproxy default `http` and `https` frontends.

1. I'd like to be able to pin the `Ingress` resource to just `http` or `https`
2. After adding raw frontend snippet and/or custom port, to be able to use `Ingress` resource on that port/frontend as well, without exposing it to the default http/s frontends.

**Comment by mike-code** [comment]
up (remove stale)

**Comment by oktalz** [comment]
hi @mike-code 

with https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--disable-http and `--disable-https` flags you can disable http or https, but that will work for all ingresses

did you meant to do it like that or you want it per ingress ?

another option is to use
https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resource-tcp.md but its different port then
