### ISSUE TITLE
ingress class for TCP balancing objects

### ISSUE THREAD

**Issue by fo511** [haproxytech/kubernetes-ingress#674]
Helllo. I have two haproxy ingresses with different class in my cluster.
When I create TCP object, I see that both ingresses now use it in their configuration.
Is it my misconfiguration or inteded behaviour? Can't find any ingressClass option in TCP CRD.

**Comment by hdurand0710** [comment]
Hello @fo511 ,
This is indeed the current intended behavior but it's planned to add the ingressClass into the TCP CRD (https://github.com/haproxytech/kubernetes-ingress/issues/666).

**Comment by fo511** [comment]
@hdurand0710 thank you.
