### ISSUE TITLE
Ingress controller in External mode on-premise: multiple clusters support

### ISSUE THREAD

**Issue by NumenDivinum** [haproxytech/kubernetes-ingress#682]
Hello!

Is it possible to have an HAProxy Ingress controller in External mode on-premise serve more than one cluster? 
Is it as direct as having more than one cluster in the kubeconfig file - will it just work with all of them?
Are there any limitations?
Are there any configuration examples of such setup?

Thank you!

**Comment by oktalz** [comment]
hi @NumenDivinum,

we do not have plans to implement this in ingress controller, its out of scope of this project
