### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by kennyjwilli** [haproxytech/kubernetes-ingress#7]
It'd be great to have the ability to deploy using a Helm Chart.

**Comment by oktalz** [comment]
hi, agreed, we will provide one soon

**Comment by redr0bin** [comment]
Any news on that ? Curious to try the haproxy-ingress :)

**Comment by bedis** [comment]
Hi,

I understand the need to support a "deployment" tool.
That said, should we support helm or kustomize or k8s-handle (append yours here) or maybe all of them?

what type of feature / customization do you expect from such tool?

**Comment by nikicat** [comment]
Hello, +1 for helm support. Something similar to https://github.com/helm/charts/tree/master/stable/nginx-ingress is desired for me.

**Comment by redr0bin** [comment]
Hello, +1 for helm, as it seems to me this is the most widespread tool and works well with k8s deployment operators

**Comment by AlecTroemel** [comment]
Hi everyone! I have a WIP helm chart here https://github.com/mirusresearch/charts. Its based on the community haproxy ingress controller's chart and the yaml files this project gives. I have a MR to add our helm chart repo to helm hub, but if you want to try it out now you can add the repo manually 

```
helm repo add mirusresearch https://mirusresearch.github.io/charts/
```

**Comment by DandyDeveloper** [comment]
Helm is definitely my :+1:. 

If you're open to contributions, you could kickstart it on the [official helm repository](https://github.com/helm/charts/) as an incubator.

**Comment by AlecTroemel** [comment]
@DandyDeveloper I actually started with a [MR to incubator in the official helm repo](https://github.com/helm/charts/pull/15187). One of the maintainers said that helm hub is the new preferred way to publish charts https://helm.sh/blog/intro-helm-hub/.

**Comment by DandyDeveloper** [comment]
@AlecTroemel Someone forgot to send me the memo! 

Where's the repository for people to contribute to?

**Comment by bedis** [comment]
@DandyDeveloper is this what you're looking for: https://github.com/mirusresearch/charts/tree/master/haproxytech-haproxy-ingress ?

**Comment by Mo3m3n** [comment]
Lost track of this issue but we do provide a Helm Chart for more than a year now:
https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress
