### ISSUE TITLE
Haproxy Ingress Controller Detects Loopback addresses from service's pods

### ISSUE THREAD

**Issue by shellscriptcode** [haproxytech/kubernetes-ingress#72]
We have currently total 105 pods running  and exposed with service. We set ingress and haproxy ingress controller with ingress having only one rule / for service. What we have observed is that haproxy ingress controller in discovery also discovers loop back addresses with pod targetport [ same port ]. 

**127.0.0.1:port**

You can see in below dashboard. All with brown lines are added which have loopback address and pods targetport which is behind service. So in logs we get more backend. Although they are added as disabled. But still we want avoid this kind of service discovery by ingress controller.

![image](https://user-images.githubusercontent.com/7248187/65374169-66442500-dca4-11e9-8a7b-a518f40d51f4.png)

Please suggest if this bug can be fixed? We are also using this official haproxy ingress controller in production.

**Comment by bedis** [comment]
Can you share the output of: `kubectl get endpoints <serviceName>` ?

**Comment by shellscriptcode** [comment]
kubectl get endpoints <serviceName> 

Output:

![abcd](https://user-images.githubusercontent.com/7248187/65485121-8e0ed500-debe-11e9-9575-d4110851c956.jpg)

**Comment by bedis** [comment]
A screenshot is not very verbose.
Could you try such command:
`kubectl -n demo get endpoints <serviceName> -o yaml | fgrep '127.0.0'`

**Comment by shellscriptcode** [comment]
@bedis 

When i run command:

kubectl -n REDACTED get endpoints REDACTED -o yaml | fgrep '127.0.0'

I do not get any output. It seems not as single pod behind service is having loop back address, But yes when haproxy ingress controller get all servers, it also detects some loopback addresses as well.

I could not share actual namespace and service name due to security reasons.

**Comment by bedis** [comment]
I just wanted to check what was exposed by kubernetes.
So it seems that no IPs are reported by k8s as 127.0.0.1.

Can you go in the pod, extract the server list from this backend and run the following:
`fgrep -c server extract.txt`
`fgrep -c 127.0.0.1 extract.txt`
`fgrep -c -v 127.0.0.1 extract.txt`

**Comment by shellscriptcode** [comment]
@bedis 

I logged in on haproxy ingress controller pod, and i got below output: We are going live today:
```
/ # fgrep -c server /etc/haproxy/haproxy.cfg 
1777
/ # fgrep -c 127.0.0.1 /etc/haproxy/haproxy.cfg 
1363
/ # fgrep -c -v 127.0.0.1 /etc/haproxy/haproxy.cfg 
452
```

**Comment by bedis** [comment]
so this looks normal :)
The controller currently reserve server "slots" for future growth. This allows it to follow-up scale out of your app and rolling update without reloading HAProxy.

Imagine your application scales out, then HAProxy has to follow-up. Usually, you do this by adding new server lines in the config file then reload HAProxy.
To avoid this reload sequence, the controller pre-provision servers in MAINT mode with dummy IP set to 127.0.0.1 and when the scale out happens, the controller pick one of the server in MAINT mode, configure it with Pod IP, port and some other settings if required at run time, maintain the config file up to date but does not perform any reload!

**Comment by shellscriptcode** [comment]
Great Logic. Thank you @bedis for support and clarification.

**Comment by bedis** [comment]
Also note that the ingress controller automatically detects if there are enough slots available and if not, it will increase this number in the config file and then trigger a reload:
https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#servers-slots-increment
