### ISSUE TITLE
Support for a custom log-format

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#75]
Hi there,

Would be great to support custom log-format annotation.
This would be applied globally through the configmap and added in the defaults section.

https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4-log-format

Note that we can currently "hardcode" such feature in the global.cfg file available in the controller's file system.

Maybe to make it more turnkey for later, we should also propose some pre-formated log format for compatibility with third parties such as ELK, splunk, etc...

**Comment by Mo3m3n** [comment]
Supported via [log-format](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#log-format) annotation
