### ISSUE TITLE
http-request capture rules

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#80]
This is related to other issues about syslog.
It is important in many cases to be able to capture request or response headers:
- https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-request%20capture
- https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-response%20capture

**Comment by Mo3m3n** [comment]
This was added since `haproxytech/kubernetes-ingress:1.3.3` 
you can use request-capture annotation documented here: https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#request-capture
