### ISSUE TITLE
Support for errorfile

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#82]
When some error occur, HAProxy returns by default a "simple" error page, that said, it also allows for customization of this page through the errorfile directive:
https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#errorfile

Would be great to support both globally (defaults section) or per service (backend section) error file for people who want to customize such errors

**Comment by Mo3m3n** [comment]
Supported from 1.5 via [--configmap-errorfile](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--configmap-errorfile) controller arg
