### ISSUE TITLE
cookie based persistence

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#88]
Allow cookie based persistence, per service.
https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#cookie

This one is pretty large, but I can see 2 main usecase:
1. "cookie insert NAME dynamic" to let HAProxy set a cookie itself
2. "cookie prefix NAME dynamic" to allow HAProxy to use a cookie set by the app

Some options may be good candidates too: indirect, nocache, httponly, maxidle, maxlife.
"dynamic" should be used in all cases to make this feature reliable

**Comment by andreasdrougge** [comment]
I have done a PR for this now: https://github.com/haproxytech/kubernetes-ingress/pull/145

**Comment by Mo3m3n** [comment]
Available from v1.3.2
