### ISSUE TITLE
IPV6 support?

### ISSUE THREAD

**Issue by dimm0** [haproxytech/kubernetes-ingress#9]
Doesn't seem to work in IPV6-enabled cilium

**Comment by oktalz** [comment]
Hi, 

ipv6 support will be added soon, its in roadmap.

**Comment by oktalz** [comment]
ipv6 support was added in v1.1.5

**Comment by danehans** [comment]
@oktalz is ipv6 support documented? I reviewed the config guide and see no IPv6 references. Here are a couple examples of projects that document ipv6 support:

- https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- https://docs.projectcalico.org/v3.5/usage/ipv6

Can you also link to the PR that added ipv6 support?

/cc @bedis

**Comment by oktalz** [comment]
@danehans 
this was added with commit d407be1
HAProxy now listens both ipv4 & ip6 traffic, 
so it really depends more on how how you configure you cluster.
