### ISSUE TITLE
Application root path

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#94]
Related to #83 .
The idea here is to "enforce" a root path where the application expect traffic.
So it's an entire rewrite of the path to the value provided by this annotation.
It's a per ingress rule configuration

**Comment by Mo3m3n** [comment]
Since `1.4.3` you can use [path-rewrite](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/README.md#path-rewrite) with single param to do this.
Feel free to reopen the ticket if this does not answer your requirement
