### ISSUE TITLE
Server side protocol

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#95]
Currently, we don't support SSL on the server side, would be great to have an annotation to allow this.

**Comment by andreasdrougge** [comment]
first version could be to ignore validation.
check-ssl ssl verify none

**Comment by andreasdrougge** [comment]
Did a simple PR here:
https://github.com/haproxytech/kubernetes-ingress/pull/143

**Comment by Mo3m3n** [comment]
Currently, both ssl and clear H2 should be supported via annotations server-ssl and server-proto
We are planning to support fcgi too in 1.6
