### ISSUE TITLE
Allow for HTTP healthcheck

### ISSUE THREAD

**Issue by GoodMirek** [haproxytech/kubernetes-ingress#96]
Currently, only TCP healthcheck is supported.
We use /status endpoint for our services, as it allows detection of more failures than TCP check.

**Comment by Mo3m3n** [comment]
This was added in #90 and available in [v1.2.3](https://github.com/haproxytech/kubernetes-ingress/releases/tag/v1.2.3) release.

**Comment by bedis** [comment]
Thanks @Mo3m3n

**Comment by GoodMirek** [comment]
Thanks @Mo3m3n !
