### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by travisghansen** [haproxytech/kubernetes-ingress#99]
I'm currently running the ingress controller in a simple setup to test. I've had the images set to autoupdate (using the `keel` project). A month ago or so an update (unfortunately don't know which version exactly as I'm simply tracking `latest` currently) started making pod memory go out the roof.  The controller/pods are literally doing nothing (although some prometheus endpoints may be getting hit in an automated fashion by the cluster itself) and my usage climbs linearly. For example I've currently got 3 replicas that have been running for 14hours and they're sitting just under 6GB of memory usage each.

Here's the diff to the yaml that I've made:

```
--- haproxy-ingress.yaml.1	2019-10-13 16:39:17.459985188 -0600
+++ haproxy-ingress.yaml	2019-07-05 21:35:31.672175096 -0600
@@ -81,7 +81,7 @@
 kind: ConfigMap
 metadata:
   name: haproxy-configmap
-  namespace: default
+  namespace: haproxy-controller
 data:
 
 ---
@@ -133,8 +133,14 @@
     run: haproxy-ingress
   name: haproxy-ingress
   namespace: haproxy-controller
+  annotations:
+    keel.sh/pollSchedule: "@every 24h"
+    #keel.sh/pollSchedule: "@every 3m"
+    keel.sh/trigger: poll
+    keel.sh/policy: force
+    keel.sh/match-tag: "true"
 spec:
-  replicas: 1
+  replicas: 3
   selector:
     matchLabels:
       run: haproxy-ingress
@@ -148,7 +154,8 @@
       - name: haproxy-ingress
         image: haproxytech/kubernetes-ingress
         args:
-          - --configmap=default/haproxy-configmap
+          - --default-ssl-certificate=haproxy-controller/tls-secret
+          - --configmap=haproxy-controller/haproxy-configmap
           - --default-backend-service=haproxy-controller/ingress-default-backend
         resources:
           requests:
```

I have just noticed that the secret for the `--default-ssl-certificate` doesn't exist so maybe it's connected.

**Comment by oktalz** [comment]
hi @travisghansen 

if you fetch logs from controller, right at start there should be a line with a version.

Also, you can enter image with:
`kubectl exec --namespace=haproxy-controller -it POD_NAME_HERE /bin/sh;`
and then execute:
`./haproxy-ingress-controller -vv`

missing secret should not create any problems, at least not with RAM usage.

**Comment by travisghansen** [comment]
```
2019/10/16 13:44:20 HAProxy Ingress Controller v1.2.3 7fc1cd6

2019/10/16 13:44:20 Build from: git@github.com:haproxytech/kubernetes-ingress.git
2019/10/16 13:44:20 Build date: 2019-10-09T06:30:02

2019/10/16 13:44:20 ConfigMap: haproxy-controller/haproxy-configmap
2019/10/16 13:44:20 Ingress class: haproxy
2019/10/16 13:44:20 main.go:83: Default backend service: haproxy-controller/ingress-default-backend
2019/10/16 13:44:20 main.go:84: Default ssl certificate: haproxy-controller/tls-secret
2019/10/16 13:44:20 controller.go:89: Starting HAProxy with /etc/haproxy/haproxy.cfg
2019/10/16 13:44:20 controller.go:108: Running on haproxy-ingress-566cc854f-5g6dc
[WARNING] 288/134421 (18) : Can't open server state file '/var/state/haproxy/global': No such file or directory
2019/10/16 13:44:21 controller.go:70: Running on Kubernetes version: v1.15.4 linux/amd64
[NOTICE] 288/134421 (21) : New worker #1 (22) forked
2019/10/16 13:44:26 controller-haproxy.go:171: HAProxy reloaded
[NOTICE] 288/134426 (34) : New worker #1 (35) forked
```

**Comment by Mo3m3n** [comment]
There is indeed a memory leak.
Thanks @travisghansen for reporting this.
I have sent a PR #102  to fix this.

**Comment by travisghansen** [comment]
Thanks for digging into it!

Something I can work around or something related to how I've deployed?

It's a pretty linear line watching the memory usage go up and up.

**Comment by oktalz** [comment]
Hi @travisghansen 

Thx for all the info, @Mo3m3n did a wonderful job with finding out what caused this.
Best option is to pull new version `1.2.4` or fetch new `latest` tag with fix for this.

**Comment by travisghansen** [comment]
If it's in latest I'll pull it down and report back within a day or so. I'll know pretty quickly if I'm still leaking memory :)

**Comment by travisghansen** [comment]
Much better! After 12 hours I'm sitting at `114.64 MiB`. Which is much better than `6 GB` :)

**Comment by travisghansen** [comment]
So over the course of a few days I'm now sitting at `120.43`. there may be some smaller memory leaks but the massive hole is for sure plugged.

**Comment by oktalz** [comment]
I'm going to close this since this is resolved with 1.2.4.

I'm still going to investigate further if there is a minor leak somewhere else

**Comment by travisghansen** [comment]
I'm currently sitting at `125.07`. that's after roughly 2 weeks.

**Comment by oktalz** [comment]
Not necessarily, Go 1.13 has changed a bit how memory is handled and minor memory increase is possible because of that.

However, most likely there is something else probably, that is causing this and we will look into it in detail.

**Comment by Mo3m3n** [comment]
This may just be related to haproxy memory usage. 5m increase after startup is something  common  if traffic size is changing.

**Comment by travisghansen** [comment]
Traffic is completely dormant (nothing is going to the ingress at all) as well as the ingress objects being dormant as well. It's a home cluster that changes very little at this point.

I do see the memory go up a bit just after start (which I would expect), but it does seem to be climbing slightly over time. I probably could throw it into a cluster to handle some actual traffic and see how it goes but you've probably got plenty of help on that front.

**Comment by travisghansen** [comment]
To be clear, I made the comment above about my current memory usage simply for historical/informational purposes, not because I'm dissatisfied (or think this should be re-opened) or anything of that nature.

**Comment by oktalz** [comment]
@travisghansen you already helped us a lot with this reporting :)

this small increase over time will be probably a bit harder to catch, 
but rest assured, we will find what is the true reason for this.
I was closing it because of a major leak we fixed.
